window.FABLEA_STORIES = {
  "2-4": [
    {
      title: "{{name}} e il lupo dal vocione",
      subtitle: "Una storia morbida dove la paura diventa gentilezza.",
      icon: "🌙 🐺 ✨",
      art: "forest",
      scene: "🌲 🐺 ✨",
      keywords: ["lupo", "bosco", "paura", "gentilezza"],
      ritual: "⭐ Stella luminosa",
      activity: "Costruisci una piccola tana morbida per il lupo gentile.",
      paragraphs: [
        "Nel bosco morbido, quando la luna saliva piano piano, {{name}} sentì un rumore grande tra le foglie.",
        "Era un rumore rotondo, profondo, un po’ tremolante. Le foglie fecero fru fru, i funghetti luminosi si abbassarono e una piccola lucciola si nascose dietro una radice.",
        "Poi arrivò una voce enorme: “GROOOOAR”. Non era un ruggito cattivo. Era solo troppo grande per quel bosco così piccolo.",
        "Dietro un albero comparve un lupo. Aveva zampe grandi, coda folta, orecchie morbide e occhi dolci. Il lupo abbassò la testa perché aveva capito di aver fatto paura.",
        "{{name}} rimase fermo. Non scappò. Guardò il lupo e vide che sotto quel vocione enorme c’era un cuore un po’ triste.",
        "Il lupo provò a parlare: “Buo...” ma uscì ancora un piccolo “GROAR”. Allora si sedette per terra e nascose il muso tra le zampe.",
        "Sotto una foglia, {{name}} trovò una piccola luce. Non era grande. Non era forte. Ma era calda e gentile.",
        "{{name}} prese la luce con delicatezza e la mise vicino al lupo. La luce non disse niente. Fece solo un piccolo bagliore dorato.",
        "Il lupo la guardò. Respirò una volta. Poi un’altra. Poi un’altra ancora. Ogni respiro faceva diventare il bosco più tranquillo.",
        "Alla fine il lupo provò di nuovo. Questa volta disse piano: “Buonasera”. Era una voce bassa, morbida, quasi come una coperta.",
        "Le foglie smisero di tremare. I funghetti tornarono dritti. La lucciola uscì dalla radice e si posò sul naso del lupo.",
        "Il lupo sorrise. {{name}} sorrise. E il bosco capì che a volte una cosa grande ha solo bisogno di imparare a diventare piccola.",
        "Prima di tornare, {{name}} lasciò una stellina accesa vicino all’albero. Così il lupo avrebbe ricordato la sua voce gentile anche il giorno dopo."
      ]
    },

    {
      title: "{{name}} e la piccola luce",
      subtitle: "Una storia visiva, morbida e rassicurante.",
      icon: "🌙 ✨ 🧸",
      art: "space",
      scene: "🌙 ✨ 🧸",
      keywords: ["luce", "luna", "calma", "orsetto"],
      ritual: "🌙 Luna silenziosa",
      activity: "Accendi una piccola luce morbida e raccontale dove deve brillare.",
      paragraphs: [
        "Vicino a {{name}} comparve una piccola luce. Non arrivò all’improvviso. Prima sembrò un puntino, poi una goccia dorata, poi una stellina vicina.",
        "La luce non correva. Non saltava. Non faceva rumore. Restava lì, tranquilla, come se sapesse aspettare.",
        "{{name}} la guardò. La luce fece un piccolo brillio, come per dire: “Sono qui”.",
        "Poco dopo arrivò un orsetto morbido. Aveva una sciarpa piccola e camminava piano, con passi rotondi.",
        "Poi arrivò una nuvola bianca, così soffice che sembrava fatta di respiro. Dietro la nuvola, una stellina fece cucù.",
        "Tutti si sedettero vicino a {{name}}. Nessuno aveva fretta. Nessuno chiedeva niente. Il mondo sembrava più lento.",
        "La piccola luce si spostò un pochino e illuminò l’orsetto. L’orsetto sorrise. Poi illuminò la nuvola. La nuvola fece un piccolo dondolio.",
        "La stellina salì in alto e disegnò un cerchio nel cielo. Non era un cerchio perfetto, ma era bellissimo.",
        "{{name}} sentì che quella luce non serviva a vedere tutto. Serviva a vedere abbastanza. Abbastanza per sentirsi al sicuro.",
        "La luna si avvicinò piano al bordo del cielo. Guardò {{name}}, guardò l’orsetto, guardò la luce, e sembrò sorridere.",
        "La luce diventò un po’ più piccola, ma non sparì. Rimase lì, come una promessa morbida.",
        "Quando il mondo diventò più scuro, {{name}} sapeva che poteva cercarla ancora.",
        "Perché alcune luci non devono essere grandi. Devono solo restare accese."
      ]
    },

    {
      title: "{{name}} e la balena luminosa",
      subtitle: "Una balena gentile illumina il mare calmo.",
      icon: "🐋 🌊 ✨",
      art: "ocean",
      scene: "🐋 🌊 ✨",
      keywords: ["balena", "mare", "oceano", "acqua", "calma"],
      ritual: "🌊 Conchiglia calma",
      activity: "Disegna una grande balena e tre stelline che dormono nel mare.",
      paragraphs: [
        "Nel mare calmo di FABLEA viveva una balena che brillava piano. Non era una luce forte. Era una luce blu, lenta, profonda.",
        "Ogni sera la balena saliva vicino alla riva, faceva un grande respiro e il mare diventava più tranquillo.",
        "{{name}} la vide comparire quando il cielo stava diventando color notte. Prima uscì una pinna, poi un dorso grande, poi un occhio dolce.",
        "La balena guardò {{name}} e fece un suono basso, come una ninna nanna dentro l’acqua.",
        "“Vuoi vedere dove dormono le stelle cadute?” chiese la balena con una voce lenta.",
        "Una piccola onda arrivò fino ai piedi di {{name}}. Non bagnava troppo. Era un’onda morbida, fatta apposta per accompagnare.",
        "{{name}} seguì la balena fino a una grotta d’acqua chiara. Dentro la grotta non c’era buio. C’erano piccole luci appese come lanterne.",
        "Erano stelle cadute dal cielo. Non erano rotte. Erano solo stanche e dormivano nel mare.",
        "La balena ne sfiorò una con il muso. La stellina fece un piccolo bagliore e poi tornò a riposare.",
        "“Anche le stelle hanno bisogno di calma,” disse la balena. “Anche le cose luminose si stancano.”",
        "{{name}} ascoltò il mare. Ogni onda faceva avanti e indietro, avanti e indietro, come un respiro.",
        "Prima di tornare alla riva, la balena regalò a {{name}} una conchiglia blu.",
        "“Quando hai bisogno di calma,” disse, “ascolta il mare dentro questa conchiglia.”"
      ]
    },

    {
      title: "{{name}} e la nuvola lenta",
      subtitle: "Una nuvola insegna la bellezza del non correre.",
      icon: "☁️ 🌤️ ✨",
      art: "sky",
      scene: "☁️ ✨ 🌤️",
      keywords: ["nuvola", "riposo", "cielo", "calma"],
      ritual: "☁️ Nuvola morbida",
      activity: "Disegna una nuvola grande e soffice, poi inventa dove sta andando.",
      paragraphs: [
        "Nel cielo di FABLEA c’era una nuvola che andava più piano di tutte.",
        "Le altre nuvole cambiavano forma in fretta. Una diventava cavallo, una diventava barca, una diventava cappello.",
        "Lei no. Lei restava tonda, morbida, tranquilla. Sembrava una coperta appesa al cielo.",
        "{{name}} la guardò a lungo. La nuvola se ne accorse e scese un pochino più in basso.",
        "“Perché vai così piano?” chiese {{name}}.",
        "La nuvola fece un piccolo sbuffo bianco. “Perché alcune cose belle si vedono solo quando non si corre.”",
        "Allora la nuvola mostrò a {{name}} un uccellino nascosto su un ramo. Era così piccolo che nessuna nuvola veloce lo aveva mai visto.",
        "Poi mostrò una luce dietro una foglia. Poi una porta minuscola sopra una collina. Poi un fiore che si stava aprendo lentamente.",
        "“Vedi?” disse la nuvola. “Il mondo non sparisce se vai piano. Anzi, diventa più grande.”",
        "{{name}} respirò. La nuvola respirò. Anche il cielo sembrò respirare.",
        "Per un momento non successe niente. E quel niente era bello.",
        "Prima di risalire, la nuvola lasciò a {{name}} un pezzetto di bianco morbido.",
        "“Tienilo per quando tutto corre troppo,” disse. “Ti ricorderà che puoi andare piano.”"
      ]
    },

    {
      title: "{{name}} e l’orsetto del sonno",
      subtitle: "Un orsetto guida verso un ritmo lento e sicuro.",
      icon: "🧸 🌙 💤",
      art: "space",
      scene: "🧸 🌙 💤",
      keywords: ["orsetto", "sonno", "riposo", "calma"],
      ritual: "🧸 Amico morbido",
      activity: "Scegli un peluche e inventa il suo posto sicuro.",
      paragraphs: [
        "{{name}} incontrò un orsetto con una coperta piccola sulle spalle.",
        "L’orsetto aveva occhi gentili e zampe tonde. Camminava piano, così piano che anche il vento si mise a camminare piano con lui.",
        "“Dove vai?” chiese {{name}}.",
        "“Vado sul sentiero del riposo,” rispose l’orsetto. “È un posto che si trova solo quando il mondo abbassa la voce.”",
        "{{name}} seguì l’orsetto. Il sentiero era fatto di piccole luci, cuscini di nuvola e foglie morbide.",
        "La prima luce disse: “Lascia qui la fretta”. La seconda disse: “Lascia qui il rumore”. La terza disse: “Porta solo un pensiero gentile”.",
        "Più camminavano, più il cielo diventava blu scuro e tranquillo.",
        "A un certo punto trovarono una stellina addormentata in mezzo al sentiero. Era caduta e non sapeva come tornare in cielo.",
        "{{name}} e l’orsetto la sollevarono piano, piano, piano. La stellina salì e si mise al suo posto.",
        "Il cielo fece un piccolo sorriso luminoso.",
        "“Quando aiutiamo qualcuno a riposare,” disse l’orsetto, “anche il nostro cuore diventa più leggero.”",
        "Alla fine del sentiero c’era una casetta fatta di luna e silenzio.",
        "L’orsetto diede a {{name}} un pezzetto di coperta luminosa. “Questo è per ricordare che il mondo può diventare morbido quando serve.”"
      ]
    },

    {
      title: "{{name}} e il giardino addormentato",
      subtitle: "Un giardino si sveglia con piccoli gesti gentili.",
      icon: "🌷 💤 ✨",
      art: "forest",
      scene: "🌷 🐞 ✨",
      keywords: ["giardino", "fiori", "natura", "gentilezza"],
      ritual: "🌷 Semino dorato",
      activity: "Disegna un fiore addormentato e poi sveglialo con un colore.",
      paragraphs: [
        "{{name}} trovò un giardino dove tutti i fiori dormivano.",
        "Dormivano i tulipani, dormivano le margherite, dormivano le violette piccole vicino al sentiero.",
        "Non erano tristi. Non erano rotti. Erano solo molto stanchi.",
        "Una coccinella con un cappellino rosso uscì da sotto una foglia.",
        "“Qui si sveglia tutto con gentilezza,” disse. “Niente rumore forte, niente fretta.”",
        "{{name}} si avvicinò a un fiore chiuso e soffiò piano. Il fiore aprì un petalo.",
        "Poi toccò una foglia. La foglia fece una goccia luminosa.",
        "La goccia cadde sulla terra e la terra fece un piccolo profumo di primavera.",
        "Poco alla volta, il giardino cominciò a svegliarsi. Una margherita sbadigliò. Un tulipano si stiracchiò. Una rosa fece un sorriso appena appena.",
        "La coccinella batté le ali, felice.",
        "“Vedi?” disse. “Non serve fare tanto. A volte basta fare piano.”",
        "Quando il giardino fu sveglio, ma ancora tranquillo, regalò a {{name}} un semino dorato.",
        "“Piantalo quando vuoi far crescere una cosa gentile,” sussurrò la terra."
      ]
    },

    {
      title: "{{name}} e la stellina silenziosa",
      subtitle: "Una stellina insegna che anche il silenzio può brillare.",
      icon: "⭐ 🤫 🌙",
      art: "space",
      scene: "⭐ 🌙 🤫",
      keywords: ["stella", "silenzio", "luna", "calma"],
      ritual: "⭐ Stella silenziosa",
      activity: "Cerca nella stanza un oggetto silenzioso e dagli un nome magico.",
      paragraphs: [
        "Nel cielo di FABLEA c’era una stellina che non parlava mai.",
        "Le altre stelline facevano scintille, risatine e piccoli suoni luminosi.",
        "Lei invece brillava in silenzio. Non perché fosse triste. Era il suo modo di stare nel cielo.",
        "{{name}} la vide subito. Tra tante luci che si muovevano, quella stellina quieta sembrava speciale.",
        "La stellina scese piano, piano, piano, fino a posarsi su una coperta di luna.",
        "“Non parli?” chiese {{name}}.",
        "La stellina non rispose con parole. Fece una luce morbida, più calda, più vicina.",
        "{{name}} capì che quella luce diceva: “Sono qui”.",
        "Poi la stellina illuminò un piccolo sasso, una foglia, un filo d’erba. Tutte cose silenziose. Tutte cose importanti.",
        "Il silenzio non sembrava più vuoto. Sembrava una stanza piena di piccole luci.",
        "La luna guardò {{name}} e sembrò dire: “A volte non servono tante parole per restare vicini.”",
        "Prima di tornare in cielo, la stellina lasciò un puntino dorato nel mondo FABLEA.",
        "Era piccolo, ma brillava abbastanza per essere ritrovato."
      ]
    },

    {
      title: "{{name}} e il coniglio della sera",
      subtitle: "Un coniglio prepara il mondo con piccoli gesti lenti.",
      icon: "🐰 🌙 🕯️",
      art: "forest",
      scene: "🐰 🌙 🕯️",
      keywords: ["coniglio", "sera", "rituale", "luna"],
      ritual: "🕯️ Lucina della sera",
      activity: "Prepara tre oggetti piccoli per chiudere la giornata: luce, peluche, coperta.",
      paragraphs: [
        "Quando il cielo diventò color miele, un coniglio bianco comparve davanti a {{name}}.",
        "Aveva una piccola borsa piena di cose lente: una piuma, una stella, una foglia, una lucina e un campanellino che non suonava quasi mai.",
        "“Ogni sera preparo il mondo a riposare,” disse il coniglio.",
        "Prima mise la piuma sotto una nuvola. La nuvola diventò più comoda.",
        "Poi mise la stella vicino alla luna. La luna diventò un po’ più luminosa.",
        "Poi sistemò la foglia sopra un sasso. Il sasso sembrò meno freddo.",
        "{{name}} lo aiutò ad accendere la lucina più piccola.",
        "La lucina non illuminò tutto. Illuminò solo il punto giusto.",
        "“Vedi?” disse il coniglio. “La sera non ha bisogno di tanta luce. Ha bisogno di una luce gentile.”",
        "Poi aprì la borsa e mostrò uno spazio vuoto.",
        "“Questo è per il gesto di domani,” spiegò. “Ogni sera può avere il suo piccolo rito.”",
        "{{name}} guardò il cielo color miele diventare blu.",
        "Il coniglio fece un inchino e saltellò via, lasciando la lucina accesa."
      ]
    },

    {
      title: "{{name}} e il pesciolino dorato",
      subtitle: "Una piccola creatura insegna a seguire una luce calma.",
      icon: "🐠 ✨ 🌊",
      art: "ocean",
      scene: "🐠 ✨ 🌊",
      keywords: ["pesce", "mare", "luce", "acqua"],
      ritual: "🐚 Perla calma",
      activity: "Disegna un pesciolino e tre bolle luminose.",
      paragraphs: [
        "In una pozzanghera grande come un piccolo mare, {{name}} vide un pesciolino dorato.",
        "Il pesciolino nuotava piano e lasciava dietro di sé tre bolle luminose.",
        "La prima bolla era piccola. La seconda era tonda. La terza brillava come una perla.",
        "“Dove vai?” chiese {{name}}.",
        "“Cerco una luce che non abbia fretta,” rispose il pesciolino.",
        "{{name}} lo seguì con gli occhi. Il pesciolino girò intorno a una foglia, passò sotto un riflesso di cielo e si fermò vicino a un sassolino.",
        "Sul sassolino c’era una perla calma. Non brillava tanto. Brillava bene.",
        "“È questa,” disse il pesciolino. “La luce che non corre.”",
        "{{name}} guardò la perla. Sembrava respirare insieme all’acqua.",
        "Il pesciolino la spinse verso la riva con il naso.",
        "“Tienila,” disse. “Quando il mondo sembra troppo pieno, guarda una cosa piccola.”",
        "Poi il pesciolino dorato fece un giro lento e tornò nel suo piccolo mare."
      ]
    },

    {
      title: "{{name}} e la porta piccolissima",
      subtitle: "Una porta minuscola apre un mondo grande ma gentile.",
      icon: "🚪 ✨ 🐭",
      art: "forest",
      scene: "🚪 ✨ 🐭",
      keywords: ["porta", "topolino", "scoperta", "bosco"],
      ritual: "🚪 Chiave gentile",
      activity: "Disegna una porta minuscola e cosa c’è dietro.",
      paragraphs: [
        "{{name}} trovò una porta piccolissima vicino a una radice.",
        "Era così piccola che sembrava fatta per una formica elegante o per un topolino con un cappello.",
        "La porta aveva una maniglia dorata grande come una briciola.",
        "Da dietro la porta arrivò un toc toc leggero.",
        "Poi uscì un topolino con una chiave grande quasi quanto lui.",
        "“Questa porta si apre solo se si bussa piano,” disse il topolino.",
        "{{name}} bussò con un dito leggero. Toc. Toc. Toc.",
        "La porta si aprì e dietro c’era una stanza piena di lucine che aspettavano in silenzio.",
        "Ogni lucina aveva una sedia piccola. Ogni sedia aspettava una storia.",
        "Il topolino diede a {{name}} una chiave invisibile.",
        "“Non apre tutte le porte,” spiegò. “Apre solo quelle che hanno bisogno di gentilezza.”",
        "{{name}} la tenne con cura, anche se non si vedeva.",
        "Perché certe chiavi non si vedono con gli occhi. Si sentono quando si usa piano il cuore."
      ]
    }
  ],

 "5-7": [

{
title:"{{name}} e la mappa luminosa",
subtitle:"Una storia di esplorazione, piccoli passi e meraviglia.",
icon:"📖 🗺️ ✨",
art:"forest",
scene:"🦊 🗺️ ✨",
keywords:["mappa","bosco","volpe","avventura"],
ritual:"🗺️ Mappa dorata",
activity:"Disegna una nuova parte della mappa.",
paragraphs:[
"{{name}} trovò un libro dimenticato sopra un tavolo. La copertina era liscia, calda e un po’ misteriosa.",
"Quando lo aprì, non trovò solo parole. Dentro c’era una mappa che brillava piano, come se respirasse.",
"Sulla mappa comparivano sentieri, alberi, piccole stelle e un bosco disegnato con linee dorate.",
"Tra le radici del bosco comparve una volpe gentile. “Non bisogna correre per vivere un’avventura,” disse. “Basta fare un passo e ascoltare.”",
"{{name}} seguì la volpe fino a una radura dove le foglie facevano luce sotto le scarpe.",
"In mezzo alla radura c’era una lanterna sospesa nel vuoto. Non cadeva. Restava lì, come se stesse aspettando qualcuno.",
"Quando {{name}} la toccò, sulla mappa apparve un nuovo sentiero mai visto prima.",
"La volpe sorrise. “Le mappe vive cambiano quando qualcuno trova il coraggio di guardare meglio.”",
"Il nuovo sentiero attraversava un ponte di legno sospeso sopra un lago nero e lucido come uno specchio.",
"Nel lago si vedevano stelle che il cielo non aveva ancora acceso.",
"Alla fine del ponte comparve una piccola casa con il tetto blu. Dentro c’era un vecchio cartografo.",
"Il cartografo guardò {{name}} e disse: “Le mappe più importanti non mostrano dove andare. Mostrano chi stai diventando.”",
"Prima di andare via, il cartografo regalò a {{name}} una bussola dorata.",
"La bussola non indicava il nord. Indicava sempre la meraviglia."
]
},

{
title:"{{name}} e il treno delle stelle",
subtitle:"Un viaggio notturno attraverso il cielo.",
icon:"🚂 ⭐ 🌌",
art:"space",
scene:"🚂 ⭐ 🌌",
keywords:["treno","stelle","spazio","viaggio"],
ritual:"⭐ Biglietto stellare",
activity:"Disegna la tua carrozza ideale del treno delle stelle.",
paragraphs:[
"La notte in cui il cielo sembrava più vicino del solito, {{name}} sentì un fischio dietro la finestra.",
"Fuori non c’era una macchina. Non c’era un autobus. C’era un piccolo treno blu fermo sopra un binario fatto di luce.",
"Il capotreno era un gufo con occhiali tondi e un orologio d’oro.",
"“Biglietto?” chiese.",
"“Non ce l’ho,” rispose {{name}}.",
"Il gufo sorrise. “Per salire basta una domanda vera.”",
"{{name}} ci pensò un momento. Poi fece la sua domanda al cielo.",
"Il gufo timbrò un biglietto stellare comparso dal nulla.",
"Appena il treno partì, le case diventarono piccole e il cielo si aprì come un oceano.",
"La prima stazione era fatta di lune addormentate.",
"La seconda stazione custodiva nuvole che ricordavano i sogni dimenticati dai bambini.",
"Nella terza stazione viveva un uomo che riparava stelle rotte con ago e filo d’argento.",
"“Anche le stelle si rompono ogni tanto,” disse l’uomo. “Ma non smettono di brillare.”",
"Prima di tornare, il gufo regalò a {{name}} un pezzetto di cielo notturno piegato come carta.",
"“Tienilo vicino,” disse. “Così saprai sempre che esistono strade sopra le nuvole.”"
]
},

{
title:"{{name}} e il castello sospeso",
subtitle:"Un castello nel cielo custodisce una chiave speciale.",
icon:"🏰 ☁️ ✨",
art:"castle",
scene:"🏰 ☁️ ✨",
keywords:["castello","nuvole","chiave","cielo"],
ritual:"🗝️ Chiave del cielo",
activity:"Disegna il castello sospeso e la sua porta segreta.",
paragraphs:[
"Tra due nuvole altissime, {{name}} vide un castello sospeso nel cielo.",
"Non era appoggiato a nulla. Restava in aria grazie a fili sottili di luce dorata.",
"Le torri sembravano fatte di vento e pietra insieme.",
"Alla porta del castello c’era una piccola chiave appesa a un filo.",
"Un cavaliere con un mantello blu stava seduto sui gradini.",
"“Questa porta non si apre con la forza,” spiegò. “Si apre solo con la parola giusta.”",
"{{name}} provò a dire parole enormi, complicate e rumorose. Ma la porta restò chiusa.",
"Poi guardò il cielo, respirò e disse una parola semplice.",
"La porta si illuminò immediatamente.",
"All’interno del castello c’erano stanze piene di mappe, telescopi e stelle sospese dentro barattoli di vetro.",
"Nel salone centrale dormiva un drago bianco gigantesco.",
"Il drago aprì un occhio e disse: “Le cose più importanti si aprono sempre piano.”",
"Prima di andare via, il cavaliere regalò a {{name}} la piccola chiave dorata.",
"“Non apre castelli,” spiegò. “Apre possibilità.”"
]
},

{
title:"{{name}} e il guardiano del faro",
subtitle:"Una luce nel mare guida chi si è perso.",
icon:"🌊 🕯️ 🌙",
art:"ocean",
scene:"🌊 🕯️ 🌙",
keywords:["mare","faro","oceano","luce"],
ritual:"🕯️ Luce del faro",
activity:"Disegna il faro e la sua luce sul mare.",
paragraphs:[
"In mezzo al mare di FABLEA esisteva un faro che non compariva sulle mappe normali.",
"Compariva solo quando qualcuno aveva bisogno di una luce.",
"Una sera {{name}} vide il mare illuminarsi in lontananza.",
"Vicino alle onde c’era una piccola barca che sembrava aspettare proprio lì.",
"{{name}} salì sopra e il mare cominciò a muoversi lentamente.",
"Il faro era altissimo. Le finestre brillavano color ambra.",
"In cima viveva il guardiano del faro, un uomo con capelli bianchi e occhi gentili.",
"“La mia luce non serve alle navi,” spiegò. “Serve ai pensieri che si sentono persi.”",
"Ogni notte il guardiano accendeva la grande lanterna e il mare diventava più tranquillo.",
"{{name}} aiutò il guardiano a girare la gigantesca ruota della luce.",
"Quando la lanterna si accese, il cielo e il mare sembrarono respirare insieme.",
"“Ricorda,” disse il guardiano. “Anche una piccola luce può aiutare qualcuno a ritrovare la strada.”",
"Prima di tornare, regalò a {{name}} una mini lanterna dorata.",
"Brillava solo quando serviva davvero."
]
},

{
title:"{{name}} e la biblioteca segreta",
subtitle:"Una biblioteca che custodisce storie vive.",
icon:"📚 ✨ 🌙",
art:"castle",
scene:"📚 ✨ 🌙",
keywords:["biblioteca","libri","storie","magia"],
ritual:"📖 Pagina dorata",
activity:"Inventa il titolo di un nuovo libro magico.",
paragraphs:[
"Nascosta dietro una parete piena di edera viveva una biblioteca segreta.",
"Le sue finestre brillavano solo di notte.",
"Quando {{name}} entrò, i libri si mossero leggermente sugli scaffali.",
"Non erano libri normali. Respiravano piano.",
"Una bibliotecaria con lunghi capelli argentati si avvicinò sorridendo.",
"“Qui custodiamo storie vive,” spiegò. “Ogni volta che qualcuno immagina davvero, un libro cambia.”",
"{{name}} aprì un volume enorme con la copertina blu.",
"All’interno non c’erano solo parole: c’erano cieli, oceani, castelli e città intere.",
"Ogni pagina sembrava muoversi lentamente.",
"La bibliotecaria mostrò una stanza piena di libri ancora vuoti.",
"“Questi aspettano bambini pronti a immaginare qualcosa che ancora non esiste.”",
"Prima di andare via, un piccolo libro dorato saltò giù dallo scaffale.",
"La bibliotecaria sorrise. “Ha scelto te.”",
"Sulla copertina apparve lentamente il nome di {{name}}."
]
},

{
title:"{{name}} e il drago delle lanterne",
subtitle:"Un drago custodisce luci perdute.",
icon:"🐉 🏮 ✨",
art:"castle",
scene:"🐉 🏮 ✨",
keywords:["drago","lanterne","luce","castello"],
ritual:"🏮 Lanterna dorata",
activity:"Disegna una lanterna magica.",
paragraphs:[
"Sopra una montagna altissima viveva un drago che collezionava lanterne.",
"Ogni lanterna custodiva una luce diversa.",
"Una notte {{name}} vide il cielo riempirsi di piccoli punti dorati.",
"Seguendo quelle luci arrivò fino alla montagna del drago.",
"Il drago era enorme ma aveva occhi tranquilli.",
"“Le persone pensano che io custodisca tesori,” disse. “In realtà custodisco luci.”",
"Mostrò a {{name}} una lanterna azzurra che conteneva il coraggio.",
"Una lanterna verde custodiva la calma.",
"Una piccola lanterna rossa custodiva la speranza.",
"Il drago spiegò che alcune luci si spengono se nessuno le guarda più.",
"Per questo ogni notte lui volava sopra FABLEA per raccogliere le luci dimenticate.",
"Prima che {{name}} andasse via, il drago regalò una piccola lanterna dorata.",
"“Non illuminerà tutto,” disse. “Illuminerà ciò che conta.”"
]
},

{
title:"{{name}} e il ponte di carta",
subtitle:"Un ponte fragile porta verso un posto speciale.",
icon:"🌉 📜 ✨",
art:"bridge",
scene:"🌉 📜 ✨",
keywords:["ponte","carta","città","viaggio"],
ritual:"📜 Foglio del coraggio",
activity:"Costruisci un piccolo ponte con carta o cartoncino.",
paragraphs:[
"Tra due colline lontane esisteva un ponte fatto interamente di carta.",
"Sembrava fragile. Troppo fragile per attraversarlo.",
"Ma ogni volta che qualcuno faceva un passo sincero, il ponte diventava più forte.",
"{{name}} guardò in basso. Sotto il ponte scorreva un fiume pieno di stelle riflesse.",
"All’inizio il vento muoveva i fogli del ponte facendoli tremare.",
"Poi comparve una ragazza con un mantello argentato.",
"“Questo ponte non regge chi ha fretta,” spiegò. “Regge chi ascolta.”",
"{{name}} fece il primo passo lentamente.",
"Il foglio sotto i piedi brillò di luce bianca.",
"Più il viaggio continuava, più il ponte diventava stabile.",
"Alla fine del percorso apparve una città fatta di carta luminosa.",
"Ogni casa raccontava una storia diversa.",
"La ragazza sorrise: “Le cose delicate non sono sempre deboli.”",
"E il ponte rimase acceso dietro {{name}}, come un sentiero di luce."
]
},

{
title:"{{name}} e il mercato della luna",
subtitle:"Un luogo notturno dove si vendono cose impossibili.",
icon:"🌙 🏮 ✨",
art:"sky",
scene:"🌙 🏮 ✨",
keywords:["mercato","luna","magia","notte"],
ritual:"🌙 Moneta lunare",
activity:"Inventa una bancarella magica.",
paragraphs:[
"Una notte {{name}} trovò una scala nascosta dietro una nuvola.",
"La scala saliva fino a una piazza illuminata da centinaia di lanterne.",
"Era il mercato della luna.",
"Non vendeva pane o vestiti. Vendeva cose impossibili.",
"C’era una bancarella di sogni lucidi.",
"Una vendeva bottiglie piene di pioggia estiva.",
"Un vecchio signore vendeva ricordi felici dimenticati sotto i letti.",
"Una bambina con capelli argentati vendeva piccoli pezzi di aurora boreale.",
"{{name}} camminò tra le bancarelle ascoltando il rumore morbido della notte.",
"Al centro del mercato c’era una fontana che invece dell’acqua aveva stelle liquide.",
"Il mercante della luna regalò a {{name}} una moneta dorata.",
"“Non serve per comprare,” spiegò. “Serve per ricordarti che il mondo è più grande di quanto sembri.”",
"Quando {{name}} tornò giù dalla scala, il cielo sembrava diverso.",
"Come se nascondesse ancora mille posti segreti."
]
},

{
title:"{{name}} e la nave tra le nuvole",
subtitle:"Una nave volante attraversa il cielo.",
icon:"☁️ ⛵ ✨",
art:"sky",
scene:"☁️ ⛵ ✨",
keywords:["nave","nuvole","cielo","viaggio"],
ritual:"⛵ Bussola del cielo",
activity:"Disegna una nave volante.",
paragraphs:[
"Sopra FABLEA esisteva una nave che navigava tra le nuvole.",
"Le sue vele erano fatte di vento e il suo legno profumava di pioggia.",
"{{name}} la vide passare lentamente sopra le montagne.",
"Dal ponte salutava un capitano con un grande cappello blu.",
"“Vuoi salire?” chiese.",
"La nave attraversava tempeste morbide e oceani di cielo.",
"Ogni nuvola aveva una forma diversa: draghi, castelli, balene e città sospese.",
"Il capitano mostrò a {{name}} una stanza piena di mappe del cielo.",
"“Le persone credono che le nuvole cambino sempre,” disse. “Ma alcune strade restano.”",
"Più la nave saliva, più il cielo diventava silenzioso.",
"A un certo punto comparve una gigantesca aurora luminosa.",
"Tutto il ponte si colorò di verde, viola e oro.",
"Prima di salutare, il capitano regalò a {{name}} una piccola bussola.",
"La bussola puntava sempre verso l’avventura."
]
},

{
title:"{{name}} e il giardino delle lucciole",
subtitle:"Un luogo dove le luci raccontano storie.",
icon:"✨ 🌿 🐞",
art:"forest",
scene:"✨ 🌿 🐞",
keywords:["lucciole","giardino","bosco","notte"],
ritual:"✨ Lucciola gentile",
activity:"Disegna un giardino pieno di lucciole.",
paragraphs:[
"Nel cuore del bosco esisteva un giardino che si illuminava solo di notte.",
"Non aveva lampade. Non aveva candele.",
"A illuminarlo erano migliaia di lucciole.",
"Ogni lucciola custodiva una storia.",
"Quando {{name}} entrò nel giardino, le luci si alzarono lentamente in aria.",
"Una lucciola blu raccontava storie di oceani lontani.",
"Una verde raccontava foreste dimenticate.",
"Una dorata raccontava di bambini che avevano trovato coraggio nei momenti difficili.",
"Il custode del giardino era un vecchio con una lanterna spenta.",
"“La mia lanterna si accende solo quando qualcuno ascolta davvero,” spiegò.",
"{{name}} rimase fermo ad ascoltare il rumore delle lucciole.",
"Poco dopo la lanterna del custode si illuminò da sola.",
"Il vecchio sorrise. “Vedi? Alcune luci si accendono solo nel silenzio.”",
"E il giardino continuò a brillare piano nella notte."
]
}

],

"8-10": [

{
title:"{{name}} e il ponte delle scelte",
subtitle:"Una storia su emozioni, fiducia e piccoli cambiamenti interiori.",
icon:"🌉 💛 🌙",
art:"bridge",
scene:"🌉 💛 🌙",
keywords:["ponte","scelte","fiducia","emozioni"],
ritual:"💛 Luce della fiducia",
activity:"Disegna tre luci: coraggio, gentilezza e fiducia.",
paragraphs:[
"Nel cuore di una città segreta, {{name}} trovò un ponte sospeso tra due colline.",
"Non era fatto di legno né di pietra. Era fatto di scelte.",
"Ogni tavola brillava quando qualcuno diceva qualcosa di vero a se stesso.",
"Sotto il ponte scorreva un fiume calmo. Nell’acqua non si vedevano pesci, ma pensieri.",
"Si vedeva una paura piccola. Poi una domanda. Poi un desiderio che non aveva ancora trovato le parole.",
"Dopo una giornata {{mood}}, quel fiume sembrava più vicino del solito.",
"All’inizio {{name}} pensò di dover attraversare in fretta.",
"Ma una voce leggera arrivò dal vento: “Il ponte non ama la fretta. Ama la verità.”",
"Sul ponte comparvero tre luci: coraggio, gentilezza e fiducia.",
"La luce del coraggio era forte. La luce della gentilezza era calda. La luce della fiducia era piccola, ma non tremava.",
"{{name}} capì che non doveva scegliere la luce più grande. Doveva scegliere quella più vera.",
"Quando fece il primo passo, il ponte vibrò piano.",
"Non perché fosse fragile, ma perché aveva riconosciuto una scelta sincera.",
"Dall’altra parte non c’era un premio. C’era una città più chiara, più calma, più vicina.",
"E {{name}} capì che crescere non significa non avere paura. Significa attraversare il ponte anche con la paura accanto."
]
},

{
title:"{{name}} e il teatro delle emozioni",
subtitle:"Le emozioni salgono sul palco una alla volta.",
icon:"🎭 ✨ 💛",
art:"bridge",
scene:"🎭 🌙 ✨",
keywords:["teatro","emozioni","rabbia","paura"],
ritual:"🎭 Maschera gentile",
activity:"Disegna il volto di un’emozione e dagli un nome.",
paragraphs:[
"Il teatro delle emozioni apriva solo quando qualcuno aveva troppe cose dentro.",
"{{name}} trovò il biglietto in tasca senza sapere come fosse arrivato lì.",
"Era un biglietto color crema, con una scritta sottile: “Questa sera parlano loro.”",
"Il teatro era nascosto dietro una porta rossa in fondo a una strada silenziosa.",
"Dentro, le poltrone erano vuote. Il palco era illuminato da una sola luce.",
"Per prima salì la Rabbia. Aveva scarpe rumorose e un mantello rosso.",
"Non urlò. Disse soltanto: “Sono stanca di essere fraintesa.”",
"Poi salì la Paura. Camminava piano e teneva una coperta tra le mani.",
"“Io non voglio comandare,” disse. “Voglio solo proteggere.”",
"Poi arrivò la Gioia. Era piccola, luminosa e un po’ timida.",
"“A volte mi nascondo,” disse. “Ma torno quando qualcuno mi lascia spazio.”",
"Il direttore del teatro guardò {{name}} e chiese: “Quale emozione ha bisogno di una sedia in prima fila?”",
"{{name}} non rispose subito. Guardò il palco, poi il cuore, poi di nuovo il palco.",
"Scelse con calma.",
"Quando il sipario si chiuse, il petto sembrò più spazioso.",
"Le emozioni non erano sparite. Ma ora parlavano una alla volta."
]
},

{
title:"{{name}} e la città degli specchi",
subtitle:"Una città riflette non l’aspetto, ma ciò che si porta dentro.",
icon:"🪞 🏙️ ✨",
art:"bridge",
scene:"🪞 🏙️ ✨",
keywords:["specchio","identità","città","crescita"],
ritual:"🪞 Specchio sincero",
activity:"Scrivi o disegna una qualità che vuoi ricordare.",
paragraphs:[
"La città degli specchi apparve a {{name}} dopo una curva che non c’era il giorno prima.",
"Le strade erano pulite, silenziose, illuminate da lampioni argentati.",
"Ogni palazzo aveva finestre lucide come acqua ferma.",
"Ma quegli specchi non riflettevano il viso.",
"Riflettevano ciò che una persona portava dentro.",
"In uno specchio {{name}} vide una paura nascosta dietro un sorriso.",
"In un altro vide una speranza piccola, ma ostinata.",
"In un altro ancora vide una versione di sé più coraggiosa, in piedi davanti a una porta difficile.",
"Una ragazza con un cappello rosso si avvicinò.",
"“Qui gli specchi non giudicano,” disse. “Mostrano.”",
"Camminarono fino alla piazza centrale, dove c’era uno specchio coperto da un telo blu.",
"{{name}} lo scoprì piano.",
"Dentro non vide una persona perfetta. Vide una luce piccola, resistente, vera.",
"“Quella è la parte che resta anche quando ti confondi,” disse la ragazza.",
"La città svanì al tramonto.",
"Ma lo specchio rimase dentro {{name}}, come una finestra accesa."
]
},

{
title:"{{name}} e il drago che non ruggiva",
subtitle:"Un drago trova una forza diversa dalla voce forte.",
icon:"🐉 💛 🌿",
art:"forest",
scene:"🐉 💛 🌿",
keywords:["drago","voce","forza","autostima"],
ritual:"🐉 Fiamma gentile",
activity:"Disegna un drago che usa un potere diverso dal ruggito.",
paragraphs:[
"Nel villaggio delle montagne tutti conoscevano i draghi per i loro ruggiti.",
"Si diceva che un vero drago dovesse far tremare le rocce.",
"Ma il drago che {{name}} incontrò non ruggiva mai.",
"Si chiamava Niro e disegnava nell’aria con il fumo leggero.",
"Con quel fumo creava ponti, alberi, piccoli animali e stelle sospese.",
"“Pensano che io sia debole,” disse Niro. “Solo perché la mia forza non fa rumore.”",
"{{name}} guardò i suoi disegni muoversi lenti nel cielo.",
"Erano bellissimi. Eppure Niro li cancellava subito, come se avesse paura di mostrarli troppo.",
"Quel giorno una frana bloccò il sentiero del villaggio.",
"Tutti aspettarono un ruggito potente per spostare le pietre.",
"Niro abbassò lo sguardo. Poi guardò {{name}}.",
"{{name}} disse piano: “Forse puoi fare a modo tuo.”",
"Allora Niro soffiò una lunga linea di fumo dorato.",
"Il fumo diventò un ponte leggero, ma solido.",
"Il villaggio attraversò in silenzio.",
"Da quel giorno, nessuno chiese più a Niro di ruggire.",
"E Niro capì che la forza vera non deve sempre fare rumore."
]
},

{
title:"{{name}} e la stanza della pioggia",
subtitle:"Una stanza ascolta le emozioni che non trovano parole.",
icon:"🌧️ 🪟 💙",
art:"ocean",
scene:"🌧️ 🪟 💙",
keywords:["pioggia","calma","emozioni","silenzio"],
ritual:"🌧️ Goccia calma",
activity:"Disegna una goccia e scrivi dentro cosa vorresti lasciar andare.",
paragraphs:[
"In fondo a un corridoio silenzioso, {{name}} trovò una porta azzurra.",
"Sopra la porta c’era scritto: “Stanza della pioggia”.",
"Dentro non pioveva forte.",
"Cadevano gocce lente, sospese nell’aria, una alla volta.",
"Ogni goccia conteneva un’emozione che qualcuno non era riuscito a dire.",
"Una voce gentile arrivò dalla finestra: “Non devi sistemare tutto. Puoi solo ascoltare.”",
"{{name}} toccò una goccia e sentì una tristezza piccola.",
"Ne toccò un’altra e sentì una rabbia stanca.",
"Ne toccò una terza e sentì una paura che voleva solo una coperta.",
"Le gocce non facevano male. Chiedevano solo un nome.",
"{{name}} restò lì per un po’, senza cercare risposte veloci.",
"Poi disse piano: “Oggi è stato difficile.”",
"La pioggia cambiò suono.",
"Non era più pesante. Sembrava musica.",
"La porta restò socchiusa.",
"Perché alcune stanze non servono per scappare. Servono per respirare."
]
},

{
title:"{{name}} e il custode delle domande",
subtitle:"Un custode protegge le domande che fanno crescere.",
icon:"❓ 📚 🕯️",
art:"castle",
scene:"❓ 📚 🕯️",
keywords:["domande","libro","crescita","curiosità"],
ritual:"❓ Domanda luminosa",
activity:"Scrivi una domanda che vuoi tenere aperta.",
paragraphs:[
"In una biblioteca senza pareti, {{name}} incontrò il custode delle domande.",
"Non custodiva risposte. Quelle cambiavano troppo spesso.",
"Custodiva domande importanti, scritte su fogli sospesi nell’aria.",
"Alcune domande brillavano molto.",
"Altre erano quasi invisibili.",
"“Una buona domanda non ti chiude,” disse il custode. “Ti apre.”",
"{{name}} lesse una domanda: “Che cosa mi aiuta quando non so cosa fare?”",
"Poi un’altra: “Quando sono davvero me stesso?”",
"Poi una terza: “Di cosa ho bisogno, anche se non lo dico?”",
"Ogni domanda accendeva una piccola candela.",
"Al centro della biblioteca c’era un foglio vuoto.",
"Il custode porse una penna a {{name}}.",
"“Non devi trovare una risposta oggi,” disse. “Scrivi solo una domanda che merita spazio.”",
"{{name}} scrisse lentamente.",
"Quando la domanda fu completa, il foglio diventò una lanterna.",
"E il custode sorrise, perché una nuova luce era entrata nella biblioteca."
]
},

{
title:"{{name}} e il ragazzo della luce blu",
subtitle:"Una luce diversa aiuta a vedere porte invisibili.",
icon:"💙 🛤️ 🌌",
art:"space",
scene:"💙 🛤️ 🌌",
keywords:["luce","blu","diversità","strada"],
ritual:"💙 Lanterna blu",
activity:"Disegna una porta che solo una luce speciale può mostrare.",
paragraphs:[
"In una città dove tutte le luci erano gialle, viveva un ragazzo con una lanterna blu.",
"Tutti gli dicevano che quella luce era strana.",
"Lui la teneva comunque accesa.",
"{{name}} lo incontrò vicino a un vicolo chiuso, davanti a un muro senza porte.",
"“Perché usi una luce diversa?” chiese {{name}}.",
"Il ragazzo sorrise. “Perché con questa vedo cose che gli altri non notano.”",
"Illuminò il muro con la lanterna blu.",
"All’improvviso comparve una porta sottile, nascosta tra i mattoni.",
"Dietro la porta c’era un sentiero pieno di disegni, parole cancellate e idee lasciate a metà.",
"“Questo è il posto delle possibilità non ascoltate,” spiegò il ragazzo.",
"{{name}} vide un aquilone mai costruito, una canzone mai cantata, una frase mai detta.",
"La lanterna blu non cambiava il mondo.",
"Lo mostrava in un modo diverso.",
"Prima di salutare, il ragazzo lasciò a {{name}} una piccola scintilla blu.",
"“Tienila,” disse. “Quando tutti guardano dalla stessa parte, tu puoi cercare una porta nascosta.”"
]
},

{
title:"{{name}} e il sentiero invisibile",
subtitle:"Un sentiero appare solo quando si procede con fiducia.",
icon:"🛤️ 🌫️ ✨",
art:"forest",
scene:"🛤️ 🌫️ ✨",
keywords:["sentiero","fiducia","nebbia","cammino"],
ritual:"🛤️ Pietra del passo",
activity:"Disegna il primo passo di un sentiero invisibile.",
paragraphs:[
"La nebbia copriva tutto, ma {{name}} sentiva che davanti c’era una strada.",
"Non si vedeva. Non ancora.",
"Solo un suono leggero arrivava da lontano, come foglie mosse da un vento gentile.",
"Una tartaruga grigia camminava lentamente nella stessa direzione.",
"“Come fai a sapere dove andare?” chiese {{name}}.",
"“Non lo so tutto insieme,” rispose la tartaruga. “So solo il prossimo passo.”",
"Appena la tartaruga mise una zampa avanti, una pietra comparve sotto di lei.",
"{{name}} provò a fare lo stesso.",
"Una nuova pietra apparve.",
"Poi un’altra. Poi un’altra ancora.",
"Il sentiero non era invisibile per fare paura.",
"Era invisibile per insegnare fiducia.",
"A metà strada, {{name}} volle guardare indietro.",
"Le pietre già percorse brillavano piano.",
"Non mostravan tutto il percorso. Mostravano solo che era possibile continuare.",
"Alla fine, {{name}} non vedeva ancora tutta la strada.",
"Ma non serviva più."
]
},

{
title:"{{name}} e il lago dei ricordi",
subtitle:"Un lago custodisce ricordi che possono diventare forza.",
icon:"🪷 🌊 🧠",
art:"ocean",
scene:"🪷 🌊 🧠",
keywords:["lago","ricordi","calma","memoria"],
ritual:"🪷 Foglia del ricordo",
activity:"Disegna un ricordo come se fosse una pianta.",
paragraphs:[
"Il lago dei ricordi era nascosto tra montagne basse e alberi immobili.",
"Non aveva onde. Non aveva barche.",
"Sembrava aspettare in silenzio.",
"{{name}} si avvicinò e vide immagini muoversi sotto l’acqua.",
"C’erano giorni belli, giorni strani, giorni in cui non tutto era andato come avrebbe voluto.",
"Una donna anziana sedeva sulla riva con un bastone di legno chiaro.",
"“I ricordi non sono pietre,” disse. “Sono semi.”",
"{{name}} guardò un ricordo difficile.",
"Sembrava pesante.",
"La donna lo toccò con il bastone e dall’acqua nacque una piccola pianta.",
"“Anche quello può insegnarti qualcosa,” spiegò.",
"{{name}} vide che la pianta non era scura.",
"Era verde, fragile, viva.",
"Prese una foglia e la mise in tasca.",
"Il lago rimase calmo.",
"Come se sapesse aspettare il prossimo ricordo."
]
},

{
title:"{{name}} e il libro che ascoltava",
subtitle:"Un libro risponde solo quando qualcuno è sincero.",
icon:"📖 👂 ✨",
art:"castle",
scene:"📖 👂 ✨",
keywords:["libro","ascolto","parole","sincerità"],
ritual:"📖 Pagina sincera",
activity:"Scrivi una frase vera che vuoi custodire.",
paragraphs:[
"Il libro che ascoltava era appoggiato su una sedia vuota.",
"Non aveva titolo.",
"Non aveva disegni in copertina.",
"Quando {{name}} lo aprì, le pagine erano bianche.",
"“Non scrivo per primo,” disse una voce sottile. “Prima ascolto.”",
"{{name}} rimase in silenzio.",
"Poi raccontò qualcosa di piccolo, qualcosa che non aveva detto ad alta voce.",
"Sulla pagina apparve una frase: “Grazie per avermi affidato questo.”",
"Il libro non dava consigli veloci.",
"Faceva spazio.",
"Ogni volta che {{name}} diceva qualcosa di vero, compariva una riga nuova.",
"Alcune righe erano luminose. Altre erano leggere come matita.",
"Alla fine, il libro scrisse: “Le parole sincere non risolvono tutto, ma aprono una finestra.”",
"Quando si chiuse, una pagina restò leggermente luminosa.",
"{{name}} capì che essere ascoltati è già un piccolo inizio."
]
}

],

"11-12": [

{
title:"{{name}} e l’atlante delle possibilità",
subtitle:"Un racconto su identità, scelte e futuro.",
icon:"🌌 🧭 📖",
art:"space",
scene:"🌌 🧭 ✨",
keywords:["atlante","futuro","direzione","identità"],
ritual:"🧭 Bussola interiore",
activity:"Scrivi una domanda che vuoi portare con te.",
paragraphs:[
"La sera in cui {{name}} trovò l’atlante, il cielo sembrava più grande del solito.",
"Sulla scrivania c’era un libro senza titolo, con una bussola disegnata in copertina.",
"La frase incisa diceva: “Non tutte le direzioni si vedono da fuori.”",
"Quando {{name}} aprì il libro, le pagine non mostrarono città o confini.",
"Mostrarono possibilità.",
"Una pagina era fatta di coraggio. Una di dubbi. Una di errori utili.",
"Un’altra sembrava piena di sogni ancora confusi.",
"Al centro dell’atlante apparve una domanda: “Che cosa ti fa sentire vivo quando nessuno ti guarda?”",
"{{name}} rimase in silenzio, non perché non avesse una risposta, ma perché quella domanda meritava spazio.",
"La bussola sulla copertina iniziò a muoversi lentamente.",
"Non indicò nord.",
"Indicò avanti.",
"{{name}} capì che crescere non significa sapere già tutto.",
"Significa imparare ad ascoltare quale strada continua a chiamarti."
]
},

{
title:"{{name}} e la città dopo il tramonto",
subtitle:"Una città notturna mostra ciò che resta acceso dentro.",
icon:"🌆 🌙 ✨",
art:"space",
scene:"🌆 🌙 ✨",
keywords:["città","notte","identità","tramonto"],
ritual:"🌙 Lampione interiore",
activity:"Disegna una città notturna con una finestra ancora accesa.",
paragraphs:[
"Dopo il tramonto, la città cambiava pelle.",
"Le vetrine si spegnevano, i rumori scendevano, le strade diventavano più grandi.",
"{{name}} camminava senza una meta precisa quando vide una strada che di giorno non esisteva.",
"In fondo alla strada c’era una piazza silenziosa.",
"Al centro della piazza, un lampione era acceso anche senza elettricità.",
"Una voce disse: “Questa luce mostra ciò che resta quando il rumore finisce.”",
"{{name}} guardò intorno e vide ombre di possibilità.",
"Cose iniziate. Cose desiderate. Cose mai dette.",
"Il lampione non giudicava.",
"Illuminava.",
"Sotto quella luce, {{name}} capì che crescere non è scegliere subito una forma definitiva.",
"È imparare quali luci vale la pena tenere accese.",
"La città tornò normale quando arrivò il mattino.",
"Ma dentro {{name}}, quel lampione continuò a brillare."
]
},

{
title:"{{name}} e il ragazzo senza bussola",
subtitle:"Perdersi diventa un modo diverso di iniziare.",
icon:"🧭 ❔ 🌫️",
art:"bridge",
scene:"🧭 ❔ 🌫️",
keywords:["bussola","strada","futuro","scelte"],
ritual:"❔ Domanda guida",
activity:"Scrivi una domanda che può diventare bussola.",
paragraphs:[
"Il ragazzo senza bussola viveva in una valle dove tutti portavano una direzione appesa al collo.",
"Nord, sud, est, ovest.",
"Tutti sembravano sapere dove andare.",
"{{name}} lo incontrò seduto su un muretto, con una bussola vuota in mano.",
"“Non indica niente,” disse il ragazzo. “Forse sono rotto io.”",
"{{name}} guardò la bussola.",
"Non sembrava rotta.",
"Sembrava in attesa.",
"Camminarono insieme tra strade che cambiavano nome e cartelli girati dal vento.",
"Alla fine arrivarono davanti a un campo aperto.",
"La bussola si accese, ma non indicò una direzione.",
"Indicò una domanda: “Che cosa vuoi conoscere meglio?”",
"Il ragazzo sorrise piano.",
"Forse non era senza bussola.",
"Forse aveva solo bisogno della domanda giusta."
]
},

{
title:"{{name}} e la biblioteca del cielo",
subtitle:"Ogni libro contiene una versione possibile di sé.",
icon:"📚 ☁️ 🌌",
art:"sky",
scene:"📚 ☁️ 🌌",
keywords:["biblioteca","cielo","sogni","possibilità"],
ritual:"📖 Pagina futura",
activity:"Scrivi il titolo di un libro che parla di chi potresti diventare.",
paragraphs:[
"La biblioteca del cielo fluttuava sopra le nuvole.",
"Nessuno la vedeva finché non aveva una domanda vera.",
"{{name}} arrivò su una scala fatta di vento.",
"All’ingresso c’era una ragazza con mani piene di polvere di stelle.",
"“Qui non conserviamo libri su ciò che è stato,” disse.",
"“Conserviamo libri su ciò che potresti diventare.”",
"{{name}} aprì un volume e vide una versione di sé coraggiosa.",
"Poi una più calma.",
"Poi una ancora confusa, ma viva.",
"“Quale devo scegliere?” chiese.",
"La ragazza sorrise.",
"“Nessuna adesso. Devi solo capire quali pagine ti chiamano.”",
"{{name}} copiò una frase su un foglio: “Non sono una sola possibilità.”",
"La biblioteca si allontanò tra le nuvole.",
"Ma il foglio restò."
]
},

{
title:"{{name}} e il ponte delle costellazioni",
subtitle:"Ogni scelta collega punti lontani.",
icon:"🌉 ✨ 🌌",
art:"space",
scene:"🌉 ✨ 🌌",
keywords:["stelle","ponte","costellazioni","scelte"],
ritual:"✨ Stella da collegare",
activity:"Disegna tre stelle e uniscile con una linea.",
paragraphs:[
"Nel cielo sopra la città, le stelle sembravano disordinate.",
"Poi {{name}} vide una linea sottile unirne due.",
"Poi tre.",
"Poi molte.",
"Si formò un ponte di costellazioni.",
"Una figura luminosa camminava dall’altra parte.",
"“Le scelte sono come stelle,” disse.",
"“Da sole sembrano sparse. Col tempo diventano disegno.”",
"{{name}} salì sul ponte e vide momenti della propria vita brillare sotto i piedi.",
"Alcuni erano belli.",
"Altri complicati.",
"Altri ancora non avevano senso.",
"Ma da lassù, tutti contribuivano a una forma.",
"La figura luminosa indicò una stella spenta.",
"“Questa è una scelta che non hai ancora fatto.”",
"{{name}} non la accese subito.",
"Ma capì che era lì, ad aspettare."
]
},

{
title:"{{name}} e la stanza delle versioni future",
subtitle:"Una stanza mostra futuri possibili senza obbligare a sceglierne uno.",
icon:"🚪 🪞 🔮",
art:"castle",
scene:"🚪 🪞 🔮",
keywords:["futuro","specchio","identità","scelta"],
ritual:"🪞 Riflesso futuro",
activity:"Disegna una versione futura di te senza renderla perfetta.",
paragraphs:[
"La stanza delle versioni future aveva molte porte e nessuna maniglia.",
"{{name}} entrò perché una porta si aprì da sola.",
"Dentro c’erano specchi, ma non riflettevano il presente.",
"In uno specchio, {{name}} parlava davanti a molte persone.",
"In un altro viaggiava.",
"In un altro costruiva qualcosa con pazienza.",
"In un altro ancora restava semplicemente in silenzio, ma sembrava sereno.",
"Una voce calma disse: “Non guardare per scegliere subito.”",
"“Guarda per riconoscere cosa si accende.”",
"{{name}} si avvicinò allo specchio più semplice.",
"Non mostrava successo, applausi o grandi scene.",
"Mostrava attenzione.",
"Mostrava presenza.",
"Mostrava una direzione ancora piccola, ma vera.",
"La stanza diventò più luminosa.",
"Forse il futuro non era una risposta.",
"Era una direzione da ascoltare."
]
},

{
title:"{{name}} e il mare delle domande",
subtitle:"Un mare calmo porta domande invece di risposte immediate.",
icon:"🌊 ❔ 🐚",
art:"ocean",
scene:"🌊 ❔ 🐚",
keywords:["mare","domande","futuro","calma"],
ritual:"🐚 Conchiglia domanda",
activity:"Scrivi una domanda e piegala come una barchetta.",
paragraphs:[
"Il mare delle domande era più silenzioso degli altri mari.",
"Le onde non portavano conchiglie normali.",
"Portavano frasi incomplete.",
"{{name}} ne raccolse una: “E se...”",
"Poi un’altra: “Perché mi importa...”",
"Poi una terza: “Dove mi sento...”",
"Sulla riva, un vecchio pescatore sistemava reti vuote.",
"“Pesco domande,” disse.",
"“Le risposte arrivano quando smetti di tirarle troppo forte.”",
"{{name}} lasciò una domanda nell’acqua.",
"Il mare non rispose.",
"La tenne al sicuro.",
"E per la prima volta, non avere subito una risposta sembrò meno spaventoso."
]
},

{
title:"{{name}} e il guardiano delle strade",
subtitle:"Non tutte le strade vanno percorse subito.",
icon:"🛤️ 🧥 🕯️",
art:"bridge",
scene:"🛤️ 🧥 🕯️",
keywords:["strade","scelte","guardiano","direzione"],
ritual:"🕯️ Candela del passo",
activity:"Disegna quattro strade e scegli solo la prima curva.",
paragraphs:[
"Il guardiano delle strade indossava un cappotto pieno di mappe piegate.",
"{{name}} lo trovò davanti a un incrocio con troppi cartelli.",
"Alcuni indicavano posti luminosi.",
"Altri sembravano difficili.",
"Altri ancora non avevano nome.",
"“Qual è quella giusta?” chiese {{name}}.",
"Il guardiano rise piano.",
"“Una domanda più utile è: quale strada vuoi conoscere adesso?”",
"Indicò una strada luminosa, una ombrosa, una rumorosa e una quasi invisibile.",
"{{name}} si accorse che stava guardando sempre quella quasi invisibile.",
"“Allora forse non è la più facile,” disse il guardiano.",
"“Ma è quella che ti parla.”",
"Consegnò a {{name}} una piccola candela.",
"“Non illumina tutta la strada. Solo il prossimo passo.”",
"A volte basta."
]
},

{
title:"{{name}} e le finestre del tempo",
subtitle:"Passato, presente e futuro si aprono come finestre.",
icon:"🪟 ⏳ 🌙",
art:"castle",
scene:"🪟 ⏳ 🌙",
keywords:["tempo","finestre","crescita","futuro"],
ritual:"🪟 Finestra accesa",
activity:"Disegna tre finestre: ieri, oggi, domani.",
paragraphs:[
"In una casa apparsa solo per una notte, {{name}} trovò tre finestre.",
"La prima guardava indietro.",
"Mostrava cose già vissute, alcune belle, altre difficili.",
"La seconda guardava il presente.",
"Mostrava {{name}} proprio lì, con domande ancora aperte.",
"La terza guardava avanti, ma il vetro era appannato.",
"Una voce disse: “Il futuro non si vede bene perché si costruisce mentre cammini.”",
"{{name}} pulì un piccolo angolo del vetro.",
"Non vide tutto.",
"Vide solo una luce, lontana ma reale.",
"Capì che non serviva conoscere ogni dettaglio.",
"Serviva scegliere cosa tenere acceso mentre il tempo passava."
]
},

{
title:"{{name}} e il quaderno delle direzioni",
subtitle:"Un quaderno raccoglie parole guida per orientarsi.",
icon:"📓 🧭 ✨",
art:"space",
scene:"📓 🧭 ✨",
keywords:["quaderno","direzione","parole","identità"],
ritual:"📓 Parola guida",
activity:"Scrivi una parola che vuoi portare con te questa settimana.",
paragraphs:[
"Il quaderno delle direzioni non aveva righe dritte.",
"Ogni pagina cambiava forma in base a chi la apriva.",
"{{name}} trovò la prima pagina vuota, tranne una frase.",
"“Scrivi una parola che vuoi portare con te.”",
"Pensò a molte parole.",
"Alcune sembravano troppo grandi.",
"Altre troppo facili.",
"Alla fine ne scelse una semplice, ma vera.",
"Quando la scrisse, la parola diventò una piccola bussola disegnata sul bordo della pagina.",
"Il quaderno non disse dove andare.",
"Disse soltanto: “Quando ti perdi, torna alla parola.”",
"{{name}} chiuse il quaderno.",
"E sentì che una direzione può iniziare anche così.",
"Da una parola sincera."
]
}

]
