(function(global){
  'use strict';

  global.FABLEA_CLASSICS_V1 = [
    {
      id:'classic-2-4-leone-topo',collection:'classic',age:'2-4',family:'emozioni',adaptableToWorld:false,worlds:['Animali','Foresta'],defaultWorld:'Animali',
      styles:['gentle','emotional'],moods:['Curiosità e voglia di scoprire','Momento tranquillo'],support:['Accendere l’immaginazione'],
      title:'Il leone e il topo',subtitle:'Anche l’aiuto più piccolo può diventare prezioso.',companion:'',cover:{icon:'🦁',art:'forest'},
      source:{author:'Esopo',originalTitle:'Il leone e il topo',origin:'Favola antica attribuita a Esopo',status:'public-domain',adaptation:'Rinarrato da FABLEA'},
      treasure:'un filo dorato annodato due volte',ritual:'Dite una cosa piccola che oggi ha aiutato qualcuno.',activity:'Costruite una piccola rete con fili di lana e liberate insieme un pupazzo.',
      pages:[
        {id:'lt1',scene:'Un sonno nel sole',text:'Nel bosco caldo un grande leone dormiva con la criniera appoggiata sull’erba. Un topolino correva tra le foglie e, senza volerlo, gli passò sopra una zampa. Il leone aprì gli occhi. Il topolino rimase fermo, piccolo come un seme.',detail:'{{name}} e {{companion}} osservavano da dietro un cespuglio. Nessuno osava muoversi.'},
        {id:'lt2',scene:'Una promessa minuscola',text:'Il topolino chiese di essere lasciato andare. Promise che un giorno avrebbe aiutato il leone. Il leone sorrise: non riusciva a immaginare come una creatura così piccola potesse aiutarlo. Però aprì la zampa e lo lasciò libero.',detail:'Il topolino corse via, ma non dimenticò la promessa.'},
        {id:'lt3',scene:'La rete',text:'Qualche giorno dopo il leone finì in una rete tesa tra due alberi. Più tirava, più i nodi diventavano stretti. Il suo ruggito attraversò il bosco e arrivò fino alla tana del topolino.',detail:'{{name}} sentì il suono rimbalzare tra i tronchi: non era un ruggito di rabbia, ma una richiesta di aiuto.'},
        {id:'lt4',scene:'Denti piccoli, lavoro grande',text:'Il topolino raggiunse la rete e cominciò a rosicchiare una corda. Poi un’altra. I suoi denti erano piccoli, ma sapevano lavorare con pazienza. Un nodo cedette, poi un secondo. Il leone riuscì finalmente a uscire.',detail:'{{companion}} contò i fili spezzati. Nessuno da solo sembrava importante; insieme avevano aperto un varco.'},
        {id:'lt5',scene:'Due amici diversi',text:'Il leone ringraziò il topolino. Questa volta non rise. Capì che essere grandi non significa poter fare tutto e che ogni creatura possiede capacità diverse. Da quel giorno camminarono spesso nello stesso bosco.',detail:'Quando il sentiero era alto, il leone proteggeva il topolino. Quando era stretto, il topolino trovava il passaggio.',optionalForShort:true},
        {id:'lt6',scene:'Il filo della promessa',text:'Prima di salutarsi, il topolino regalò a {{name}} un pezzetto della rete. {{name}} lo annodò due volte: un nodo per chi chiede aiuto e uno per chi decide di rispondere.',detail:'Il filo era leggero, ma ricordava una cosa forte: nessuno è troppo piccolo per essere utile.',optionalForShort:true,optionalForMedium:true}
      ]
    },
    {
      id:'classic-2-4-lepre-tartaruga',collection:'classic',age:'2-4',family:'avventura',adaptableToWorld:false,worlds:['Animali','Foresta'],defaultWorld:'Foresta',
      styles:['adventurous','gentle'],moods:['Tanta energia','Allegria'],support:['Stimolare curiosità'],
      title:'La lepre e la tartaruga',subtitle:'Una corsa dove conta continuare, non soltanto partire veloci.',companion:'',cover:{icon:'🐢',art:'forest'},
      source:{author:'Esopo',originalTitle:'La lepre e la tartaruga',origin:'Favola antica attribuita a Esopo',status:'public-domain',adaptation:'Rinarrato da FABLEA'},
      treasure:'una foglia con una piccola freccia',ritual:'Fate cinque passi lentissimi senza fermarvi.',activity:'Create un percorso sul pavimento e provatelo prima velocemente, poi con passi regolari.',
      pages:[
        {id:'tt1',scene:'La sfida',text:'Una lepre correva così veloce da sollevare le foglie. Una tartaruga camminava piano, con passi sempre uguali. La lepre la prese in giro. La tartaruga propose una corsa fino alla grande quercia.',detail:'Gli animali del bosco tracciarono una linea di partenza con sassolini chiari.'},
        {id:'tt2',scene:'Via!',text:'Al via, la lepre partì come il vento. La tartaruga mosse una zampa, poi l’altra. La lepre diventò presto un puntino lontano. La tartaruga continuò a guardare la quercia e a seguire il sentiero.',detail:'{{name}} e {{companion}} camminavano accanto a lei senza spingerla né trascinarla.'},
        {id:'tt3',scene:'Una pausa troppo lunga',text:'La lepre si voltò e non vide la tartaruga. Decise di riposarsi sotto un albero. Chiuse gli occhi soltanto per un momento, pensò. Ma il vento era tiepido e il momento diventò un sonno profondo.',detail:'Le foglie scesero lentamente sulla sua coda.'},
        {id:'tt4',scene:'Passo dopo passo',text:'La tartaruga arrivò vicino all’albero. Vide la lepre addormentata, ma non si fermò. Un passo, poi un altro. Attraversò una pozzanghera, superò una radice e continuò verso la quercia.',detail:'Non andava più veloce di prima. Semplicemente non aveva smesso.'},
        {id:'tt5',scene:'Il traguardo',text:'La lepre si svegliò e corse con tutta la sua forza. Quando raggiunse la quercia, la tartaruga aveva già appoggiato una zampa oltre la linea. Gli animali applaudirono la sua costanza.',detail:'La lepre si congratulò. Aveva scoperto che un grande vantaggio può sparire quando si smette di avere cura del percorso.',optionalForShort:true},
        {id:'tt6',scene:'La freccia sulla foglia',text:'La tartaruga regalò a {{name}} una foglia con una freccia disegnata. Non diceva “corri”. Diceva soltanto “continua”.',detail:'{{companion}} la mise al sicuro: sarebbe servita nei giorni in cui un passo piccolo sembrava non bastare.',optionalForShort:true,optionalForMedium:true}
      ]
    },
    {
      id:'classic-5-7-brutto-anatroccolo',collection:'classic',age:'5-7',family:'emozioni',adaptableToWorld:false,worlds:['Animali','Mare'],defaultWorld:'Animali',
      styles:['emotional','calm'],moods:['Una giornata difficile','Una piccola paura'],support:['Aiutare con le emozioni'],
      title:'Il brutto anatroccolo',subtitle:'Un viaggio per scoprire che non tutto deve assomigliare a ciò che lo circonda.',companion:'',cover:{icon:'🦢',art:'ocean'},
      source:{author:'Hans Christian Andersen',originalTitle:'Den grimme ælling',origin:'Fiaba pubblicata nel 1843',status:'public-domain',adaptation:'Rinarrato da FABLEA'},
      treasure:'una piuma bianca con una punta grigia',ritual:'Ognuno nomina una qualità che ha impiegato tempo a riconoscere.',activity:'Disegnate lo stesso animale in tre momenti diversi della sua crescita.',
      pages:[
        {id:'ba1',scene:'L’uovo diverso',text:'Nel nido di un’anatra si aprirono molte uova. Dall’ultima uscì un piccolo più grande, grigio e impacciato. Gli altri anatroccoli avevano piume gialle e movimenti simili. Lui sembrava arrivato da un’altra storia.',detail:'{{name}} e {{companion}} notarono che nuotava bene, anche se sulla terra inciampava spesso.'},
        {id:'ba2',scene:'Le parole che fanno male',text:'Nel cortile alcuni animali lo chiamavano brutto e ridevano del suo collo lungo. Il piccolo cercò di piegarsi, camminare più basso e occupare meno spazio. Ma ogni tentativo di nascondersi lo faceva sentire ancora più solo.',detail:'Non c’era nulla di sbagliato nel suo corpo. Era il modo in cui gli altri lo guardavano a ferirlo.'},
        {id:'ba3',scene:'La partenza',text:'Una mattina lasciò il cortile. Attraversò canneti, campi e uno stagno dove nessuno lo conosceva. Alcuni giorni furono liberi, altri difficili. Quando arrivò il freddo, dovette imparare a trovare riparo e ad aspettare.',detail:'{{companion}} spiegò a {{name}} che crescere non è una trasformazione improvvisa: spesso avviene mentre si resiste, si osserva e si continua.'},
        {id:'ba4',scene:'Gli uccelli nel cielo',text:'Prima dell’inverno vide grandi uccelli bianchi volare sopra lo stagno. Erano eleganti e forti. Il piccolo sentì una strana nostalgia, come se quelle ali gli ricordassero qualcosa che ancora non conosceva.',detail:'Non desiderava diventare qualcun altro. Desiderava soltanto capire perché quella vista gli sembrasse familiare.'},
        {id:'ba5',scene:'Il riflesso',text:'In primavera tornò vicino all’acqua. Si chinò e vide un lungo collo bianco, ali ampie e uno sguardo che riconosceva. Non era diventato prezioso in quel momento: lo era sempre stato. Ora aveva finalmente incontrato la propria forma adulta.',detail:'I cigni lo accolsero senza chiedergli di spiegare perché fosse diverso dagli anatroccoli.'},
        {id:'ba6',scene:'Una piuma per ricordare',text:'Il cigno lasciò a {{name}} una piuma bianca con una piccola punta grigia. La parte grigia non venne cancellata: raccontava il viaggio, le stagioni e il coraggio di continuare quando nessuno sapeva ancora chi sarebbe diventato.',detail:'{{name}} capì che crescere non significa rinnegare ciò che si è stati, ma comprenderlo meglio.',optionalForShort:true}
      ]
    },
    {
      id:'classic-5-7-musicanti-brema',collection:'classic',age:'5-7',family:'avventura',adaptableToWorld:false,worlds:['Animali','Foresta'],defaultWorld:'Animali',
      styles:['adventurous','playful'],moods:['Allegria','Tanta energia'],support:['Accendere l’immaginazione'],
      title:'I musicanti di Brema',subtitle:'Quattro animali scoprono che insieme possono inventare una strada nuova.',companion:'',cover:{icon:'🎺',art:'forest'},
      source:{author:'Fratelli Grimm',originalTitle:'Die Bremer Stadtmusikanten',origin:'Fiaba raccolta dai fratelli Grimm',status:'public-domain',adaptation:'Rinarrato da FABLEA'},
      treasure:'un piccolo campanello con quattro suoni',ritual:'Create un ritmo usando quattro suoni diversi.',activity:'Costruite una torre di pupazzi e inventate il verso musicale di ciascuno.',
      pages:[
        {id:'mb1',scene:'Una strada per Brema',text:'Un asino ormai anziano lasciò la fattoria e decise di andare a Brema per diventare musicista. Non sapeva se avesse una bella voce, ma sapeva di voler scegliere da solo il proprio futuro.',detail:'Sul sentiero incontrò {{name}} e {{companion}}, che decisero di accompagnarlo per un tratto.'},
        {id:'mb2',scene:'La squadra cresce',text:'Poco dopo incontrarono un cane stanco, poi un gatto che non aveva più una casa e infine un gallo destinato a una brutta fine. L’asino propose a tutti la stessa cosa: partire insieme e trasformare le loro voci in musica.',detail:'Nessuno di loro sembrava adatto a un’orchestra elegante. Proprio per questo potevano inventarne una nuova.'},
        {id:'mb3',scene:'La luce tra gli alberi',text:'Quando arrivò la sera, videro una casa illuminata. Dentro c’erano alcuni ladri che mangiavano e ridevano. Gli animali avevano fame, ma non potevano affrontarli uno alla volta. Decisero di usare altezza, sorpresa e soprattutto le loro quattro voci.',detail:'L’asino si mise davanti alla finestra, il cane salì sulla sua schiena, il gatto sul cane e il gallo in cima.'},
        {id:'mb4',scene:'Il concerto più rumoroso',text:'Al segnale di {{name}}, ragliarono, abbaiarono, miagolarono e cantarono tutti insieme. Poi attraversarono la finestra come una creatura enorme e sconosciuta. I ladri fuggirono nel bosco convinti che la casa fosse abitata da un mostro.',detail:'La loro musica non era precisa, ma aveva ritmo, coraggio e un effetto sorprendente.'},
        {id:'mb5',scene:'Una casa scelta',text:'Gli animali mangiarono, riposarono e sistemarono la casa. Al mattino capirono che non avevano più bisogno di raggiungere Brema. Avevano trovato un luogo in cui vivere e una compagnia che valorizzava ciò che ciascuno sapeva fare.',detail:'Continuarono a suonare, ma senza chiedere a nessuno il permesso di chiamarla musica.'},
        {id:'mb6',scene:'Quattro suoni',text:'Prima di ripartire, regalarono a {{name}} un campanello capace di produrre quattro note. Ogni nota era semplice; suonate insieme diventavano il ricordo di una casa conquistata con collaborazione e inventiva.',detail:'{{companion}} provò il ritmo del loro primo concerto e tutti risero.',optionalForShort:true}
      ]
    },
    {
      id:'classic-8-10-pinocchio',collection:'classic',age:'8-10',family:'avventura',adaptableToWorld:false,worlds:['Regni e castelli','Foresta'],defaultWorld:'Regni e castelli',
      styles:['adventurous','emotional'],moods:['Curiosità e voglia di scoprire','Una giornata difficile'],support:['Stimolare curiosità','Aiutare con le emozioni'],
      title:'Le avventure di Pinocchio',subtitle:'Un burattino impaziente impara che diventare libero significa assumersi le proprie scelte.',companion:'',cover:{icon:'🪵',art:'castle'},
      source:{author:'Carlo Collodi',originalTitle:'Le avventure di Pinocchio. Storia di un burattino',origin:'Romanzo pubblicato tra il 1881 e il 1883',status:'public-domain',adaptation:'Rinarrato da FABLEA'},
      treasure:'un bottone di legno levigato',ritual:'Raccontate una scelta che oggi potreste riparare con un’azione concreta.',activity:'Costruite un piccolo burattino di carta con snodi mobili e inventate tre decisioni possibili.',
      pages:[
        {id:'pi1',scene:'Il pezzo di legno che rideva',text:'Geppetto ricevette un pezzo di legno insolito: quando lo lavorava, sembrava ridere e protestare. Ne costruì un burattino e lo chiamò Pinocchio. Appena ebbe gambe abbastanza forti, Pinocchio corse fuori, curioso di tutto e poco disposto ad ascoltare.',detail:'{{name}} e {{companion}} lo videro attraversare il paese come se ogni strada dovesse diventare subito un’avventura.'},
        {id:'pi2',scene:'La scuola rimandata',text:'Geppetto vendette il proprio cappotto per comprare a Pinocchio un libro scolastico. Pinocchio partì per la scuola, ma lungo il cammino sentì musica e vendette il libro per entrare in un teatro di burattini. Non aveva progettato di ferire Geppetto: aveva semplicemente scelto il desiderio più vicino senza pensare al costo.',detail:'Quando i burattini lo riconobbero come uno di loro, la festa sembrò cancellare ogni conseguenza. Ma le conseguenze non erano scomparse: aspettavano fuori dal teatro.'},
        {id:'pi3',scene:'Promesse e bugie',text:'Una fata gli chiese che cosa fosse accaduto. Pinocchio inventò una spiegazione, poi un’altra. Il naso si allungò, rendendo visibile la distanza tra i fatti e le sue parole. La fata non gli chiese di essere perfetto: gli chiese di fermarsi, ricostruire la sequenza e dire dove aveva scelto diversamente da ciò che aveva promesso.',detail:'{{name}} capì che una bugia spesso nasce per fuggire da una conseguenza, ma finisce per aggiungerne una nuova.'},
        {id:'pi4',scene:'Il Paese dei Balocchi',text:'Più avanti Pinocchio seguì un amico verso un luogo dove nessuno studiava e ogni giorno sembrava festa. All’inizio fu meraviglioso. Poi i ragazzi iniziarono a trasformarsi in asini, usati da adulti che guadagnavano dalla loro ingenuità. Pinocchio scoprì che una promessa senza regole può nascondere il progetto di qualcun altro.',detail:'Non tutto ciò che elimina fatica offre libertà. A volte elimina anche strumenti, scelta e possibilità di tornare indietro.'},
        {id:'pi5',scene:'Dentro il grande pesce',text:'Fuggito dal pericolo, Pinocchio finì nel ventre di un enorme pesce e vi trovò Geppetto, stanco ma vivo. Per la prima volta non aspettò che qualcuno lo salvasse. Osservò il respiro dell’animale, preparò un piccolo fuoco fumoso e organizzò la fuga, sostenendo Geppetto durante il nuoto.',detail:'Il cambiamento non avvenne perché pronunciò una promessa migliore. Avvenne perché compì azioni affidabili quando erano difficili.'},
        {id:'pi6',scene:'Diventare reale',text:'Tornato a casa, Pinocchio lavorò, studiò e si prese cura di Geppetto. Non smise di essere curioso o vivace; imparò a collegare il desiderio del momento alle persone e agli impegni che ne avrebbero sopportato il peso. Solo allora la sua trasformazione divenne visibile.',detail:'Essere “vero” non significava assomigliare agli altri bambini. Significava diventare responsabile delle proprie scelte senza perdere immaginazione.'},
        {id:'pi7',scene:'Il bottone levigato',text:'Pinocchio regalò a {{name}} un bottone del suo vecchio corpo di legno. Era stato ruvido, ma il tempo e le mani lo avevano reso liscio. Ricordava che il carattere non compare già finito: prende forma attraverso errori riconosciuti, riparazioni e nuove decisioni.',detail:'{{companion}} lo cucì su una piccola tasca destinata alle promesse che richiedono azioni.',optionalForShort:true}
      ]
    },
    {
      id:'classic-8-10-alice-meraviglie',collection:'classic',age:'8-10',family:'scoperta',adaptableToWorld:false,worlds:['Magia','Misteri e scoperte'],defaultWorld:'Magia',
      styles:['mysterious','playful'],moods:['Curiosità e voglia di scoprire','Allegria'],support:['Stimolare curiosità'],
      title:'Alice nel Paese delle Meraviglie',subtitle:'Un viaggio tra regole assurde, parole elastiche e domande che cambiano misura.',companion:'',cover:{icon:'🐇',art:'castle'},
      source:{author:'Lewis Carroll',originalTitle:"Alice’s Adventures in Wonderland",origin:'Romanzo pubblicato nel 1865',status:'public-domain',adaptation:'Rinarrato da FABLEA'},
      treasure:'una chiave minuscola con un punto interrogativo',ritual:'Inventate una domanda assurda e cercate una risposta sorprendentemente logica.',activity:'Disegnate una porta piccolissima e decidete quale oggetto potrebbe attraversarla.',
      pages:[
        {id:'al1',scene:'Il coniglio in ritardo',text:'Alice vide un coniglio bianco controllare un orologio e lamentarsi del ritardo. La cosa più strana non era che parlasse, ma che sembrasse avere un appuntamento importante. Alice lo seguì e cadde in una tana profondissima, circondata da scaffali, mappe e oggetti impossibili da raggiungere.',detail:'{{name}} e {{companion}} scesero con lei, cercando di capire se stessero cadendo o se il corridoio fosse diventato verticale.'},
        {id:'al2',scene:'Porte e dimensioni',text:'In una sala piena di porte, Alice trovò una chiave che apriva soltanto l’ingresso più piccolo. Bevande e dolci cambiavano la sua altezza, ma ogni soluzione creava un problema nuovo: troppo grande per la porta, troppo piccola per la chiave. Dovette smettere di agire in fretta e ricordare l’ordine delle trasformazioni.',detail:'Il Paese delle Meraviglie sembrava caotico, ma spesso chiedeva attenzione alle conseguenze più di quanto facessero i luoghi normali.'},
        {id:'al3',scene:'Il sorriso senza gatto',text:'Un gatto appariva e scompariva lasciando nell’aria soltanto il sorriso. Quando Alice chiese quale strada prendere, lui rispose che dipendeva da dove volesse arrivare. Alice non aveva una destinazione precisa. Scoprì così che scegliere una direzione senza uno scopo può portare ovunque, ma non necessariamente dove serve.',detail:'{{companion}} annotò la domanda: “Che cosa vogliamo capire prima di decidere il sentiero?”'},
        {id:'al4',scene:'Il tè che non finisce',text:'A una tavola apparecchiata, il Cappellaio e la Lepre di Marzo cambiavano posto senza mai sparecchiare. Le parole venivano usate come trappole e ogni domanda diventava un’altra domanda. Alice provò a seguire la conversazione, poi capì che non tutte le regole meritano obbedienza soltanto perché qualcuno le pronuncia con sicurezza.',detail:'Lasciò il tavolo quando il gioco smise di essere curioso e diventò semplicemente scortese.'},
        {id:'al5',scene:'La partita della Regina',text:'Nel giardino della Regina, i giocatori usavano fenicotteri come mazze e ricci come palle. La Regina minacciava punizioni per ogni errore, ma quasi nessuno eseguiva davvero i suoi ordini. Il suo potere cresceva grazie alla paura e al fatto che tutti fingevano di crederle invincibile.',detail:'Alice iniziò a osservare la distanza tra ciò che la Regina dichiarava e ciò che accadeva davvero.'},
        {id:'al6',scene:'Il processo impossibile',text:'Durante un processo, la sentenza sembrava decisa prima delle prove. Testimoni confusi parlavano di cose irrilevanti e una regola veniva inventata proprio quando serviva all’accusa. Alice, ormai tornata alla propria altezza, disse che un procedimento non diventa giusto solo perché indossa una corona e usa parole solenni.',detail:'Il tribunale si trasformò in un vortice di carte. Alice non lo sconfisse con la forza, ma rifiutando di trattare l’assurdo come autorità.'},
        {id:'al7',scene:'La chiave interrogativa',text:'Al risveglio, Alice trovò vicino a sé una piccola chiave. Sulla testa aveva inciso un punto interrogativo. La regalò a {{name}}: non apriva tutte le porte, ma ricordava di chiedere chi avesse inventato una regola, a quale scopo e che cosa accadesse seguendola.',detail:'Nel mondo reale le cose erano più stabili, ma non sempre più sensate.',optionalForShort:true}
      ]
    },
    {
      id:'classic-11-12-mago-oz',collection:'classic',age:'11-12',family:'avventura',adaptableToWorld:false,worlds:['Magia','Regni e castelli'],defaultWorld:'Magia',
      styles:['adventurous','mysterious'],moods:['Curiosità e voglia di scoprire','Una piccola paura'],support:['Stimolare curiosità'],
      title:'Il meraviglioso mago di Oz',subtitle:'Quattro viaggiatori cercano ciò che credono di non possedere e imparano a riconoscerlo nelle proprie azioni.',companion:'',cover:{icon:'🌪️',art:'castle'},
      source:{author:'L. Frank Baum',originalTitle:'The Wonderful Wizard of Oz',origin:'Romanzo pubblicato nel 1900',status:'public-domain',adaptation:'Rinarrato da FABLEA'},
      treasure:'un frammento verde di vetro comune',ritual:'Ognuno completa la frase: “Pensavo mi mancasse…, ma l’ho usato quando…”.',activity:'Disegnate una mappa con quattro ostacoli e annotate quale capacità serve davvero per superarli.',
      pages:[
        {id:'oz1',scene:'La casa nel ciclone',text:'Dorothy viveva in una pianura dove il cielo sembrava occupare quasi tutto. Un ciclone sollevò la casa e la trasportò in una terra sconosciuta. Per tornare a casa, Dorothy ricevette un’indicazione semplice: seguire la strada di mattoni gialli fino alla Città di Smeraldo e chiedere aiuto al potente Mago di Oz.',detail:'{{name}} e {{companion}} si unirono al viaggio. La strada era visibile, ma nessuno sapeva quali condizioni il Mago avrebbe imposto.'},
        {id:'oz2',scene:'Tre desideri',text:'Lungo il cammino incontrarono uno Spaventapasseri convinto di non avere cervello, un Boscaiolo di Latta convinto di non avere cuore e un Leone convinto di non avere coraggio. Tutti decisero di raggiungere il Mago. Eppure, già durante il viaggio, lo Spaventapasseri elaborava soluzioni, il Boscaiolo mostrava compassione e il Leone affrontava pericoli nonostante la paura.',detail:'La mancanza che ciascuno dichiarava non coincideva con il comportamento osservabile. Era diventata una storia ripetuta così spesso da sembrare un fatto.'},
        {id:'oz3',scene:'La città attraverso il verde',text:'Alle porte della Città di Smeraldo, ogni visitatore dovette indossare occhiali con lenti verdi. Tutto appariva brillante e prezioso. {{name}} si chiese quanto della meraviglia appartenesse davvero alla città e quanto dipendesse dal filtro obbligatorio. Nessuno poteva confrontare la propria impressione con una visione non mediata.',detail:'Il potere del Mago cominciava prima ancora dell’incontro: controllava il modo in cui le persone vedevano ciò che lo circondava.'},
        {id:'oz4',scene:'Il prezzo della promessa',text:'Il Mago apparve a ciascuno in una forma diversa e promise di concedere i loro desideri soltanto dopo la sconfitta di una strega pericolosa. Il gruppo accettò, pur comprendendo che la richiesta trasferiva su di loro un rischio che il governante non aveva affrontato. Nel viaggio verso ovest, le qualità considerate mancanti diventarono indispensabili.',detail:'Lo Spaventapasseri pianificò, il Boscaiolo protesse, il Leone agì mentre tremava e Dorothy mantenne unito il gruppo.'},
        {id:'oz5',scene:'L’uomo dietro il sipario',text:'Quando tornarono vittoriosi, scoprirono che il grande Mago era un uomo comune che usava macchine, luci e una voce amplificata. Non possedeva poteri straordinari. Aveva costruito un’immagine capace di convincere gli abitanti e, col tempo, anche se stesso. Il gruppo si sentì ingannato, ma la scoperta rese finalmente possibile una conversazione reale.',detail:'Il Mago non poteva creare cervello, cuore o coraggio. Poteva soltanto offrire simboli che aiutassero i viaggiatori a riconoscere prove già presenti nelle loro azioni.'},
        {id:'oz6',scene:'Doni e riconoscimenti',text:'Lo Spaventapasseri ricevette un attestato, il Boscaiolo un piccolo cuore simbolico e il Leone una medaglia. I doni non produssero le capacità: diedero un nome pubblico a ciò che il viaggio aveva dimostrato. Dorothy, invece, scoprì che il mezzo per tornare a casa era stato con lei per molto tempo, ma richiedeva conoscenza e una scelta consapevole.',detail:'{{companion}} osservò che possedere una risorsa e sapere di poterla usare sono due condizioni diverse.'},
        {id:'oz7',scene:'Il vetro senza filtro',text:'Prima del ritorno, Dorothy tolse gli occhiali verdi e raccolse un frammento di vetro trasparente. Lo consegnò a {{name}} come promemoria: autorità, reputazione e scenografie possono influenzare la percezione, ma le capacità si verificano nelle azioni e le affermazioni nelle prove.',detail:'Il frammento non rendeva il mondo meno meraviglioso. Permetteva di distinguerne meglio i colori.',optionalForShort:true}
      ]
    },
    {
      id:'classic-11-12-principe-felice',collection:'classic',age:'11-12',family:'emozioni',adaptableToWorld:false,worlds:['Regni e castelli','Misteri e scoperte'],defaultWorld:'Regni e castelli',
      styles:['emotional','calm'],moods:['Una giornata difficile','Momento tranquillo'],support:['Aiutare con le emozioni'],
      title:'Il principe felice',subtitle:'Una statua e una rondine osservano la città e trasformano la compassione in scelte concrete.',companion:'',cover:{icon:'🐦',art:'castle'},
      source:{author:'Oscar Wilde',originalTitle:'The Happy Prince',origin:'Racconto pubblicato nel 1888',status:'public-domain',adaptation:'Rinarrato da FABLEA'},
      treasure:'una piccola piuma accanto a una foglia d’oro opaco',ritual:'Scegliete un bisogno vicino e immaginate un aiuto concreto, rispettoso e possibile.',activity:'Disegnate una città vista dall’alto e segnate ciò che una statua potrebbe vedere ma un passante distratto no.',
      pages:[
        {id:'pf1',scene:'La statua sopra la città',text:'Al centro della città si alzava la statua del Principe Felice, ricoperta d’oro, con zaffiri negli occhi e una gemma rossa sull’elsa della spada. Quando era vivo, il principe aveva abitato dietro mura che nascondevano sofferenza e povertà. Dall’alto della statua, invece, vedeva strade, case e persone che la celebrazione ufficiale della città ignorava.',detail:'{{name}} e {{companion}} passarono ai piedi del monumento mentre una rondine, in viaggio verso sud, cercava riparo tra i suoi piedi.'},
        {id:'pf2',scene:'La prima richiesta',text:'Una goccia cadde sulla rondine. Non era pioggia, ma una lacrima della statua. Il Principe le mostrò una casa dove una madre lavorava fino a tardi accanto a un bambino malato. Le chiese di portare loro la gemma rossa della spada. La rondine esitò: il viaggio era urgente e la notte fredda. Poi accettò di rimandare la partenza.',detail:'La compassione divenne azione solo quando qualcuno decise di sostenere un costo: tempo, fatica e rinuncia a una parte dell’ornamento.'},
        {id:'pf3',scene:'Gli occhi di zaffiro',text:'Il giorno seguente il Principe vide un giovane scrittore senza legna e una bambina che rischiava una punizione perché aveva perso ciò che doveva vendere. Chiese alla rondine di portare loro i due zaffiri dei suoi occhi. La rondine protestò: senza occhi la statua non avrebbe più visto. Il Principe rispose che ormai aveva bisogno della rondine per conoscere la città.',detail:'La relazione cambiò: non più un benefattore che osserva dall’alto e un messaggero obbediente, ma due persone che condividevano informazioni, decisioni e responsabilità.'},
        {id:'pf4',scene:'L’oro distribuito',text:'Ora cieco, il Principe chiese alla rondine di sorvolare quartieri e cortili. Ascoltando i suoi racconti, fece staccare una dopo l’altra le foglie d’oro che ricoprivano la statua e le distribuì a chi ne aveva bisogno. Il monumento perdeva valore agli occhi dei notabili, ma acquistava significato nelle vite raggiunte.',detail:'{{name}} notò un limite importante: nessun gesto individuale poteva correggere da solo le cause della povertà. Però poteva rendere visibili bisogni nascosti e creare tempo perché altre soluzioni diventassero possibili.'},
        {id:'pf5',scene:'L’inverno e la scelta della rondine',text:'L’inverno arrivò. La rondine avrebbe dovuto partire, ma scelse di restare accanto al Principe. Non perché il sacrificio fosse sempre giusto, ma perché quella relazione era diventata per lei una responsabilità consapevole. Continuò a raccontare ciò che vedeva finché il freddo consumò le sue forze.',detail:'Le sue ultime azioni non furono ordinate dalla statua. Furono scelte, e proprio per questo avevano un peso morale diverso.'},
        {id:'pf6',scene:'Ciò che la città giudicò inutile',text:'Quando la rondine morì, il cuore di piombo del Principe si spezzò. I governanti decisero che la statua, ormai opaca e senza gemme, era brutta e inutile. La fecero fondere, ma il cuore non si sciolse e venne gettato insieme alla rondine. La città valutava l’opera con gli stessi criteri che il Principe aveva messo in discussione: splendore, prestigio e convenienza visibile.',detail:'Ciò che aveva perso valore economico conservava la storia delle scelte più importanti.'},
        {id:'pf7',scene:'Due cose preziose',text:'{{name}} raccolse una piuma e una piccola foglia d’oro ormai opaca. Non servivano a decorare un monumento. Servivano a ricordare che vedere un bisogno non basta, aiutare richiede ascolto e che la generosità più efficace non tratta le persone come comparse nella bontà di qualcun altro.',detail:'{{companion}} aggiunse una domanda da portare a casa: “Quale parte della città non stiamo guardando abbastanza?”',optionalForShort:true}
      ]
    }
  ];
})(window);
