window.FABLEA_STORIES_V2_5_7 = [
  {
    id:'v2-5-7-avventura-tre-impronte', age:'5-7', family:'avventura', adaptableToWorld:true, worlds:['*'],
    styles:['adventurous','mysterious'], moods:['Curiosità e voglia di scoprire','Tanta energia','Allegria'],
    support:['Accendere l’immaginazione','Stimolare curiosità'],
    title:'{{name}} e il sentiero delle tre impronte',
    subtitle:'Tre tracce diverse conducono a una scelta importante nel cuore di {{world}}.',
    companion:'', cover:{icon:'🐾',art:'forest'},
    treasure:'il medaglione delle tre impronte, inciso in {{material}}',
    ritual:'Disegnate tre impronte e dite: una cosa che so fare, una che sto imparando, una che vorrei provare.',
    activity:'Create una pista di impronte in casa e nascondete alla fine un piccolo messaggio di incoraggiamento.',
    pages:[
      {id:'a1',scene:'La traccia impossibile',text:'All’alba, davanti a {{threshold}}, {{name}} trovò tre impronte. La prima era grande e profonda. La seconda era leggera, quasi elegante. La terza sembrava incompleta: appariva, spariva e ricompariva più avanti. {{companion}} osservò le tracce e disse: «Nessun abitante di {{world}} cammina in tre modi così diversi».',detail:'L’aria profumava di {{scent}}. Da lontano arrivavano {{sound}}, ma vicino alle impronte tutto sembrava trattenere il fiato.'},
      {id:'a2',scene:'Il messaggio sotto la pietra',text:'Sotto una pietra piatta c’era un biglietto: “Segui tutte e tre le tracce prima che il sole tocchi {{landmark}}. Solo allora troverai ciò che è stato perduto”. Non diceva chi avesse scritto il messaggio né che cosa fosse scomparso. {{name}} decise di partire, portando una corda, una borraccia e una matita.',detail:'{{companion}} aggiunse una merenda e una lente. «Le grandi avventure», spiegò, «hanno bisogno anche di biscotti e dettagli». '},
      {id:'a3',scene:'L’impronta pesante',text:'La traccia grande attraversava un terreno morbido e portava a un passaggio bloccato. Per avanzare bisognava spostare tre massi. {{name}} provò a spingerli tutti insieme, senza riuscirci. Poi li osservò, trovò il più piccolo e iniziò da quello. Il sentiero si aprì un poco alla volta.',detail:'Dietro l’ultimo masso c’era una piuma rossa e una frase: “La forza non è fare tutto in un colpo. È capire da dove cominciare”.',optionalForShort:true},
      {id:'a4',scene:'L’impronta leggera',text:'La seconda traccia saliva lungo una passerella sottile. Sotto, il paesaggio di {{place}} sembrava lontanissimo. {{name}} non aveva voglia di guardare in basso. {{companion}} propose di scegliere un punto davanti e fare un passo per volta. A metà strada, il vento portò una risata: qualcuno li stava aspettando.',detail:'Ogni asse della passerella produceva una nota diversa. Quando {{name}} trovò il proprio ritmo, la paura smise di comandare i piedi.'},
      {id:'a5',scene:'La traccia che spariva',text:'La terza impronta terminava davanti a un prato senza segni. {{name}} cercò a destra e a sinistra, ma niente. Poi notò che le impronte comparivano soltanto quando una nuvola copriva il sole. Non serviva correre: serviva aspettare l’ombra e osservare. Così apparve una porta bassa nascosta nell’erba.',detail:'Sulla porta era incisa un’altra frase: “Chi sa aspettare vede strade che la fretta nasconde”.',optionalForShort:true},
      {id:'a6',scene:'La creatura dalle tre andature',text:'Dietro la porta viveva una giovane creatura che aveva una zampa forte, una leggera e una ancora incerta. Aveva lasciato le impronte durante una fuga e ora si vergognava del proprio modo di camminare. «Tutti si accorgeranno che sono diversa», disse. {{name}} mostrò le tre prove superate: forza, equilibrio e attenzione.',detail:'«Le tue impronte non sono sbagliate», aggiunse {{companion}}. «Raccontano tre capacità. È per questo che ci hanno portati fin qui». '},
      {id:'a7',scene:'Il rumore oltre il crinale',text:'Un boato arrivò dalla direzione di {{landmark}}. Una frana stava chiudendo il passaggio verso casa. La creatura conosceva tre sentieri, ma ognuno richiedeva una delle sue andature. Prima spinse un tronco con la zampa forte, poi attraversò rocce sottili con quella leggera, infine trovò una fessura invisibile seguendo la zampa incerta.',detail:'Quella che sembrava una debolezza era il passo più sensibile: percepiva le vibrazioni della terra prima degli altri.'},
      {id:'a8',scene:'Una squadra di passi diversi',text:'Gli abitanti di {{world}} arrivarono per aiutare. Alcuni erano veloci, altri robusti, altri bravissimi a orientarsi. Nessuno poteva fare tutto. {{name}} organizzò la squadra: chi spostava, chi ascoltava, chi indicava il percorso. Insieme liberarono la strada prima che il sole raggiungesse {{landmark}}.',detail:'Dall’alto, le loro impronte formavano un disegno bellissimo: non una fila perfetta, ma una mappa di collaborazione.',optionalForShort:true,optionalForMedium:true},
      {id:'a9',scene:'Il medaglione',text:'La creatura regalò a {{name}} un medaglione con tre impronte. «Quella che conosci, quella che stai allenando e quella che ancora non capisci», spiegò. Tornando a casa, {{name}} guardò i propri passi: alcuni sicuri, altri leggeri, altri esitanti. Tutti, però, conducevano avanti.',detail:'Da quel giorno, quando qualcosa sembrava difficile, il medaglione ricordava che esiste più di un modo per attraversare una strada.'}
    ]
  },
  {
    id:'v2-5-7-calma-faro-respiri', age:'5-7', family:'calma-sera', adaptableToWorld:true, worlds:['*'],
    styles:['calm'], moods:['Momento tranquillo','Stanchezza'], support:['Calmare la sera','Favorire piccoli rituali'],
    title:'{{name}} e il faro che contava i respiri',
    subtitle:'Una storia lenta per accompagnare {{world}} verso la notte.',
    companion:'', cover:{icon:'🕯️',art:'ocean'},
    treasure:'la lente quieta di {{material}}',
    ritual:'Accendete una luce piccola e fate cinque respiri: la luce sale quando inspirate e scende quando espirate.',
    activity:'Costruite un faro con rotoli di carta e scegliete a chi mandare una luce gentile.',
    pages:[
      {id:'c1',scene:'Una luce troppo veloce',text:'La sera era arrivata a {{place}}, ma il grande faro vicino a {{landmark}} continuava a girare troppo in fretta. La sua luce correva sulle pareti, svegliava gli abitanti e faceva sembrare ogni ombra un allarme. «Da tre notti non riesce a fermarsi», spiegò {{companion}}.',detail:'Perfino {{sky}} sembrava agitato, come se le stelle dovessero inseguire quel fascio luminoso.'},
      {id:'c2',scene:'Il guardiano stanco',text:'Dentro il faro, il guardiano aveva gli occhi rossi per la stanchezza. Ogni volta che provava a rallentare la ruota, una campana suonava: “E se qualcuno ha bisogno? E se non vedo un pericolo? E se mi fermo proprio nel momento sbagliato?”. {{name}} riconobbe quella voce: era la preoccupazione che continua a fare domande.',detail:'Sul tavolo c’erano tazze fredde, mappe aperte e una coperta mai usata. Il guardiano non si concedeva riposo da molto tempo.'},
      {id:'c3',scene:'La stanza dei rumori',text:'Per capire il problema, {{name}} salì nella stanza della lente. Lì dentro ogni suono diventava enorme: {{sound}}, il tic dell’orologio, il respiro del guardiano. {{name}} chiuse una finestra, sistemò una catena e mise un panno sotto l’orologio. Restò soltanto il rumore dell’aria che entrava e usciva.',detail:'Quando i rumori inutili diminuirono, quelli importanti divennero più chiari.',optionalForShort:true},
      {id:'c4',scene:'Una luce per ogni respiro',text:'{{name}} propose un esperimento. «La luce non deve controllare tutto in ogni momento. Può seguire un respiro». Inspirarono mentre il fascio saliva verso {{sky}}. Espirarono mentre scendeva verso il sentiero. La ruota fece un giro più lento. Poi un altro. Nessuna emergenza comparve.',detail:'Il guardiano sembrava incredulo. Per anni aveva pensato che rallentare significasse trascurare; ora vedeva che poteva significare osservare meglio.'},
      {id:'c5',scene:'Il segnale lontano',text:'Dalla parte opposta di {{place}} apparve una luce piccola: tre lampi, una pausa, altri tre lampi. Il guardiano si agitò. {{name}} guardò la mappa e capì che non era un pericolo, ma il saluto serale di una casa lontana. Risposero con lo stesso ritmo, senza accelerare.',detail:'La casa lontana spense la luce. Il messaggio era arrivato. Non tutto ciò che chiama richiede di correre.',optionalForShort:true},
      {id:'c6',scene:'La stanza del riposo',text:'Al piano più basso c’era una stanza dimenticata con una poltrona, una coperta e una finestra rivolta verso {{landmark}}. {{name}} convinse il guardiano a sedersi per un solo giro della luce. {{companion}} avrebbe controllato la ruota. Il guardiano si appoggiò e scoprì che il faro continuava a funzionare anche senza il suo sguardo costante.',detail:'Il primo minuto sembrò lunghissimo. Il secondo, più morbido. Al terzo, il guardiano fece finalmente uno sbadiglio.'},
      {id:'c7',scene:'La notte trova il ritmo',text:'Quando la luce iniziò a girare al ritmo dei respiri, gli abitanti di {{world}} chiusero finestre e porte. Le ombre smisero di correre. Il cielo diventò più profondo e il silenzio non sembrò vuoto, ma protetto. {{name}} ascoltò il proprio corpo diventare pesante e tranquillo.',detail:'Ogni passaggio del faro diceva senza parole: “Ora puoi lasciare andare. Tornerò di nuovo, con calma”.'},
      {id:'c8',scene:'Il turno della luna',text:'A mezzanotte, la luna si posizionò sopra {{landmark}} e prese il turno del faro. Il guardiano spense la lampada principale, lasciando una piccola luce di sicurezza. Per la prima volta, salì sul tetto non per controllare, ma per guardare il panorama insieme a {{name}}.',detail:'Videro che il mondo di notte non smette di esistere: cambia ritmo, affida compiti al buio e conserva energie per il mattino.',optionalForShort:true,optionalForMedium:true},
      {id:'c9',scene:'La lente quieta',text:'Prima del ritorno, il guardiano regalò a {{name}} una lente trasparente. Guardandoci attraverso, ogni luce sembrava respirare. «Usala quando i pensieri girano troppo in fretta», disse. Quella sera, a casa, {{name}} immaginò il faro: luce su, luce giù. Dopo pochi giri, il sonno arrivò.',detail:'La lente non fermava i pensieri. Ricordava loro che potevano passare uno alla volta.'}
    ]
  },
  {
    id:'v2-5-7-emozioni-nodo-parole', age:'5-7', family:'emozioni', adaptableToWorld:true, worlds:['*'],
    styles:['emotional'], moods:['Una giornata difficile','Un po’ di rabbia','Una piccola paura'], support:['Aiutare con le emozioni'],
    title:'{{name}} e il nodo delle parole non dette',
    subtitle:'Una storia per trovare parole quando dentro sembra tutto aggrovigliato.',
    companion:'', cover:{icon:'🪢',art:'castle'},
    treasure:'il filo sincero di {{material}}',
    ritual:'Ognuno completa tre frasi: “Mi è piaciuto…”, “Mi ha fatto stare male…”, “Avrei bisogno di…”.',
    activity:'Create un braccialetto con tre colori: sentimento, motivo e bisogno.',
    pages:[
      {id:'e1',scene:'Il nodo sulla strada',text:'Davanti a {{threshold}} comparve un nodo enorme, fatto di fili rossi, blu, gialli e grigi. Bloccava il passaggio verso {{place}}. Ogni volta che qualcuno provava a tirare un filo, il nodo diventava più stretto. «È nato dalle parole che nessuno ha detto», spiegò {{companion}}.',detail:'Dal nodo uscivano mezze frasi: “Non volevo…”, “Pensavo che…”, “Mi sono sentito…”. Poi tutto tornava a stringersi.'},
      {id:'e2',scene:'La parola arrabbiata',text:'{{name}} toccò un filo rosso. Subito sentì una voce gridare: «Lasciami stare!». Ma sotto quella frase ce n’era un’altra, più bassa: «Mi hai escluso e mi sono sentito solo». Il filo smise di bruciare appena la seconda frase fu ascoltata.',detail:'{{name}} capì che la rabbia spesso arriva per prima, come una guardia. Dietro, però, protegge qualcosa di più delicato.'},
      {id:'e3',scene:'La parola impaurita',text:'Il filo grigio tremava. Diceva: «Non mi importa», ma quando {{name}} lo tenne senza tirare, sussurrò: «Avevo paura di sbagliare davanti a tutti». {{companion}} non cercò di convincerlo che non doveva avere paura. Disse soltanto: «Capisco perché ti sei nascosto».',detail:'Il filo diventò più morbido. Essere compresi gli permetteva finalmente di cambiare forma.',optionalForShort:true},
      {id:'e4',scene:'La parola triste',text:'Il filo blu era bagnato e pesante. Ripeteva: «Va tutto bene». {{name}} lo ascoltò a lungo, finché uscì la frase vera: «Mi mancava qualcuno e non sapevo come dirlo». Una goccia cadde a terra. Il nodo si allentò di un giro.',detail:'Dire che qualcosa fa male non fece aumentare il dolore. Gli diede un posto in cui stare.'},
      {id:'e5',scene:'Il filo di {{name}}',text:'Al centro del nodo c’era un filo che portava il nome di {{name}}. Per scioglierlo serviva una frase sincera. Non doveva essere perfetta né coraggiosa. Bastava che fosse vera. {{name}} pensò a una situazione recente e disse ciò che aveva sentito, senza accusare nessuno.',detail:'La frase iniziava con “Io mi sono sentito…” e terminava con “Avrei bisogno di…”. Il filo rispose con una luce tenue.',optionalForShort:true},
      {id:'e6',scene:'La scelta di non tirare',text:'Restavano due fili opposti. Se {{name}} ne avesse tirato uno, l’altro si sarebbe spezzato. Allora scelse di avvicinarli e fare spazio a entrambe le frasi: “Sono arrabbiato” e “Tengo ancora a te”. Il nodo si aprì perché non era più obbligato a scegliere un solo sentimento.',detail:'A volte due emozioni contrarie possono essere vere nello stesso momento. Riconoscerle entrambe evita che si facciano guerra.'},
      {id:'e7',scene:'Il passaggio si apre',text:'I fili caddero a terra e diventarono un tappeto colorato. Gli abitanti di {{world}} attraversarono il passaggio, raccogliendo le proprie frasi. Alcuni chiesero scusa. Altri spiegarono. Qualcuno disse soltanto: «Non sono pronto, ma vorrei riparlarne». Anche quella era una frase utile.',detail:'{{name}} vide che comunicare non significa risolvere tutto subito. Significa permettere all’altro di sapere dove siamo.'},
      {id:'e8',scene:'Il laboratorio delle frasi',text:'Vicino a {{landmark}} aprirono un piccolo laboratorio. C’erano cartoncini con inizi diversi: “Quando è successo…”, “Ho provato…”, “Mi servirebbe…”. {{name}} aiutò una creatura timida a scegliere le parole per parlare con un amico.',detail:'Ogni frase completata diventava un filo diritto, pronto a unire invece che stringere.',optionalForShort:true,optionalForMedium:true},
      {id:'e9',scene:'Il filo sincero',text:'{{companion}} consegnò a {{name}} un filo di {{material}}. «Non obbliga nessuno a parlare», spiegò. «Ricorda soltanto che le parole vere possono essere dette un pezzetto alla volta». A casa, il filo rimase vicino al letto, pronto per le giornate in cui dentro si forma un nodo.',detail:'E quando le parole non arrivavano, {{name}} poteva iniziare da una sola: rabbia, paura, tristezza, bisogno. Una parola era già un’estremità da cui cominciare.'}
    ]
  },
  {
    id:'v2-5-7-scoperta-mappa-domande', age:'5-7', family:'scoperta', adaptableToWorld:true, worlds:['*'],
    styles:['mysterious','adventurous'], moods:['Curiosità e voglia di scoprire','Momento tranquillo'], support:['Stimolare curiosità','Accendere l’immaginazione'],
    title:'{{name}} e la mappa che cambiava con le domande',
    subtitle:'Ogni buona domanda fa comparire una strada nuova in {{world}}.',
    companion:'', cover:{icon:'🗺️',art:'space'},
    treasure:'la matita delle domande, con la punta di {{material}}',
    ritual:'Scegliete una cosa normale e fate cinque domande iniziando con “Come?”, “Perché?” oppure “Che cosa succederebbe se?”.',
    activity:'Disegnate una mappa immaginaria che cambia ogni volta che aggiungete una domanda.',
    pages:[
      {id:'s1',scene:'Una mappa quasi vuota',text:'Nella biblioteca vicino a {{threshold}}, {{name}} trovò una mappa con un solo punto: “Tu sei qui”. Non mostrava {{landmark}}, strade o case. Sul bordo c’era scritto: “Questa mappa non risponde a chi vuole soltanto arrivare. Risponde a chi sa domandare”.',detail:'La carta sembrava fatta di {{material}} sottile. Cambiava riflesso ogni volta che {{name}} la inclinava.'},
      {id:'s2',scene:'La prima domanda',text:'{{name}} chiese: «Dove porta il sentiero più vicino?». Una linea comparve sulla carta, ma terminava davanti a un cerchio bianco. {{companion}} provò una domanda diversa: «Chi usa quel sentiero?». Sul cerchio apparvero piccole orme e un simbolo a forma di zaino.',detail:'La mappa non mostrava soltanto luoghi. Mostrava relazioni tra luoghi, persone e motivi.'},
      {id:'s3',scene:'La domanda troppo grande',text:'«Come funziona tutto {{world}}?» domandò {{name}}. La mappa si riempì di linee confuse e poi si spense. Era una domanda enorme. {{name}} la spezzò: «Da dove viene l’acqua di questa fontana?». Una linea azzurra apparve e conduceva verso {{place}}.',detail:'Le domande grandi non erano sbagliate. A volte avevano bisogno di diventare una scala di domande più piccole.',optionalForShort:true},
      {id:'s4',scene:'Seguire l’acqua',text:'Il percorso li portò a un canale nascosto. L’acqua, però, era quasi ferma. {{name}} osservò foglie, pietre e piccole bolle. «Che cosa la blocca?», chiese. La mappa evidenziò un punto sotto una radice. Lì trovarono una ruota incastrata da un ramo.',detail:'Non era stato necessario conoscere in anticipo la risposta. Era bastato fare una domanda precisa e guardare le prove.'},
      {id:'s5',scene:'La domanda sbagliata',text:'Davanti a una porta chiusa, {{name}} domandò: «Qual è la parola magica?». La mappa non reagì. Provò: «Perché questa porta è stata chiusa?». Comparve il disegno di un piccolo animale che cercava tranquillità. La porta non proteggeva un tesoro; proteggeva qualcuno che aveva bisogno di non essere disturbato.',detail:'Una buona domanda può cambiare non soltanto ciò che sappiamo, ma anche il modo in cui ci comportiamo.',optionalForShort:true},
      {id:'s6',scene:'L’indizio che contraddice',text:'Vicino a {{landmark}}, la mappa indicava una torre. Ma sul terreno non c’era alcuna torre, soltanto un’ombra lunga. {{name}} avrebbe potuto dire che la mappa era sbagliata. Invece chiese: «Quando compare la torre?». Aspettarono che il sole scendesse e l’ombra rivelò una scala disegnata sulla parete.',detail:'Cambiare domanda fu più utile che difendere la prima idea.'},
      {id:'s7',scene:'La stanza delle risposte provvisorie',text:'La scala conduceva a una stanza piena di barattoli. Su ogni etichetta c’era scritto “Risposta provvisoria”. Dentro, le risposte cambiavano quando arrivavano nuove informazioni. {{name}} ne aprì una: “Le stelle sono piccoli buchi nel cielo”. Poco dopo, la frase si trasformò in una spiegazione più precisa.',detail:'{{companion}} sorrise: «Imparare non significa non sbagliare mai. Significa lasciare alle idee lo spazio per migliorare». '},
      {id:'s8',scene:'Una domanda per aiutare',text:'La mappa mostrò infine un abitante perduto. Invece di chiedere soltanto dove fosse, {{name}} domandò: «Che cosa può vedere da lì? Che suono sente? Che cosa lo farebbe sentire al sicuro?». Le risposte disegnarono un luogo preciso e permisero di raggiungerlo senza spaventarlo.',detail:'Le domande diventarono una forma di cura: servivano a capire l’esperienza di qualcun altro, non soltanto a risolvere un enigma.',optionalForShort:true,optionalForMedium:true},
      {id:'s9',scene:'La matita delle domande',text:'Quando tornarono alla biblioteca, la mappa era piena di strade. Il bibliotecario regalò a {{name}} una matita con la punta di {{material}}. «Non scrive risposte», disse. «Scrive domande che meritano attenzione». Da allora, ogni cosa ordinaria poteva diventare l’inizio di una scoperta.',detail:'Una foglia non era più soltanto una foglia: diventava “Come beve?”, “Perché cambia colore?”, “Chi vive sotto di lei?”. Il mondo non era diventato più complicato. Era diventato più vivo.'}
    ]
  }
];
