window.FABLEA_STORIES_V2_11_12 = [
  {
    id:'v2-11-12-avventura-citta-nomi', age:'11-12', family:'avventura', adaptableToWorld:true, worlds:['*'],
    styles:['adventurous','mysterious'], moods:['Curiosità e voglia di scoprire','Tanta energia'], support:['Accendere l’immaginazione','Stimolare curiosità'],
    title:'{{name}} e la città che cambiava nome',
    subtitle:'Un viaggio tra identità imposte, nomi scelti e mappe che non riescono a restare ferme.',
    companion:'', cover:{icon:'🏙️',art:'castle'}, treasure:'la tessera senza nome in {{material}}',
    ritual:'Scrivete tre parole: una che gli altri usano per descrivervi, una che sentite vostra, una che state ancora esplorando.',
    activity:'Create una mappa di una città immaginaria in cui ogni quartiere prende il nome da una qualità, una domanda o un ricordo.',
    pages:[
      {id:'a1',scene:'Il cartello della frontiera',text:'Quando {{name}} attraversò {{threshold}}, il cartello all’ingresso cambiò tre volte. Prima diceva “Città dei Coraggiosi”, poi “Città di Chi Non Sbaglia Mai”, infine “Città di Quelli che Sanno Già Chi Sono”. {{companion}} provò a fotografarlo, ma nell’immagine comparve soltanto una superficie bianca. Ogni visitatore leggeva un nome diverso, scelto dalla città in base a ciò che pensava di dover diventare.',detail:'Il fenomeno non sembrava un semplice incantesimo. I nomi influenzavano postura, tono di voce e perfino le strade che le persone riuscivano a vedere.'},
      {id:'a2',scene:'Il quartiere delle etichette',text:'Nel primo quartiere, ogni abitante portava al collo una targa: “quello intelligente”, “quella difficile”, “il simpatico”, “la responsabile”, “quello che non finisce mai niente”. Alcuni sembravano fieri, altri stanchi. Una ragazza chiamata “Perfetta” confessò di non ricordare più il proprio nome. «Quando faccio qualcosa di normale, sembra una delusione», disse.',detail:'{{name}} notò che le targhe non erano tutte negative. Anche quelle considerate complimenti potevano trasformarsi in gabbie, perché non lasciavano spazio a cambiare o a essere contraddittori.'},
      {id:'a3',scene:'La mappa selettiva',text:'La mappa della città mostrava soltanto i luoghi compatibili con la targa di chi la teneva. A “Perfetta” indicava scuole, palazzi e sale di premiazione, ma nascondeva parchi e laboratori dove si poteva sbagliare. A {{name}} offriva una strada diversa ogni volta che cambiava pensiero su di sé. Per raggiungere {{landmark}}, serviva una mappa capace di ammettere possibilità multiple.',detail:'{{companion}} propose di sovrapporre le mappe di persone diverse. Le strade mancanti cominciarono a comparire negli spazi tra una definizione e l’altra.',optionalForShort:true},
      {id:'a4',scene:'L’ufficio dei nomi definitivi',text:'Al centro della città sorgeva un ufficio dove, a dodici anni, ogni abitante doveva scegliere un nome definitivo. Un funzionario spiegò che la regola evitava confusione: una volta deciso chi essere, la città avrebbe assegnato il percorso più adatto. {{name}} chiese che cosa accadesse a chi cambiasse interessi, idee o desideri. Il funzionario indicò una porta laterale: “Casi irregolari”.',detail:'Dietro la porta c’erano fascicoli di persone che avevano cambiato strada. Non erano scomparse: la città aveva semplicemente smesso di saperle rappresentare.'},
      {id:'a5',scene:'I casi irregolari',text:'Nei sotterranei, {{name}} incontrò musicisti diventati scienziati, atleti che amavano scrivere, persone coraggiose in alcune situazioni e impaurite in altre. Ognuno conservava vecchie targhe, non come errori, ma come parti di una storia. Una donna disse: «Il problema non è scegliere. È credere che una scelta debba cancellare tutte le altre versioni possibili».',detail:'I casi irregolari avevano costruito una rete di passaggi non ufficiali. Grazie a loro, la città continuava a funzionare anche quando le mappe pubbliche fallivano.'},
      {id:'a6',scene:'La proposta del sindaco',text:'Il sindaco ricevette {{name}} in una sala piena di specchi. Sosteneva che i nomi definitivi dessero sicurezza e rendessero semplice organizzare scuole, lavori e gruppi. «Senza categorie, come sapremmo dove collocare le persone?», domandò. {{name}} rispose che le categorie possono essere strumenti, ma diventano pericolose quando pretendono di essere identità complete.',detail:'Il sindaco non era convinto. Propose una prova: se {{name}} avesse attraversato la città senza una definizione stabile, la regola sarebbe stata discussa pubblicamente.'},
      {id:'a7',scene:'Il percorso delle contraddizioni',text:'La prova iniziò con porte che si aprivano soltanto a chi dichiarava una qualità. {{name}} disse: «A volte sono sicuro, a volte ho bisogno di tempo». La prima porta esitò, poi si aprì in due direzioni. Più avanti, un ponte chiedeva di scegliere tra ragione e immaginazione. {{name}} rifiutò l’alternativa: usò calcoli per verificare la struttura e immaginazione per trovare una via diversa.',detail:'Ogni risposta non esclusiva creava un passaggio nuovo. La città, abituata a caselle nette, scopriva di poter sostenere identità più complesse.'},
      {id:'a8',scene:'Il nome rubato',text:'Vicino a {{landmark}}, una figura mascherata sottrasse la targa temporanea di {{name}}. Senza di essa, le guardie non sapevano come registrare il passaggio. {{companion}} suggerì di scegliere in fretta una nuova etichetta, ma {{name}} decise di proseguire senza. Gli abitanti iniziarono a fare domande invece di affidarsi alla targa: «Che cosa cerchi? Che cosa sai fare? Di che cosa hai bisogno adesso?».',detail:'Quelle domande richiedevano più tempo, ma producevano incontri più precisi. Nessuno poteva più fingere di conoscere una persona leggendo una sola parola.'},
      {id:'a9',scene:'La piazza dei nomi mobili',text:'Nella piazza centrale, i casi irregolari esposero targhe cancellabili. Ogni persona poteva scrivere parole diverse a seconda del contesto e lasciare spazi vuoti. “Studente” poteva convivere con “musicista”, “incerto”, “amico”, “in cambiamento”. Alcuni abitanti temevano che tutto diventasse confuso; altri sentirono per la prima volta di poter respirare.',detail:'{{name}} propose una regola semplice: nessuna parola scelta da altri avrebbe potuto sostituire la possibilità di descriversi e cambiare.'},
      {id:'a10',scene:'Il voto sulle mappe',text:'La città votò. Non abolì nomi, ruoli o categorie: li rese modificabili e dichiaratamente incompleti. Le mappe cominciarono a mostrare strade opzionali, deviazioni e percorsi di ritorno. Le scuole crearono passaggi tra discipline; i quartieri smisero di appartenere a un solo tipo di persona. Il cartello all’ingresso fu lasciato vuoto, con una domanda: “Che cosa stai diventando?”.',detail:'La domanda non pretendeva una risposta immediata. Permetteva di entrare anche a chi non aveva ancora deciso, o aveva deciso più di una cosa.',optionalForShort:true,optionalForMedium:true},
      {id:'a11',scene:'La tessera senza nome',text:'Prima della partenza, il sindaco consegnò a {{name}} una tessera di {{material}}. Non riportava alcuna etichetta, soltanto una frase sul retro: “Valida durante i cambiamenti”. A casa, la tessera non risolse le domande sull’identità. Le rese meno minacciose. {{name}} poteva scegliere, provare, cambiare e conservare tracce delle versioni precedenti senza essere obbligato a trasformarne una in prigione.',detail:'Da allora, quando qualcuno chiedeva “Che tipo di persona sei?”, {{name}} poteva rispondere con una storia, una direzione o una domanda. Una sola parola non era più l’unica forma ammessa.'}
    ]
  },
  {
    id:'v2-11-12-calma-ora-silenzio', age:'11-12', family:'calma-sera', adaptableToWorld:true, worlds:['*'],
    styles:['calm','emotional'], moods:['Momento tranquillo','Stanchezza'], support:['Calmare la sera','Favorire piccoli rituali'],
    title:'{{name}} e l’ora in cui il rumore si ferma',
    subtitle:'Una storia sulla stanchezza invisibile e sul diritto di non essere sempre raggiungibili.',
    companion:'', cover:{icon:'🌒',art:'space'}, treasure:'il minuto intatto custodito in {{material}}',
    ritual:'Stabilite un piccolo confine serale: dieci minuti senza notifiche, richieste o decisioni, con una sola attività scelta.',
    activity:'Disegnate una giornata come una linea sonora e indicate dove servono pause, volume basso e silenzio.',
    pages:[
      {id:'c1',scene:'La città che non interrompe mai',text:'A {{place}} ogni oggetto chiedeva attenzione. Le finestre mostravano messaggi, i lampioni trasmettevano annunci, le panchine suggerivano attività e perfino le tazze ricordavano di bere più in fretta. Nessun suono era fortissimo, ma insieme formavano un ronzio continuo. {{name}} arrivò stanco senza capire da che cosa, perché non era successo nulla di particolarmente difficile.',detail:'{{companion}} spiegò che la stanchezza non nasce soltanto dagli eventi grandi. Può accumularsi in centinaia di piccoli richiami che impediscono alla mente di completare un pensiero.'},
      {id:'c2',scene:'Il servizio di reperibilità totale',text:'Gli abitanti portavano un bracciale che diventava caldo ogni volta che qualcuno li cercava. Rispondere subito era considerato gentilezza; non farlo sembrava disinteresse. Una ragazza confessò di dormire con il bracciale acceso per paura di perdere qualcosa. Un anziano aveva smesso di leggere perché ogni pagina veniva interrotta da richieste minime.',detail:'Nessuno aveva imposto la reperibilità totale con una legge. Era diventata normale un’abitudine alla volta, finché scegliere di non rispondere sembrava una colpa.'},
      {id:'c3',scene:'L’orologiaio delle pause',text:'Vicino a {{landmark}} viveva un orologiaio che riparava soltanto i minuti interrotti. Sul tavolo conservava frammenti di conversazioni, respiri a metà e pensieri abbandonati. «Un minuto intatto non è un minuto vuoto», disse. «È un contenitore in cui qualcosa può finalmente arrivare alla fine». Chiese a {{name}} di proteggerne uno.',detail:'Il compito sembrava semplice. In realtà, il primo minuto fu assediato da campanelli, curiosità, impulsi a controllare e dalla sensazione che fermarsi fosse uno spreco.',optionalForShort:true},
      {id:'c4',scene:'Il primo confine',text:'{{name}} spense il bracciale e mise un cartello: “Torno tra dieci minuti”. Alcuni abitanti protestarono, ma nessuna emergenza reale si verificò. Nel silenzio emersero cose prima coperte dal rumore: {{sound}}, il proprio respiro, una preoccupazione precisa che fino a quel momento sembrava soltanto stanchezza indistinta.',detail:'Il confine non eliminò le richieste. Le mise in attesa, permettendo a {{name}} di distinguere ciò che era urgente da ciò che era semplicemente immediato.'},
      {id:'c5',scene:'La paura di restare indietro',text:'Una notifica riuscì a entrare dalla finestra: annunciava una conversazione a cui tutti stavano partecipando. {{name}} sentì il bisogno di controllare. L’orologiaio non lo vietò. Chiese: «Che cosa temi di perdere? E che cosa perdi ogni volta che interrompi te stesso?». {{name}} scelse di finire il minuto e poi leggere il messaggio.',detail:'La conversazione era ancora lì. Alcune parti erano già passate, ma nulla di essenziale richiedeva una presenza costante.'},
      {id:'c6',scene:'Il rumore interno',text:'Quando i suoni esterni diminuirono, i pensieri diventarono più evidenti. {{name}} si aspettava calma immediata e invece incontrò elenchi, ricordi e frasi non concluse. «Il silenzio non è sempre rilassante all’inizio», spiegò {{companion}}. «A volte restituisce tutto ciò che il rumore aveva tenuto in sospeso». Serviva tempo, non un altro stimolo.',detail:'{{name}} scrisse i pensieri su un foglio, senza risolverli. Vederli separati ridusse la sensazione che fossero un’unica massa impossibile.'},
      {id:'c7',scene:'La proposta alla città',text:'L’orologiaio invitò {{name}} a presentare un’idea al consiglio: un’ora quotidiana in cui servizi non essenziali, annunci e richieste avrebbero ridotto il volume. Alcuni temevano isolamento e perdita di opportunità. {{name}} propose eccezioni chiare per emergenze, possibilità di scegliere l’orario e messaggi che indicassero quando aspettarsi una risposta.',detail:'Il riposo funzionava meglio quando non dipendeva soltanto dalla forza di volontà individuale, ma veniva sostenuto da regole sociali comprensibili.'},
      {id:'c8',scene:'La prima ora quieta',text:'La prova iniziò al tramonto. Le insegne smisero di aggiornarsi, i bracciali passarono in modalità silenziosa e le panchine tornarono a essere soltanto panchine. All’inizio molte persone camminavano senza sapere che cosa fare. Poi qualcuno parlò con chi aveva accanto. Altri guardarono {{sky}}. Qualcuno scelse semplicemente di non produrre nulla.',detail:'La città non si fermò completamente: ospedali, trasporti e servizi essenziali continuarono. Si fermò l’idea che ogni momento dovesse chiedere una reazione.'},
      {id:'c9',scene:'Chi non riusciva a fermarsi',text:'Non tutti trovarono beneficio immediato. Un ragazzo disse che nel silenzio si sentiva più solo. Una donna preferiva lavorare proprio a quell’ora. Il consiglio capì che la quiete non poteva diventare un’altra imposizione. Crearono spazi diversi: stanze silenziose, luoghi di compagnia tranquilla, percorsi per camminare, canali disponibili per chi aveva bisogno di contatto.',detail:'Proteggere il riposo significava offrire alternative, non stabilire una sola forma corretta di calma.'},
      {id:'c10',scene:'Un ritmo sostenibile',text:'Dopo alcune settimane, gli abitanti rispondevano con meno fretta e più precisione. Le conversazioni importanti duravano di più perché venivano interrotte meno. Alcuni problemi attendevano l’ora successiva e risultavano più semplici. {{name}} scoprì che essere raggiungibile in ogni istante non rendeva necessariamente più presente; a volte produceva soltanto frammenti di attenzione.',detail:'Il tempo quieto non era sottratto alla vita. Restituiva continuità alle parti della vita che il rumore aveva spezzato.',optionalForShort:true,optionalForMedium:true},
      {id:'c11',scene:'Il minuto intatto',text:'L’orologiaio regalò a {{name}} una piccola capsula di {{material}}. Dentro non c’era nulla, e proprio per questo era preziosa: custodiva un minuto non ancora occupato. Ogni sera {{name}} poteva decidere come usarlo — respirare, leggere, ascoltare musica, guardare fuori — senza trasformarlo in un altro compito da svolgere bene.',detail:'Il minuto non garantiva serenità. Garantiva uno spazio in cui la serenità, la stanchezza o qualsiasi altro stato potessero presentarsi senza essere immediatamente sostituiti.'}
    ]
  },
  {
    id:'v2-11-12-emozioni-versioni', age:'11-12', family:'emozioni', adaptableToWorld:true, worlds:['*'],
    styles:['emotional','mysterious'], moods:['Una giornata difficile','Un po’ di rabbia','Una piccola paura'], support:['Aiutare con le emozioni'],
    title:'{{name}} e la stanza delle versioni possibili',
    subtitle:'Incontrare i futuri immaginati senza trasformarli in obblighi.',
    companion:'', cover:{icon:'🪞',art:'castle'}, treasure:'il frammento di specchio in {{material}}',
    ritual:'Scrivete una versione futura che vi incuriosisce e aggiungete: “Non è una promessa. È una possibilità da esplorare”.',
    activity:'Create quattro carte-futuro: una desiderata, una improbabile, una temuta e una ancora senza nome.',
    pages:[
      {id:'e1',scene:'La porta dopo {{landmark}}',text:'Dietro {{landmark}}, {{name}} trovò una stanza circolare piena di specchi. Nessuno rifletteva il presente. In uno, {{name}} parlava davanti a una folla. In un altro lavorava in solitudine. In un terzo viveva lontano. Ogni immagine sembrava convincente e pretendeva attenzione. {{companion}} lesse l’iscrizione sul pavimento: “Possibile non significa necessario”.',detail:'Alcuni specchi mostravano scene desiderabili, altri inquietanti. Tutti avevano la stessa qualità: sembravano completi, come se una singola immagine potesse raccontare un’intera vita.'},
      {id:'e2',scene:'La versione perfetta',text:'Uno specchio mostrava una versione di {{name}} capace, sicura e ammirata. Non esitava mai e otteneva risultati visibili. Avvicinandosi, però, {{name}} notò che quella figura non riposava, non chiedeva aiuto e nascondeva ogni errore. «Perché sembri così stanca?», domandò. Il riflesso rispose: «Perché devo dimostrare continuamente di meritare questa immagine».',detail:'La perfezione appariva attraente da lontano, ma richiedeva un controllo costante. Non lasciava spazio a giornate normali o cambi di direzione.'},
      {id:'e3',scene:'La versione che ha rinunciato',text:'Un altro specchio mostrava {{name}} dopo aver evitato ogni rischio. La vita era ordinata, prevedibile e priva di grandi fallimenti. La figura disse di sentirsi al sicuro, ma guardava spesso una porta chiusa. «Non so che cosa ci fosse dall’altra parte», ammise. Non era una condanna; era il risultato di molte scelte comprensibili guidate dalla paura.',detail:'{{name}} provò compassione invece di disprezzo. Quella versione aveva cercato protezione con gli strumenti disponibili, non aveva semplicemente “mancato di coraggio”.',optionalForShort:true},
      {id:'e4',scene:'La versione scelta dagli altri',text:'Nel terzo specchio, {{name}} seguiva un percorso apprezzato da famiglia, insegnanti e amici. Riceveva approvazione, ma parlava con parole che sembravano prese in prestito. Quando {{name}} chiese: «Ti piace davvero?», il riflesso rispose: «Non ho avuto tempo di capirlo. Ero occupato a non deludere».',detail:'L’approvazione non era falsa né inutile. Il problema nasceva quando diventava l’unico criterio ammesso.'},
      {id:'e5',scene:'La versione impossibile da vedere',text:'Uno specchio restava appannato. {{name}} provò a pulirlo, ma il vetro tornava opaco. {{companion}} suggerì che forse rappresentava eventi non ancora immaginabili: incontri, interessi e cambiamenti che il presente non possedeva gli strumenti per prevedere. Quello spazio vuoto fece più paura degli altri perché non offriva controllo.',detail:'Allo stesso tempo, era l’unico specchio che non imponeva un copione. La sua incertezza conteneva possibilità non ancora limitate dalle aspettative attuali.'},
      {id:'e6',scene:'Il giudice degli specchi',text:'Dal centro della stanza emerse una figura incaricata di scegliere la versione “migliore”. Confrontava successo, sicurezza e approvazione, assegnando punteggi. Chiese a {{name}} di selezionare un futuro prima di uscire. {{name}} rifiutò il criterio: nessuna immagine mostrava relazioni complete, salute, caso, costi o trasformazioni interiori.',detail:'Ridurre una vita a una classifica produceva un’illusione di precisione. I numeri nascondevano valori che non erano stati scelti da chi avrebbe dovuto viverli.'},
      {id:'e7',scene:'La conversazione tra versioni',text:'{{name}} aprì gli specchi e invitò le versioni a parlare tra loro. La Perfetta desiderava il riposo della versione prudente. Quella prudente ammirava la libertà della versione sconosciuta. La versione approvata dagli altri voleva imparare a riconoscere una preferenza propria. Nessuna era completamente giusta o sbagliata; ognuna conteneva bisogni, paure e risorse.',detail:'Le versioni smisero di competere quando capirono di poter offrire informazioni al presente invece di pretendere di diventare l’unico futuro.'},
      {id:'e8',scene:'Una scelta reversibile',text:'Per uscire dalla stanza serviva comunque una decisione. Non una decisione sull’intera vita, ma sul prossimo passo. {{name}} scelse un’esperienza piccola e reversibile: provare, informarsi, parlare con qualcuno, dedicare tempo a un interesse. Il giudice protestò che non era abbastanza definitivo. Proprio per questo era una scelta onesta.',detail:'Le decisioni esplorative permettono di raccogliere dati su di sé senza trasformare ogni tentativo in identità permanente.'},
      {id:'e9',scene:'Lo specchio del presente',text:'Tra i riflessi comparve finalmente uno specchio normale. Mostrava {{name}} con dubbi, qualità, contraddizioni e possibilità aperte. Non era la versione più spettacolare, ma era l’unica capace di agire adesso. Sul bordo apparvero tre domande: “Che cosa conta?”, “Che cosa posso provare?”, “Che cosa sono disposto a rivedere?”.',detail:'Il presente non aveva l’eleganza narrativa dei futuri immaginati. Aveva però accesso al tempo, alle relazioni e alla possibilità di correggere.'},
      {id:'e10',scene:'La stanza cambia funzione',text:'{{name}} propose di trasformare la stanza. Gli specchi non avrebbero più assegnato destini; sarebbero diventati strumenti per esplorare conseguenze, desideri e paure. Ogni visitatore avrebbe potuto annotare che cosa lo attirava e che cosa lo preoccupava, senza scegliere una versione definitiva. Il giudice divenne archivista delle domande.',detail:'La stanza conservava ancora futuri possibili, ma ora dichiarava i propri limiti: scenari parziali, costruiti con informazioni presenti e aperti a cambiamenti imprevedibili.',optionalForShort:true,optionalForMedium:true},
      {id:'e11',scene:'Il frammento non riflettente',text:'Prima di tornare, {{name}} ricevette un frammento di specchio in {{material}}. Non mostrava un volto: rifletteva soltanto la luce intorno. Sul retro era incisa una frase: “Non devi diventare oggi la persona che sarai per sempre”. Quando le aspettative future diventavano troppo pesanti, il frammento ricordava che il compito del presente non è indovinare tutta la vita, ma viverne con attenzione il tratto disponibile.',detail:'Il futuro rimaneva importante, ma smetteva di essere un tribunale. Poteva tornare a essere un territorio da conoscere un passo, una prova e una revisione alla volta.'}
    ]
  },
  {
    id:'v2-11-12-scoperta-atlante', age:'11-12', family:'scoperta', adaptableToWorld:true, worlds:['*'],
    styles:['mysterious','adventurous'], moods:['Curiosità e voglia di scoprire','Momento tranquillo'], support:['Stimolare curiosità','Accendere l’immaginazione'],
    title:'{{name}} e l’atlante delle domande senza risposta',
    subtitle:'Un viaggio tra ciò che sappiamo, ciò che non sappiamo ancora e ciò che forse non avrà una risposta unica.',
    companion:'', cover:{icon:'📚',art:'space'}, treasure:'la pagina trasparente in {{material}}',
    ritual:'Scegliete una domanda aperta e dividetela in: ciò che è verificabile, ciò che dipende dai valori, ciò che resta incerto.',
    activity:'Create una pagina di atlante con una domanda, tre fonti possibili e una sezione intitolata “Che cosa potrebbe farmi cambiare idea?”.',
    pages:[
      {id:'s1',scene:'Il libro che non finiva',text:'Nella biblioteca di {{place}}, {{name}} trovò un atlante enorme aperto su una pagina bianca. Il titolo era: “Domande senza risposta”. Appena {{name}} pensò che forse il libro fosse incompleto, apparvero migliaia di voci: “Che cosa rende giusta una scelta?”, “Siamo soli nell’universo?”, “Quanto di noi cambia nel tempo?”, “Una storia può essere vera senza essere accaduta?”.',detail:'Le domande non erano ordinate per materia, ma per il tipo di incertezza che contenevano: dati mancanti, concetti difficili, valori in conflitto, limiti dell’osservazione.'},
      {id:'s2',scene:'Il cartografo delle incertezze',text:'Il custode dell’atlante era un cartografo che non disegnava territori, ma confini della conoscenza. «Una buona mappa mostra anche dove terminano le informazioni», spiegò. Consegnò a {{name}} tre strumenti: una lente per le prove, una bilancia per i valori e una bussola che indicava le ipotesi alternative.',detail:'{{companion}} aggiunse una matita cancellabile. Nell’atlante, correggere una pagina non era vandalismo: era parte del lavoro.'},
      {id:'s3',scene:'La domanda con una risposta nascosta',text:'La prima tappa chiedeva perché una sorgente vicino a {{landmark}} cambiasse colore. Gli abitanti proponevano leggende diverse. {{name}} raccolse campioni, confrontò l’acqua in orari differenti e scoprì microrganismi che reagivano alla luce. La domanda aveva una spiegazione verificabile, anche se nuove osservazioni avrebbero potuto renderla più precisa.',detail:'Il cartografo segnò la pagina in verde: “Risposta sostenuta da prove, aperta a revisioni”. Non tutte le domande senza risposta rimangono tali per sempre.',optionalForShort:true},
      {id:'s4',scene:'La domanda che dipende dalle parole',text:'La seconda tappa chiedeva: “Qual è il luogo più bello di {{world}}?”. Gruppi diversi difendevano {{landmark}}, {{threshold}} o una piccola strada laterale. {{name}} capì che il problema non era trovare la misurazione corretta, ma chiarire che cosa significasse “bello”: armonioso, emozionante, familiare, raro. La domanda conteneva criteri diversi, non un unico dato nascosto.',detail:'La pagina fu segnata in blu: “Risposte argomentabili, legate a esperienze e valori”. Discutere restava utile, purché nessuno fingesse che una preferenza fosse una legge naturale.'},
      {id:'s5',scene:'La domanda impossibile da osservare direttamente',text:'La terza tappa riguardava una civiltà scomparsa. Restavano edifici, strumenti e lettere incomplete, ma nessuna testimonianza totale. Gli studiosi costruivano ricostruzioni plausibili partendo dagli indizi. {{name}} confrontò due teorie: entrambe spiegavano alcuni dati e lasciavano problemi aperti. Non era possibile tornare indietro per osservare direttamente.',detail:'Il cartografo usò il colore ambra: “Conoscenza indiretta, livelli di probabilità”. L’incertezza non annullava ciò che si poteva sapere; richiedeva un linguaggio più preciso.'},
      {id:'s6',scene:'La risposta proibita',text:'In una sala chiusa, un sovrano aveva ordinato che una domanda avesse una sola risposta ufficiale. Le fonti contrarie erano state rimosse dall’atlante. {{name}} trovò cancellature e note nascoste. Capì che l’assenza di alternative non dimostrava consenso: poteva essere il risultato di potere, paura o accesso limitato alle informazioni.',detail:'Ricostruire la pagina richiese cercare chi non era stato ascoltato e distinguere testimonianze, propaganda e interpretazioni successive.'},
      {id:'s7',scene:'La domanda personale',text:'L’atlante presentò una domanda rivolta a {{name}}: “Quale vita ti renderebbe felice?”. La lente per le prove mostrava esperienze passate, la bilancia rivelava valori importanti, ma nessuno strumento produceva una risposta definitiva. Desideri e condizioni sarebbero cambiati. {{name}} poteva formulare ipotesi e testarle attraverso scelte graduali.',detail:'Le domande personali non erano meno serie perché prive di soluzione universale. Richiedevano osservazione di sé, tempo e disponibilità a rivedere ciò che sembrava certo.'},
      {id:'s8',scene:'Il mercato delle risposte semplici',text:'Fuori dalla biblioteca, venditori promettevano risposte rapide a domande complesse. Alcuni usavano paura, altri sicurezza assoluta, altri frasi abbastanza vaghe da sembrare sempre corrette. {{name}} applicò tre controlli: quali prove vengono offerte, quali alternative sono ignorate, che cosa guadagna chi propone la risposta. Molte certezze persero brillantezza.',detail:'Non ogni risposta semplice era falsa. Il problema era la semplicità usata per nascondere passaggi, limiti o interessi.'},
      {id:'s9',scene:'La pagina in conflitto',text:'Due comunità chiedevano come usare una risorsa limitata vicino a {{place}}. I dati descrivevano quantità e conseguenze, ma non decidevano da soli che cosa fosse giusto. Entravano in gioco equità, bisogni presenti, futuro e responsabilità. {{name}} aiutò a separare disaccordi sui fatti da disaccordi sui valori, così la discussione divenne più onesta.',detail:'Alcune decisioni richiedono prove solide e, dopo le prove, una scelta politica o morale. Confondere i due livelli rende facile accusare l’altro di ignoranza quando in realtà protegge un valore diverso.'},
      {id:'s10',scene:'Il confine mobile',text:'Arrivando all’ultima pagina, {{name}} vide che il confine tra noto e ignoto si muoveva. Ogni risposta faceva nascere nuove domande. Scoprire la causa di un fenomeno apriva interrogativi sui meccanismi; chiarire un valore mostrava conflitti con altri valori. L’atlante non si avvicinava alla fine: diventava più dettagliato.',detail:'Il cartografo spiegò che la conoscenza non riduce semplicemente il numero di domande. Migliora la qualità delle domande disponibili.',optionalForShort:true,optionalForMedium:true},
      {id:'s11',scene:'La pagina trasparente',text:'Il cartografo regalò a {{name}} una pagina trasparente in {{material}}. Sovrapposta a qualsiasi testo, faceva comparire tre righe: “Quanto è certo?”, “Da che cosa dipende?”, “Che cosa resta aperto?”. Non serviva a dubitare di tutto nello stesso modo. Serviva a distinguere tra fatto ben sostenuto, ipotesi, interpretazione e valore.',detail:'A casa, {{name}} inserì nell’atlante una nuova domanda. Non cercò di chiuderla subito. Annotò ciò che sapeva, ciò che avrebbe potuto verificare e il punto in cui iniziava l’incertezza. La pagina bianca non sembrò più un fallimento, ma una forma precisa di onestà.'}
    ]
  }
];
