window.FABLEA_STORIES_V2_8_10 = [
  {
    id:'v2-8-10-avventura-archivio-strade', age:'8-10', family:'avventura', adaptableToWorld:true, worlds:['*'],
    styles:['adventurous','mysterious'], moods:['Curiosità e voglia di scoprire','Tanta energia'], support:['Accendere l’immaginazione','Stimolare curiosità'],
    title:'{{name}} e l’archivio delle strade scomparse',
    subtitle:'Quando le mappe dimenticano una strada, qualcuno deve avere il coraggio di percorrerla.',
    companion:'', cover:{icon:'🧭',art:'castle'}, treasure:'la bussola incompleta di {{material}}',
    ritual:'Disegnate una strada che non conoscete ancora e scrivete il primo passo possibile, non l’intero percorso.',
    activity:'Create una mappa di un luogo conosciuto aggiungendo un passaggio immaginario e una regola per attraversarlo.',
    pages:[
      {id:'a1',scene:'La strada cancellata',text:'All’ingresso di {{place}}, {{name}} vide un cartello indicare {{landmark}}. Un istante dopo, le lettere svanirono e il sentiero si richiuse sotto erba e polvere. Gli abitanti continuarono a passare senza accorgersene, come se quella direzione non fosse mai esistita. Solo {{companion}} ricordava che un tempo da lì si raggiungeva l’Archivio delle Strade.',detail:'Sul terreno restava una linea più chiara, interrotta in alcuni punti. Sembrava la cicatrice di un percorso dimenticato, non una semplice traccia consumata.'},
      {id:'a2',scene:'Il paese con una sola via',text:'Nel centro di {{world}} tutte le persone camminavano lungo la stessa strada. Era larga, illuminata e sicura, ma diventava ogni giorno più affollata. Le altre vie erano sparite dalle mappe. Un mercante spiegò che, quando una strada smetteva di essere usata, l’Archivio la cancellava per “semplificare”. Nessuno ricordava chi avesse deciso quella regola.',detail:'La strada principale offriva indicazioni per ogni passo: dove fermarsi, quanto impiegare, che cosa aspettarsi. Era comoda, ma non lasciava spazio a sorprese o alternative.'},
      {id:'a3',scene:'Il margine della mappa',text:'{{name}} trovò una vecchia mappa nella bottega di una rilegatrice. Ai bordi erano annotate strade sottili, alcune segnate con punti interrogativi. La rilegatrice indicò una via chiamata “Percorso delle Cose Non Ancora Decise”. «È l’unica che può portarvi all’Archivio», disse. «Ma cambia quando chi la percorre pretende di sapere tutto in anticipo».',detail:'La carta reagiva alle domande: diventava rigida davanti a “Dimmi esattamente cosa succederà” e più morbida davanti a “Che cosa posso osservare al prossimo passo?”.',optionalForShort:true},
      {id:'a4',scene:'Il ponte senza fine visibile',text:'Il percorso conduceva a un ponte coperto di nebbia. Si vedevano soltanto tre assi alla volta. {{name}} cercò di immaginare il ponte intero e sentì crescere l’ansia. {{companion}} propose di verificare un asse, poi il successivo. Ogni passo controllato faceva apparire un nuovo pezzo, mentre quelli alle spalle restavano solidi.',detail:'Non era un ponte che chiedeva fiducia cieca. Chiedeva attenzione al tratto disponibile e la possibilità di fermarsi se qualcosa non convinceva.'},
      {id:'a5',scene:'La deviazione sbagliata',text:'Dopo il ponte, un segnale indicava due direzioni. {{name}} scelse quella che sembrava più breve, ma portava a una parete. Per qualche minuto pensò di aver rovinato la missione. Poi notò incisioni sulla roccia: erano i tentativi di altri viaggiatori, con note su ciò che avevano imparato. La deviazione non conduceva avanti, ma offriva informazioni utili.',detail:'{{name}} copiò le incisioni sulla mappa. Tornare indietro non cancellava il tempo trascorso: trasformava un errore in orientamento.'},
      {id:'a6',scene:'Il custode dell’archivio',text:'L’Archivio apparve sotto {{landmark}}, costruito con scaffali altissimi e cassetti pieni di sentieri arrotolati. Il custode sosteneva di cancellare le vie poco usate per proteggere le persone dall’incertezza. «Una sola strada evita confusione», disse. {{name}} gli mostrò il paese bloccato, la via affollata e le possibilità perdute.',detail:'Il custode non era malvagio. Aveva visto persone perdersi e aveva concluso che il problema fossero le alternative, non la mancanza di strumenti per sceglierle.'},
      {id:'a7',scene:'La prova delle tre destinazioni',text:'Per cambiare la regola, {{name}} doveva recuperare tre rotoli: una strada utile, una strada bella e una strada che non serviva ancora a niente. La prima conduceva a una sorgente. La seconda attraversava un panorama sotto {{sky}}. La terza terminava in uno spiazzo vuoto. Il custode voleva eliminare quest’ultima, ma {{name}} chiese tempo.',detail:'Nello spiazzo trovarono impronte di animali, un punto perfetto per osservare il cielo e terreno adatto a un futuro giardino. L’utilità non era assente: non era stata ancora immaginata.'},
      {id:'a8',scene:'La scelta pubblica',text:'Il custode accettò di riaprire le strade soltanto se gli abitanti avessero scelto come gestirle. Alcuni volevano indicazioni dettagliate, altri percorsi liberi. {{name}} propose mappe con livelli diversi: vie sicure e segnate, vie da esplorare con preparazione, sentieri temporaneamente chiusi. La scelta non era tra controllo totale e caos.',detail:'Gli abitanti discussero, modificarono la proposta e aggiunsero punti di ritrovo. La mappa divenne un accordo comune, non un ordine calato dall’alto.',optionalForShort:true},
      {id:'a9',scene:'Il ritorno delle vie',text:'Quando i cassetti dell’Archivio si aprirono, nastri luminosi attraversarono {{place}}. Vecchi ponti ricomparvero, vicoli tornarono ad avere un nome e sentieri dimenticati si disegnarono tra gli alberi o le case. La strada principale non scomparve: smise soltanto di essere l’unica possibilità.',detail:'Le persone iniziarono a raccontarsi i percorsi. Ogni mappa portava note su difficoltà, bellezza, tempo e sorprese, così scegliere diventava più consapevole senza diventare automatico.',optionalForShort:true,optionalForMedium:true},
      {id:'a10',scene:'La bussola incompleta',text:'Il custode consegnò a {{name}} una bussola con uno spazio vuoto al posto del nord. «Non indica una direzione unica», spiegò. «Segnala ciò che conta per te in quel momento: sicurezza, curiosità, compagnia, tempo». A casa, la bussola non diede risposte immediate, ma aiutò {{name}} a formulare domande migliori prima di scegliere.',detail:'Da allora, davanti a una strada nuova, {{name}} non cercava la certezza assoluta. Cercava informazioni sufficienti, un primo passo possibile e la libertà di cambiare rotta.'}
    ]
  },
  {
    id:'v2-8-10-calma-luci', age:'8-10', family:'calma-sera', adaptableToWorld:true, worlds:['*'],
    styles:['calm','mysterious'], moods:['Momento tranquillo','Stanchezza'], support:['Calmare la sera','Favorire piccoli rituali'],
    title:'{{name}} e la notte delle luci non necessarie',
    subtitle:'Per ritrovare il cielo, {{world}} deve scegliere quali luci servono davvero.',
    companion:'', cover:{icon:'🌌',art:'space'}, treasure:'la piccola stella di {{material}}',
    ritual:'Prima di dormire, spegnete una luce non necessaria e scegliete un pensiero da lasciare acceso per domani.',
    activity:'Disegnate la vostra stanza con tre tipi di luce: utile, rassicurante e superflua.',
    pages:[
      {id:'c1',scene:'Un cielo senza stelle',text:'A {{place}} la notte non diventava mai davvero buia. Insegne, torri, finestre, sentieri e fontane restavano illuminati fino al mattino. Gli abitanti dicevano che tanta luce li faceva sentire sicuri, ma nessuno ricordava più {{sky}}. {{name}} notò che perfino {{companion}} faticava a distinguere l’orizzonte.',detail:'La luce entrava nelle camere, confondeva gli animali notturni e rendeva ogni ora simile alla precedente. Il mondo sembrava sveglio, ma non veramente attento.'},
      {id:'c2',scene:'La custode delle stelle',text:'Vicino a {{landmark}} viveva una custode con un telescopio coperto di polvere. «Le stelle non sono sparite», spiegò. «Siamo noi ad aver riempito ogni spazio». Chiese a {{name}} di aiutarla a spegnere tutto per un minuto. Il consiglio cittadino rifiutò: temeva incidenti, furti e paura.',detail:'{{name}} capì che non bastava dire “spegniamo”. Serviva distinguere tra luce utile, luce rassicurante e luce accesa soltanto per abitudine.'},
      {id:'c3',scene:'La mappa luminosa',text:'Con {{companion}}, {{name}} percorse {{world}} segnando ogni fonte di luce. Le lampade sui ponti proteggevano i passaggi. Una piccola luce all’ospedale indicava l’ingresso. Altre insegne illuminavano negozi chiusi; alcune torri puntavano il cielo senza motivo. La mappa mostrò che il problema non era la luce, ma l’assenza di scelte.',detail:'Registrarono anche colore e direzione: una luce calda rivolta a terra disturbava meno di un fascio bianco sparato verso le finestre.',optionalForShort:true},
      {id:'c4',scene:'La prova del quartiere',text:'Un piccolo quartiere accettò di sperimentare. Ridussero le insegne, schermarono le lampade e lasciarono accesi soltanto i percorsi necessari. All’inizio il silenzio visivo sembrò strano. Poi comparve una stella. Subito dopo, un’altra. Le persone uscirono sui balconi per guardare.',detail:'Nessuno si sentì abbandonato: le strade restavano leggibili. Era scomparsa soltanto la luce che invadeva luoghi in cui non serviva.'},
      {id:'c5',scene:'La paura del buio',text:'Un bambino del quartiere confessò di avere paura quando la stanza diventava completamente scura. {{name}} non gli disse che doveva abituarsi. Insieme scelsero una lampada bassa, color ambra, orientata verso il pavimento. La notte non richiedeva oscurità totale; richiedeva una luce capace di rispettare il riposo.',detail:'La custode annotò la soluzione: “La calma non è uguale per tutti. Progettare bene significa lasciare spazio anche ai bisogni diversi”.'},
      {id:'c6',scene:'Gli animali tornano',text:'Dopo alcune sere, piccoli animali e insetti ricomparvero vicino a {{threshold}}. Seguivano la luna invece di girare confusi intorno alle lampade. Le piante chiudevano i petali al momento giusto. {{name}} osservò che anche il corpo umano sembrava capire meglio quando era ora di rallentare.',detail:'La notte non era un’interruzione inutile. Era una fase del mondo con lavori propri: riparare, orientare, far riposare, permettere ad altre creature di vivere.'},
      {id:'c7',scene:'La discussione al consiglio',text:'Al consiglio alcuni commercianti temevano che meno luce significasse meno vita. {{name}} mostrò la mappa e propose orari, sensori e intensità diverse. Non tutto doveva spegnersi insieme. Le luci potevano diminuire quando le strade erano vuote e riaccendersi al passaggio, proteggendo sia le persone sia la notte.',detail:'La proposta funzionava perché non trasformava una buona idea in una regola cieca. Usava osservazioni, prove e possibilità di correzione.'},
      {id:'c8',scene:'Un minuto di cielo',text:'La sera della prova generale, tutte le luci non necessarie si abbassarono per un minuto. {{place}} cambiò volto. Sopra {{landmark}} comparve una fascia di stelle che nessuno aveva mai visto così chiaramente. Il silenzio durò poco, ma fu abbastanza perché molte persone capissero che cosa avevano perso.',detail:'Qualcuno pianse, qualcuno rise, qualcuno rimase immobile. Non era nostalgia di un passato: era la scoperta di uno spazio ancora possibile.',optionalForShort:true},
      {id:'c9',scene:'Una notte con più profondità',text:'Le nuove regole entrarono in funzione. Le strade importanti restavano sicure, le finestre potevano tornare buie e il cielo aveva di nuovo un posto. {{name}} camminò con {{companion}} ascoltando {{sound}} senza il ronzio continuo delle insegne. Ogni luce sembrava più preziosa perché non era circondata da altre cento.',detail:'La città non era diventata meno viva. Aveva ritrovato contrasto, ritmo e la possibilità di fermarsi.',optionalForShort:true,optionalForMedium:true},
      {id:'c10',scene:'La stella tascabile',text:'La custode regalò a {{name}} una piccola stella di {{material}}. Non illuminava una stanza; si vedeva soltanto quando il resto si calmava. «Portala con te», disse, «per ricordare che non ogni pensiero deve restare acceso tutta la notte». Prima di dormire, {{name}} scelse una preoccupazione da spegnere fino al mattino.',detail:'La preoccupazione non era risolta, ma poteva aspettare. Nel buio gentile rimase accesa una sola cosa: la fiducia di poterla riprendere con più energia il giorno dopo.'}
    ]
  },
  {
    id:'v2-8-10-emozioni-teatro-voci', age:'8-10', family:'emozioni', adaptableToWorld:true, worlds:['*'],
    styles:['emotional','mysterious'], moods:['Una giornata difficile','Un po’ di rabbia','Una piccola paura'], support:['Aiutare con le emozioni'],
    title:'{{name}} e il teatro delle voci interiori',
    subtitle:'Quando tutte le voci parlano insieme, serve un regista, non un silenziatore.',
    companion:'', cover:{icon:'🎭',art:'castle'}, treasure:'il biglietto da regista in {{material}}',
    ritual:'Scrivete tre voci che avete sentito oggi e date a ciascuna una battuta, poi decidete chi deve parlare per prima.',
    activity:'Create maschere di carta per la Voce Critica, la Paura, il Coraggio e la Curiosità.',
    pages:[
      {id:'e1',scene:'Il teatro chiuso',text:'Nel centro di {{place}} c’era un teatro che nessuno riusciva più ad aprire. Da dietro le porte arrivavano voci sovrapposte: “Non sei capace”, “Devi provarci”, “Scappa”, “Fatti vedere”, “Non deludere nessuno”. {{name}} riconobbe qualcosa di familiare in quel caos. {{companion}} trovò un biglietto con scritto: “Manca il regista”.',detail:'La facciata del teatro cambiava espressione a seconda della voce più forte: severa, spaventata, entusiasta, stanca.'},
      {id:'e2',scene:'Il palcoscenico affollato',text:'Entrando da {{threshold}}, {{name}} vide quattro personaggi discutere sotto i riflettori. La Voce Critica correggeva ogni gesto. La Paura immaginava disastri. La Curiosità apriva porte senza aspettare. Il Coraggio sosteneva di non aver bisogno di nessuno. Ognuno voleva essere protagonista dell’intero spettacolo.',detail:'In fondo alla platea sedeva una figura quasi invisibile: la Stanchezza. Non gridava, ma rendeva tutte le altre voci più irritabili.'},
      {id:'e3',scene:'Il tentativo di spegnere tutto',text:'{{name}} abbassò i riflettori e ordinò silenzio. Per qualche secondo funzionò. Poi le voci ricominciarono più forti, battendo sulle quinte. {{companion}} osservò che nessuna era comparsa per caso. Anche la Critica cercava di evitare errori; anche la Paura voleva proteggere. Il problema era il volume e il momento, non la loro esistenza.',detail:'Eliminare una voce avrebbe significato perdere anche l’informazione che portava. Serviva imparare ad ascoltarla senza consegnarle tutto il copione.',optionalForShort:true},
      {id:'e4',scene:'Il provino delle intenzioni',text:'{{name}} chiese a ciascuna voce che cosa stesse cercando di ottenere. La Critica rispose: “Voglio che tu faccia bene”. La Paura: “Voglio che tu non venga ferito”. La Curiosità: “Voglio scoprire”. Il Coraggio: “Voglio che tu non rinunci”. La Stanchezza alzò la mano: “Io vorrei soltanto una pausa”.',detail:'Le intenzioni non rendevano corretto ogni comportamento, ma permettevano di discutere con le voci invece di combatterle alla cieca.'},
      {id:'e5',scene:'Una scena reale',text:'Il teatro proiettò una situazione: {{name}} doveva presentare un lavoro davanti ad altre persone. La Critica gridò che non era abbastanza perfetto. La Paura suggerì di fingersi malato. La Curiosità voleva vedere che cosa sarebbe successo. {{name}} assegnò a ciascuna una battuta e poi scelse un piano: prepararsi, chiedere aiuto e accettare la possibilità di un piccolo errore.',detail:'Il Coraggio non cancellò la Paura. Le offrì un posto accanto, senza lasciarle decidere la direzione.'},
      {id:'e6',scene:'La voce che mancava',text:'Durante le prove, {{name}} notò una sedia vuota. Sullo schienale c’era scritto “Gentilezza verso di sé”. Quella voce non era mai stata invitata perché sembrava poco utile. Quando entrò, non disse “Andrà tutto benissimo”. Disse: “Puoi impegnarti senza trattarti male. Un errore non racconta tutto di te”.',detail:'La Critica abbassò il copione. Per la prima volta, poté offrire suggerimenti specifici invece di giudizi sull’intera persona.'},
      {id:'e7',scene:'Il cambio di regia',text:'Una campana annunciò che il vecchio regista stava tornando: era una figura chiamata Opinione degli Altri. Pretendeva che ogni scelta ottenesse approvazione. {{name}} ascoltò i suoi consigli, ma rifiutò di restituirgli il comando. «Puoi sederti in platea», disse. «Non puoi scrivere da solo il finale».',detail:'L’Opinione degli Altri protestò, poi accettò una poltrona laterale. Da lì poteva essere considerata senza occupare tutto il palco.'},
      {id:'e8',scene:'La prima rappresentazione',text:'Le porte del teatro si aprirono agli abitanti di {{world}}. Lo spettacolo raccontava una decisione difficile senza fingere che esistesse una risposta perfetta. Ogni voce entrava al momento giusto. Quando la Paura parlava, il pubblico capiva il rischio. Quando la Curiosità rispondeva, vedeva anche la possibilità. {{name}} dirigeva i passaggi.',detail:'Il pubblico non applaudì perché il protagonista era senza dubbi. Applaudì perché aveva imparato a muoversi insieme ai dubbi.',optionalForShort:true},
      {id:'e9',scene:'Il teatro portatile',text:'Dopo lo spettacolo, il palcoscenico si piegò fino a diventare un piccolo taccuino. Su ogni pagina c’era spazio per scrivere: “Quale voce parla?”, “Che cosa vuole proteggere?”, “Quanto volume le serve?”, “Chi deve rispondere?”. {{name}} lo mise in tasca.',detail:'Le voci non sarebbero sparite. Ma ora esisteva una regia capace di trasformare un litigio interno in una conversazione utile.',optionalForShort:true,optionalForMedium:true},
      {id:'e10',scene:'Il biglietto da regista',text:'Sul retro del biglietto di {{material}} comparve una frase: “Tu non sei una sola delle tue voci. Sei anche chi può ascoltarle e scegliere”. Tornando a casa, {{name}} sentì la Critica commentare un dettaglio, la Paura anticipare un problema e la Gentilezza rispondere. Nessuna voce vinse. Insieme prepararono la scena successiva.',detail:'Quella sera, il silenzio non fu l’assenza di pensieri. Fu la sensazione che ogni pensiero avesse finalmente un posto e un limite.'}
    ]
  },
  {
    id:'v2-8-10-scoperta-laboratorio', age:'8-10', family:'scoperta', adaptableToWorld:true, worlds:['*'],
    styles:['mysterious','adventurous'], moods:['Curiosità e voglia di scoprire','Momento tranquillo'], support:['Stimolare curiosità'],
    title:'{{name}} e il laboratorio delle cose quasi vere',
    subtitle:'Un’indagine tra ipotesi, prove e idee affascinanti che potrebbero essere sbagliate.',
    companion:'', cover:{icon:'🧪',art:'space'}, treasure:'la lente delle prove in {{material}}',
    ritual:'Scegliete un’affermazione curiosa e dividete un foglio in tre colonne: cosa sappiamo, cosa immaginiamo, come potremmo verificare.',
    activity:'Inventate un esperimento sicuro con acqua, carta o luce e annotate previsione, risultato e nuova domanda.',
    pages:[
      {id:'s1',scene:'La macchina delle certezze',text:'Sotto {{landmark}} sorgeva un laboratorio famoso per una macchina capace di rispondere a qualsiasi domanda. Quando {{name}} arrivò, la macchina stampava frasi sicure: “Domani pioverà caramello”, “Le ombre pensano”, “Il suono pesa più della luce”. Gli abitanti di {{world}} prendevano ogni biglietto come verità.',detail:'La macchina parlava con una voce convincente e aggiungeva numeri, grafici e timbri. Sembrava precisa anche quando le sue affermazioni erano impossibili.'},
      {id:'s2',scene:'Una previsione affascinante',text:'Il biglietto destinato a {{name}} diceva: “Dentro {{threshold}} esiste una stanza che esaudisce il desiderio più forte”. {{companion}} voleva correre a cercarla. {{name}} era incuriosito, ma chiese: «Come lo sappiamo? Qualcuno l’ha vista? Che cosa significherebbe “esaudire”?». La macchina ripeté la frase senza fornire prove.',detail:'Una spiegazione poteva essere emozionante e restare comunque non verificata. Il desiderio di crederci non era una prova a favore.'},
      {id:'s3',scene:'Il reparto delle ipotesi',text:'Una scienziata del laboratorio mostrò scaffali pieni di barattoli etichettati “forse”. Ogni ipotesi era conservata lì finché non veniva confrontata con osservazioni. «Le ipotesi non sono bugie», spiegò. «Sono idee che accettano di essere messe alla prova». {{name}} decise di trattare la stanza dei desideri come un’ipotesi.',detail:'Scrissero tre possibilità: la stanza esiste davvero; è un fenomeno naturale interpretato male; qualcuno ha inventato la storia. Ogni possibilità richiedeva prove diverse.',optionalForShort:true},
      {id:'s4',scene:'Le tracce selezionate',text:'Vicino a {{threshold}} trovarono segni luminosi che sembravano confermare la macchina. {{companion}} li indicò con entusiasmo. {{name}}, però, cercò anche elementi contrari: polvere non spostata, ragnatele intatte, nessuna impronta recente. Le prove favorevoli erano visibili; quelle contrarie richiedevano attenzione.',detail:'Cercare soltanto ciò che conferma un’idea rende qualunque storia più credibile. Una buona indagine cerca anche ciò che potrebbe smentirla.'},
      {id:'s5',scene:'L’esperimento del desiderio',text:'Costruirono un test. Tre persone avrebbero attraversato la soglia pensando a desideri diversi, senza dirli agli osservatori. Se la stanza funzionava, i risultati avrebbero dovuto corrispondere in modo riconoscibile. Invece ognuno interpretò le stesse luci e gli stessi suoni secondo ciò che sperava di trovare.',detail:'La stanza non leggeva i desideri: offriva segnali ambigui che la mente completava. Era una scoperta interessante, anche se diversa dalla promessa iniziale.'},
      {id:'s6',scene:'La macchina si difende',text:'Quando {{name}} presentò i risultati, la macchina stampò: “L’esperimento è fallito perché non avete creduto abbastanza”. Era una risposta impossibile da controllare: qualunque esito poteva essere usato per salvare l’affermazione. La scienziata spiegò che un’idea seria deve prevedere che cosa la farebbe risultare sbagliata.',detail:'Se nessun risultato può cambiare una convinzione, non stiamo più testando: stiamo proteggendo l’idea dalle informazioni.'},
      {id:'s7',scene:'Il nucleo della macchina',text:'Aprendo il pannello posteriore, scoprirono che la macchina combinava frammenti di vecchi libri, leggende e dati casuali. Non distingueva tra fonti affidabili e racconti. Produceva frasi plausibili, non conoscenza. {{name}} propose di aggiungere citazioni, livelli di certezza e un avviso quando mancavano prove.',detail:'La macchina poteva restare utile per generare domande e possibilità, purché smettesse di presentarle tutte come fatti.'},
      {id:'s8',scene:'La conferenza pubblica',text:'Gli abitanti non furono contenti di sapere che alcuni biglietti erano sbagliati. Qualcuno accusò {{name}} di rovinare la meraviglia. {{name}} rispose che la meraviglia non dipende dalla certezza: una domanda aperta può essere più affascinante di una risposta inventata. Mostrò il vero fenomeno della stanza, capace di rivelare come interpretiamo i segnali.',detail:'Il pubblico iniziò a fare domande più precise. La delusione iniziale lasciò spazio a una curiosità meno facile da ingannare.',optionalForShort:true},
      {id:'s9',scene:'Il nuovo laboratorio',text:'La macchina fu rinominata “Generatore di Ipotesi”. Ogni biglietto riportava tre sezioni: idea, prove disponibili, modo per verificare. Alcune frasi venivano confermate, altre corrette, altre restavano in sospeso. {{place}} divenne famoso non per avere sempre ragione, ma per mostrare come cambia una spiegazione.',detail:'Sbagliare non era più una vergogna da nascondere. Era un passaggio documentato, utile a chi sarebbe arrivato dopo.',optionalForShort:true,optionalForMedium:true},
      {id:'s10',scene:'La lente delle prove',text:'La scienziata regalò a {{name}} una lente di {{material}} con tre incisioni: “Fonte?”, “Prova?”, “Alternativa?”. Non rendeva automaticamente vere o false le affermazioni. Ricordava di rallentare prima di condividere o credere. Tornando a casa, {{name}} conservò anche il primo biglietto: non come verità, ma come esempio di una domanda iniziata bene e conclusa meglio.',detail:'La stanza dei desideri non esaudiva desideri. Aveva però offerto qualcosa di reale: la possibilità di imparare come la mente costruisce significati e come le prove possono aiutarla a correggersi.'}
    ]
  }
];
