window.FABLEA_STORIES_V2_8_10 = [
  {
    "id": "v2-8-10-avventura",
    "age": "8-10",
    "family": "avventura",
    "worlds": [
      "Magia"
    ],
    "styles": [
      "adventurous"
    ],
    "moods": [
      "Curiosità e voglia di scoprire",
      "Tanta energia",
      "Allegria"
    ],
    "support": [
      "Stimolare curiosità"
    ],
    "title": "{{name}} e la porta delle orme",
    "subtitle": "Un racconto avventura nel mondo Magia.",
    "companion": "Nilo il drago tascabile",
    "cover": {
      "icon": "🦖",
      "art": "forest"
    },
    "pages": [
      {
        "id": "p1",
        "scene": "Scena 1",
        "text": "{{name}} entra in Magia quando una porta sembra respirare. Nilo il drago tascabile saluta: “Questo mondo conosce il tuo nome e oggi chiede una scelta vera.” Nel dettaglio 8-10-avventura-Magia-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": false,
        "extendedForLong": "{{name}} entra in Magia quando una porta sembra respirare. Nilo il drago tascabile saluta: “Questo mondo conosce il tuo nome e oggi chiede una scelta vera.” Nel dettaglio 8-10-avventura-Magia-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p2",
        "scene": "Scena 2",
        "text": "Il desiderio nasce da una scintilla scomparsa. Ci sono odore di pioggia, luce sulle mani e un sentiero che cambia se qualcuno ascolta. Nel dettaglio 8-10-avventura-Magia-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": false,
        "extendedForLong": "Il desiderio nasce da una scintilla scomparsa. Ci sono odore di pioggia, luce sulle mani e un sentiero che cambia se qualcuno ascolta. Nel dettaglio 8-10-avventura-Magia-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p3",
        "scene": "Scena 3",
        "text": "Un custode con tasche piene di semi racconta il problema: “La risposta non basta. Serve capire che cosa protegge questa storia.” Nel dettaglio 8-10-avventura-Magia-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": false,
        "extendedForLong": "Un custode con tasche piene di semi racconta il problema: “La risposta non basta. Serve capire che cosa protegge questa storia.” Nel dettaglio 8-10-avventura-Magia-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p4",
        "scene": "Scena 4",
        "text": "La scena si apre in tre tracce: una lucida, una storta, una quasi invisibile. {{name}} sceglie quella più fragile e il mondo si avvicina. Nel dettaglio 8-10-avventura-Magia-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": false,
        "extendedForLong": "La scena si apre in tre tracce: una lucida, una storta, una quasi invisibile. {{name}} sceglie quella più fragile e il mondo si avvicina. Nel dettaglio 8-10-avventura-Magia-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p5",
        "scene": "Scena 5",
        "text": "L'ostacolo è un ponte di parole difficili. Ogni asse ripete “non riesco”; ogni respiro lo trasforma in “posso provare piano”. Nel dettaglio 8-10-avventura-Magia-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": false,
        "extendedForLong": "L'ostacolo è un ponte di parole difficili. Ogni asse ripete “non riesco”; ogni respiro lo trasforma in “posso provare piano”. Nel dettaglio 8-10-avventura-Magia-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p6",
        "scene": "Scena 6",
        "text": "La scelta produce conseguenze. Una finestra si accende, un abitante esce dal nascondiglio e ringrazia perché il coraggio è diventato cura. Nel dettaglio 8-10-avventura-Magia-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": true,
        "extendedForLong": "La scelta produce conseguenze. Una finestra si accende, un abitante esce dal nascondiglio e ringrazia perché il coraggio è diventato cura. Nel dettaglio 8-10-avventura-Magia-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p7",
        "scene": "Scena 7",
        "text": "La scintilla riappare dentro acqua ferma. Si vede solo restando presenti. {{name}} la raccoglie e il colore diventa unico. Nel dettaglio 8-10-avventura-Magia-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": true,
        "extendedForLong": "La scintilla riappare dentro acqua ferma. Si vede solo restando presenti. {{name}} la raccoglie e il colore diventa unico. Nel dettaglio 8-10-avventura-Magia-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p8",
        "scene": "Scena 8",
        "text": "Per tornare serve un rituale: nominare una cosa vista, una cosa sentita e una promessa minuscola da lasciare al luogo. Nel dettaglio 8-10-avventura-Magia-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": true,
        "extendedForLong": "Per tornare serve un rituale: nominare una cosa vista, una cosa sentita e una promessa minuscola da lasciare al luogo. Nel dettaglio 8-10-avventura-Magia-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p9",
        "scene": "Scena 9",
        "text": "A casa resta un tesoro caldo. Non spiega tutto, ma riapre la memoria del viaggio, del compagno e della scelta fatta. Nel dettaglio 8-10-avventura-Magia-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": true,
        "extendedForLong": "A casa resta un tesoro caldo. Non spiega tutto, ma riapre la memoria del viaggio, del compagno e della scelta fatta. Nel dettaglio 8-10-avventura-Magia-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-avventura-Magia-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      }
    ],
    "treasure": "Pietra del avventura",
    "ritual": "Rituale del avventura: tre respiri e una parola",
    "activity": "Disegna il segno del Magia e ricostruisci la scelta centrale con tre oggetti."
  },
  {
    "id": "v2-8-10-calma-sera",
    "age": "8-10",
    "family": "calma-sera",
    "worlds": [
      "Foresta"
    ],
    "styles": [
      "calm"
    ],
    "moods": [
      "Momento tranquillo",
      "Stanchezza"
    ],
    "support": [
      "Calmare la sera"
    ],
    "title": "{{name}} e il faro quieto",
    "subtitle": "Un racconto calma sera nel mondo Foresta.",
    "companion": "Marea la balena-lanterna",
    "cover": {
      "icon": "🌊",
      "art": "ocean"
    },
    "pages": [
      {
        "id": "p1",
        "scene": "Scena 1",
        "text": "{{name}} entra in Foresta quando una porta sembra respirare. Nilo il drago tascabile saluta: “Questo mondo conosce il tuo nome e oggi chiede una scelta vera.” Nel dettaglio 8-10-calma-sera-Foresta-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": false,
        "extendedForLong": "{{name}} entra in Foresta quando una porta sembra respirare. Nilo il drago tascabile saluta: “Questo mondo conosce il tuo nome e oggi chiede una scelta vera.” Nel dettaglio 8-10-calma-sera-Foresta-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p2",
        "scene": "Scena 2",
        "text": "Il desiderio nasce da una scintilla scomparsa. Ci sono odore di pioggia, luce sulle mani e un sentiero che cambia se qualcuno ascolta. Nel dettaglio 8-10-calma-sera-Foresta-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": false,
        "extendedForLong": "Il desiderio nasce da una scintilla scomparsa. Ci sono odore di pioggia, luce sulle mani e un sentiero che cambia se qualcuno ascolta. Nel dettaglio 8-10-calma-sera-Foresta-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p3",
        "scene": "Scena 3",
        "text": "Un custode con tasche piene di semi racconta il problema: “La risposta non basta. Serve capire che cosa protegge questa storia.” Nel dettaglio 8-10-calma-sera-Foresta-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": false,
        "extendedForLong": "Un custode con tasche piene di semi racconta il problema: “La risposta non basta. Serve capire che cosa protegge questa storia.” Nel dettaglio 8-10-calma-sera-Foresta-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p4",
        "scene": "Scena 4",
        "text": "La scena si apre in tre tracce: una lucida, una storta, una quasi invisibile. {{name}} sceglie quella più fragile e il mondo si avvicina. Nel dettaglio 8-10-calma-sera-Foresta-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": false,
        "extendedForLong": "La scena si apre in tre tracce: una lucida, una storta, una quasi invisibile. {{name}} sceglie quella più fragile e il mondo si avvicina. Nel dettaglio 8-10-calma-sera-Foresta-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p5",
        "scene": "Scena 5",
        "text": "L'ostacolo è un ponte di parole difficili. Ogni asse ripete “non riesco”; ogni respiro lo trasforma in “posso provare piano”. Nel dettaglio 8-10-calma-sera-Foresta-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": false,
        "extendedForLong": "L'ostacolo è un ponte di parole difficili. Ogni asse ripete “non riesco”; ogni respiro lo trasforma in “posso provare piano”. Nel dettaglio 8-10-calma-sera-Foresta-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p6",
        "scene": "Scena 6",
        "text": "La scelta produce conseguenze. Una finestra si accende, un abitante esce dal nascondiglio e ringrazia perché il coraggio è diventato cura. Nel dettaglio 8-10-calma-sera-Foresta-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": true,
        "extendedForLong": "La scelta produce conseguenze. Una finestra si accende, un abitante esce dal nascondiglio e ringrazia perché il coraggio è diventato cura. Nel dettaglio 8-10-calma-sera-Foresta-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p7",
        "scene": "Scena 7",
        "text": "La scintilla riappare dentro acqua ferma. Si vede solo restando presenti. {{name}} la raccoglie e il colore diventa unico. Nel dettaglio 8-10-calma-sera-Foresta-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": true,
        "extendedForLong": "La scintilla riappare dentro acqua ferma. Si vede solo restando presenti. {{name}} la raccoglie e il colore diventa unico. Nel dettaglio 8-10-calma-sera-Foresta-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p8",
        "scene": "Scena 8",
        "text": "Per tornare serve un rituale: nominare una cosa vista, una cosa sentita e una promessa minuscola da lasciare al luogo. Nel dettaglio 8-10-calma-sera-Foresta-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": true,
        "extendedForLong": "Per tornare serve un rituale: nominare una cosa vista, una cosa sentita e una promessa minuscola da lasciare al luogo. Nel dettaglio 8-10-calma-sera-Foresta-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p9",
        "scene": "Scena 9",
        "text": "A casa resta un tesoro caldo. Non spiega tutto, ma riapre la memoria del viaggio, del compagno e della scelta fatta. Nel dettaglio 8-10-calma-sera-Foresta-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": true,
        "extendedForLong": "A casa resta un tesoro caldo. Non spiega tutto, ma riapre la memoria del viaggio, del compagno e della scelta fatta. Nel dettaglio 8-10-calma-sera-Foresta-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-calma-sera-Foresta-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      }
    ],
    "treasure": "Conchiglia del calma-sera",
    "ritual": "Rituale del calma-sera: tre respiri e una parola",
    "activity": "Disegna il segno del Foresta e ricostruisci la scelta centrale con tre oggetti."
  },
  {
    "id": "v2-8-10-emozioni",
    "age": "8-10",
    "family": "emozioni",
    "worlds": [
      "Regni e castelli"
    ],
    "styles": [
      "emotional"
    ],
    "moods": [
      "Una giornata difficile",
      "Un po’ di rabbia",
      "Una piccola paura"
    ],
    "support": [
      "Aiutare con le emozioni"
    ],
    "title": "{{name}} e il nodo parlante",
    "subtitle": "Un racconto emozioni nel mondo Regni e castelli.",
    "companion": "Pip la volpe con gli occhiali",
    "cover": {
      "icon": "🦊",
      "art": "castle"
    },
    "pages": [
      {
        "id": "p1",
        "scene": "Scena 1",
        "text": "{{name}} entra in Regni e castelli quando una porta sembra respirare. Nilo il drago tascabile saluta: “Questo mondo conosce il tuo nome e oggi chiede una scelta vera.” Nel dettaglio 8-10-emozioni-Regni e castelli-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": false,
        "extendedForLong": "{{name}} entra in Regni e castelli quando una porta sembra respirare. Nilo il drago tascabile saluta: “Questo mondo conosce il tuo nome e oggi chiede una scelta vera.” Nel dettaglio 8-10-emozioni-Regni e castelli-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p2",
        "scene": "Scena 2",
        "text": "Il desiderio nasce da una scintilla scomparsa. Ci sono odore di pioggia, luce sulle mani e un sentiero che cambia se qualcuno ascolta. Nel dettaglio 8-10-emozioni-Regni e castelli-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": false,
        "extendedForLong": "Il desiderio nasce da una scintilla scomparsa. Ci sono odore di pioggia, luce sulle mani e un sentiero che cambia se qualcuno ascolta. Nel dettaglio 8-10-emozioni-Regni e castelli-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p3",
        "scene": "Scena 3",
        "text": "Un custode con tasche piene di semi racconta il problema: “La risposta non basta. Serve capire che cosa protegge questa storia.” Nel dettaglio 8-10-emozioni-Regni e castelli-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": false,
        "extendedForLong": "Un custode con tasche piene di semi racconta il problema: “La risposta non basta. Serve capire che cosa protegge questa storia.” Nel dettaglio 8-10-emozioni-Regni e castelli-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p4",
        "scene": "Scena 4",
        "text": "La scena si apre in tre tracce: una lucida, una storta, una quasi invisibile. {{name}} sceglie quella più fragile e il mondo si avvicina. Nel dettaglio 8-10-emozioni-Regni e castelli-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": false,
        "extendedForLong": "La scena si apre in tre tracce: una lucida, una storta, una quasi invisibile. {{name}} sceglie quella più fragile e il mondo si avvicina. Nel dettaglio 8-10-emozioni-Regni e castelli-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p5",
        "scene": "Scena 5",
        "text": "L'ostacolo è un ponte di parole difficili. Ogni asse ripete “non riesco”; ogni respiro lo trasforma in “posso provare piano”. Nel dettaglio 8-10-emozioni-Regni e castelli-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": false,
        "extendedForLong": "L'ostacolo è un ponte di parole difficili. Ogni asse ripete “non riesco”; ogni respiro lo trasforma in “posso provare piano”. Nel dettaglio 8-10-emozioni-Regni e castelli-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p6",
        "scene": "Scena 6",
        "text": "La scelta produce conseguenze. Una finestra si accende, un abitante esce dal nascondiglio e ringrazia perché il coraggio è diventato cura. Nel dettaglio 8-10-emozioni-Regni e castelli-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": true,
        "extendedForLong": "La scelta produce conseguenze. Una finestra si accende, un abitante esce dal nascondiglio e ringrazia perché il coraggio è diventato cura. Nel dettaglio 8-10-emozioni-Regni e castelli-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p7",
        "scene": "Scena 7",
        "text": "La scintilla riappare dentro acqua ferma. Si vede solo restando presenti. {{name}} la raccoglie e il colore diventa unico. Nel dettaglio 8-10-emozioni-Regni e castelli-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": true,
        "extendedForLong": "La scintilla riappare dentro acqua ferma. Si vede solo restando presenti. {{name}} la raccoglie e il colore diventa unico. Nel dettaglio 8-10-emozioni-Regni e castelli-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p8",
        "scene": "Scena 8",
        "text": "Per tornare serve un rituale: nominare una cosa vista, una cosa sentita e una promessa minuscola da lasciare al luogo. Nel dettaglio 8-10-emozioni-Regni e castelli-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": true,
        "extendedForLong": "Per tornare serve un rituale: nominare una cosa vista, una cosa sentita e una promessa minuscola da lasciare al luogo. Nel dettaglio 8-10-emozioni-Regni e castelli-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p9",
        "scene": "Scena 9",
        "text": "A casa resta un tesoro caldo. Non spiega tutto, ma riapre la memoria del viaggio, del compagno e della scelta fatta. Nel dettaglio 8-10-emozioni-Regni e castelli-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": true,
        "extendedForLong": "A casa resta un tesoro caldo. Non spiega tutto, ma riapre la memoria del viaggio, del compagno e della scelta fatta. Nel dettaglio 8-10-emozioni-Regni e castelli-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-emozioni-Regni e castelli-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      }
    ],
    "treasure": "Chiave del emozioni",
    "ritual": "Rituale del emozioni: tre respiri e una parola",
    "activity": "Disegna il segno del Regni e castelli e ricostruisci la scelta centrale con tre oggetti."
  },
  {
    "id": "v2-8-10-scoperta",
    "age": "8-10",
    "family": "scoperta",
    "worlds": [
      "Misteri e scoperte"
    ],
    "styles": [
      "mysterious"
    ],
    "moods": [
      "Curiosità e voglia di scoprire",
      "Tanta energia",
      "Allegria"
    ],
    "support": [
      "Stimolare curiosità"
    ],
    "title": "{{name}} e la mappa gentile",
    "subtitle": "Un racconto scoperta nel mondo Misteri e scoperte.",
    "companion": "Astra la lucciola delle orbite",
    "cover": {
      "icon": "🚀",
      "art": "space"
    },
    "pages": [
      {
        "id": "p1",
        "scene": "Scena 1",
        "text": "{{name}} entra in Misteri e scoperte quando una porta sembra respirare. Nilo il drago tascabile saluta: “Questo mondo conosce il tuo nome e oggi chiede una scelta vera.” Nel dettaglio 8-10-scoperta-Misteri e scoperte-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": false,
        "extendedForLong": "{{name}} entra in Misteri e scoperte quando una porta sembra respirare. Nilo il drago tascabile saluta: “Questo mondo conosce il tuo nome e oggi chiede una scelta vera.” Nel dettaglio 8-10-scoperta-Misteri e scoperte-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-0, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p2",
        "scene": "Scena 2",
        "text": "Il desiderio nasce da una scintilla scomparsa. Ci sono odore di pioggia, luce sulle mani e un sentiero che cambia se qualcuno ascolta. Nel dettaglio 8-10-scoperta-Misteri e scoperte-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": false,
        "extendedForLong": "Il desiderio nasce da una scintilla scomparsa. Ci sono odore di pioggia, luce sulle mani e un sentiero che cambia se qualcuno ascolta. Nel dettaglio 8-10-scoperta-Misteri e scoperte-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-1, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p3",
        "scene": "Scena 3",
        "text": "Un custode con tasche piene di semi racconta il problema: “La risposta non basta. Serve capire che cosa protegge questa storia.” Nel dettaglio 8-10-scoperta-Misteri e scoperte-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": false,
        "extendedForLong": "Un custode con tasche piene di semi racconta il problema: “La risposta non basta. Serve capire che cosa protegge questa storia.” Nel dettaglio 8-10-scoperta-Misteri e scoperte-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-2, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p4",
        "scene": "Scena 4",
        "text": "La scena si apre in tre tracce: una lucida, una storta, una quasi invisibile. {{name}} sceglie quella più fragile e il mondo si avvicina. Nel dettaglio 8-10-scoperta-Misteri e scoperte-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": false,
        "extendedForLong": "La scena si apre in tre tracce: una lucida, una storta, una quasi invisibile. {{name}} sceglie quella più fragile e il mondo si avvicina. Nel dettaglio 8-10-scoperta-Misteri e scoperte-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-3, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p5",
        "scene": "Scena 5",
        "text": "L'ostacolo è un ponte di parole difficili. Ogni asse ripete “non riesco”; ogni respiro lo trasforma in “posso provare piano”. Nel dettaglio 8-10-scoperta-Misteri e scoperte-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": false,
        "extendedForLong": "L'ostacolo è un ponte di parole difficili. Ogni asse ripete “non riesco”; ogni respiro lo trasforma in “posso provare piano”. Nel dettaglio 8-10-scoperta-Misteri e scoperte-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-4, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p6",
        "scene": "Scena 6",
        "text": "La scelta produce conseguenze. Una finestra si accende, un abitante esce dal nascondiglio e ringrazia perché il coraggio è diventato cura. Nel dettaglio 8-10-scoperta-Misteri e scoperte-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": true,
        "extendedForLong": "La scelta produce conseguenze. Una finestra si accende, un abitante esce dal nascondiglio e ringrazia perché il coraggio è diventato cura. Nel dettaglio 8-10-scoperta-Misteri e scoperte-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-5, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p7",
        "scene": "Scena 7",
        "text": "La scintilla riappare dentro acqua ferma. Si vede solo restando presenti. {{name}} la raccoglie e il colore diventa unico. Nel dettaglio 8-10-scoperta-Misteri e scoperte-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": true,
        "extendedForLong": "La scintilla riappare dentro acqua ferma. Si vede solo restando presenti. {{name}} la raccoglie e il colore diventa unico. Nel dettaglio 8-10-scoperta-Misteri e scoperte-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-6, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p8",
        "scene": "Scena 8",
        "text": "Per tornare serve un rituale: nominare una cosa vista, una cosa sentita e una promessa minuscola da lasciare al luogo. Nel dettaglio 8-10-scoperta-Misteri e scoperte-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": true,
        "extendedForLong": "Per tornare serve un rituale: nominare una cosa vista, una cosa sentita e una promessa minuscola da lasciare al luogo. Nel dettaglio 8-10-scoperta-Misteri e scoperte-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-7, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      },
      {
        "id": "p9",
        "scene": "Scena 9",
        "text": "A casa resta un tesoro caldo. Non spiega tutto, ma riapre la memoria del viaggio, del compagno e della scelta fatta. Nel dettaglio 8-10-scoperta-Misteri e scoperte-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.",
        "optionalForShort": true,
        "extendedForLong": "A casa resta un tesoro caldo. Non spiega tutto, ma riapre la memoria del viaggio, del compagno e della scelta fatta. Nel dettaglio 8-10-scoperta-Misteri e scoperte-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile. Nel dettaglio 8-10-scoperta-Misteri e scoperte-8, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile."
      }
    ],
    "treasure": "Stella del scoperta",
    "ritual": "Rituale del scoperta: tre respiri e una parola",
    "activity": "Disegna il segno del Misteri e scoperte e ricostruisci la scelta centrale con tre oggetti."
  }
];
