(function(global){
  'use strict';

  const extensions = {
    'v2-2-4-avventura-campanella': [
      {id:'a3b',after:'a3',includeInShort:true,includeInMedium:true,scene:'Il coro della pozzanghera',text:'Dalla pozzanghera uscirono tre ranocchie. Una faceva «plip», una «plop» e la più piccola soltanto «p». {{name}} batté le mani seguendo il loro ritmo. La campanella dondolò felice e conservò quel piccolo coro, perché anche un suono minuscolo può far parte di una musica grande.'},
      {id:'a7b',after:'a7',scene:'La prova del silenzio',text:'Prima della festa, la campanella chiese un momento senza rumori. {{name}} ascoltò il vento, il proprio respiro e un fruscio lontano. Poi fece suonare la campanella una sola volta. Il suo «din» sembrò più chiaro, perché aveva trovato uno spazio libero in cui farsi sentire.'}
    ],
    'v2-2-4-calma-casa-piano': [
      {id:'c3b',after:'c3',includeInShort:true,includeInMedium:true,scene:'I gradini fanno piano',text:'Anche la scala voleva imparare. Ogni gradino faceva un rumore diverso: toc, tac, tuc. {{name}} salì appoggiando prima la punta e poi tutto il piede. Toc diventò toc-piano, tac diventò tac-piano. In cima, la casa sembrava già un poco più assonnata.'},
      {id:'c7b',after:'c7',scene:'Il corridoio degli sbadigli',text:'Nel corridoio comparvero sbadigli di tutte le forme. Uno era lungo, uno tondo, uno così piccolo da sembrare un sospiro. {{name}} ne scelse uno e lo lasciò passare dalla bocca senza trattenerlo. La casa lo imitò, e perfino le porte smisero di cigolare.'}
    ],
    'v2-2-4-emozioni-temporale': [
      {id:'e2b',after:'e2',includeInShort:true,includeInMedium:true,scene:'La coperta della rabbia',text:'Il tuono rosso non voleva essere cacciato. Voleva dire che qualcosa aveva fatto male. {{name}} gli preparò una coperta e gli lasciò spazio per brontolare senza colpire nessuno. Dopo un poco il tuono diventò più basso e riuscì a spiegare che cosa lo aveva acceso.'},
      {id:'e7b',after:'e7',scene:'Le nuvole si salutano',text:'Prima di andare via, Rabbia, Tristezza e Paura si misero in fila. Ognuna promise di bussare, la prossima volta, invece di entrare tutte insieme. {{name}} promise di ascoltarle e di chiedere aiuto quando il temporale fosse diventato troppo grande da tenere da solo.'}
    ],
    'v2-2-4-scoperta-luce': [
      {id:'s2b',after:'s2',includeInShort:true,includeInMedium:true,scene:'La formica esploratrice',text:'Una formica arrivò vicino al seme e lo annusò. Per lei quel puntino era grande come una casa. {{name}} la seguì con lo sguardo e scoprì un sentiero fatto di granelli, fili d’erba e briciole. Il mondo cambiava misura a seconda di chi lo guardava.'},
      {id:'s7b',after:'s7',scene:'La notte dei semi',text:'Quando arrivò il buio, i semi luminosi non si spensero. Crearono un cielo sotto i piedi. {{name}} camminò lentamente tra quelle stelle di terra, facendo attenzione a non calpestarle. Ogni luce indicava una cosa piccola che stava crescendo senza fare rumore.'}
    ],

    'v2-5-7-avventura-tre-impronte': [
      {id:'a3x',after:'a3',includeInShort:true,includeInMedium:true,scene:'Il masso che rotolava indietro',text:'Il masso più grande continuava a tornare al punto di partenza. {{name}} smise di spingere e studiò la pendenza. Con una pietra piatta costruì un fermo, mentre {{companion}} cercava un ramo robusto da usare come leva. Non servì diventare più forti: servì cambiare metodo e coordinare i movimenti.'},
      {id:'a6x',after:'a6',includeInShort:true,includeInMedium:true,scene:'Provare una nuova andatura',text:'La giovane creatura invitò {{name}} a imitare le sue tre andature. Il passo pesante dava stabilità, quello leggero permetteva di cambiare direzione, quello incerto sentiva vibrazioni che gli altri ignoravano. All’inizio sembrò buffo, poi {{name}} capì che ogni modo di muoversi offriva informazioni diverse sul terreno.'},
      {id:'a8x',after:'a8',scene:'La notte al riparo',text:'La frana costrinse la squadra a fermarsi fino al mattino. Costruirono un riparo con rami e teli, divisero l’acqua e organizzarono turni di ascolto. Intorno al fuoco, ognuno raccontò una capacità che un tempo aveva considerato strana. Le storie trasformarono l’attesa in una parte essenziale del viaggio.'}
    ],
    'v2-5-7-calma-faro-respiri': [
      {id:'c3x',after:'c3',includeInShort:true,includeInMedium:true,scene:'La scala dei cinque sensi',text:'Per salire senza farsi trascinare dalla fretta, {{name}} osservò una cosa per ogni senso: la parete fredda, il profumo di {{scent}}, il rumore di {{sound}}, il colore della luce e il sapore dell’aria salata. Arrivare in cima richiese più tempo, ma la mente smise di correre avanti.'},
      {id:'c6x',after:'c6',includeInShort:true,includeInMedium:true,scene:'Il turno condiviso',text:'Il guardiano preparò una tabella con turni brevi. Nessuno avrebbe dovuto controllare il faro per tutta la notte da solo. Gli abitanti scelsero orari compatibili con il proprio riposo e lasciarono istruzioni semplici per chi veniva dopo. La responsabilità diventò più sicura quando smise di pesare su una sola persona.'},
      {id:'c8x',after:'c8',scene:'La barca che seguiva il ritmo',text:'Una barca apparve lontano e regolò la rotta sui passaggi lenti del faro. Il capitano ringraziò con una luce verde: il segnale regolare era più facile da leggere di quello frenetico. Il guardiano vide che rallentare non diminuiva la precisione; la rendeva finalmente affidabile.'}
    ],
    'v2-5-7-emozioni-nodo-parole': [
      {id:'e3x',after:'e3',includeInShort:true,includeInMedium:true,scene:'La frase che comincia male',text:'Una voce provò a dire: «Tu fai sempre tutto sbagliato». Il nodo si strinse. {{name}} la aiutò a ripartire da un fatto concreto: «Quando hai preso il mio oggetto senza chiedere, mi sono arrabbiato». Il filo grigio cambiò forma, perché una situazione precisa può essere discussa senza trasformare l’altra persona in un problema intero.'},
      {id:'e6x',after:'e6',includeInShort:true,includeInMedium:true,scene:'Ascoltare la risposta',text:'Dopo aver detto una frase sincera, {{name}} dovette lasciare spazio alla risposta. Non era uguale a quella immaginata. L’altra voce ricordava alcuni dettagli in modo diverso e aveva un bisogno proprio. Ascoltare non significava rinunciare a ciò che {{name}} sentiva; significava aggiungere informazioni al nodo.'},
      {id:'e8x',after:'e8',scene:'Riparare senza cancellare',text:'Due amici portarono un filo spezzato. Chiedere scusa non bastava a farlo tornare identico, così decisero una piccola riparazione: restituire ciò che era stato preso, rispettare un confine e verificare dopo qualche giorno. Il segno della rottura restò visibile, ma il filo poteva di nuovo sostenere peso.'}
    ],
    'v2-5-7-scoperta-mappa-domande': [
      {id:'s3x',after:'s3',includeInShort:true,includeInMedium:true,scene:'La domanda osservabile',text:'La mappa chiese a {{name}} di trasformare “Perché questo posto è strano?” in qualcosa che si potesse osservare. {{name}} annotò: “Quali suoni cambiano dopo il tramonto?” e “Dove sono rivolte le impronte?”. Le nuove domande fecero comparire simboli precisi invece di una nebbia di supposizioni.'},
      {id:'s6x',after:'s6',includeInShort:true,includeInMedium:true,scene:'Due spiegazioni possibili',text:'Davanti a una luce intermittente, {{name}} formulò due ipotesi: qualcuno stava inviando un segnale, oppure una superficie rifletteva il sole. Cercò prove per entrambe. Quando una nuvola coprì il cielo e la luce sparì, la seconda spiegazione diventò più forte senza bisogno di deridere la prima.'},
      {id:'s8x',after:'s8',scene:'La domanda di chi non era presente',text:'La mappa mostrava soltanto i percorsi raccontati da chi aveva potuto viaggiare. {{name}} intervistò persone anziane, bambini piccoli e abitanti con difficoltà motorie. Le loro domande aggiunsero panchine, rampe, fonti d’acqua e sentieri meno ripidi. Una mappa migliore includeva esperienze che prima non erano state chieste.'}
    ],

    'v2-8-10-avventura-archivio-strade': [
      {id:'a3y',after:'a3',includeInShort:true,includeInMedium:true,scene:'Il registro delle strade fallite',text:'La rilegatrice mostrò un registro che il custode aveva nascosto. Conteneva sentieri chiusi dopo un solo incidente, deviazioni abbandonate perché nessuno aveva finanziato la manutenzione e percorsi giudicati inutili da persone che non li percorrevano. {{name}} capì che una strada può scomparire non perché non serva, ma perché chi decide non vede chi la usa.'},
      {id:'a5y',after:'a5',includeInShort:true,includeInMedium:true,scene:'La deviazione diventa rifugio',text:'Mentre tornavano dalla parete cieca, iniziò una pioggia improvvisa. La deviazione sbagliata offrì una rientranza asciutta e una cisterna dimenticata. Altri viaggiatori si unirono al riparo. Quello che non conduceva alla destinazione principale aveva una funzione diversa: proteggere, far incontrare e permettere di aspettare condizioni migliori.'},
      {id:'a7y',after:'a7',scene:'La strada contestata',text:'Uno dei rotoli attraversava un terreno importante per una comunità locale. Riaprirlo senza consultarli avrebbe accorciato il viaggio di molti, ma danneggiato luoghi di memoria. {{name}} convocò un incontro e scoprì un’alternativa più lunga che evitava l’area sensibile. Una mappa responsabile non misura soltanto distanza e velocità; registra anche conseguenze e diritti.'},
      {id:'a9y',after:'a9',scene:'Il primo viaggiatore smarrito',text:'Pochi giorni dopo la riapertura, un viaggiatore ignorò gli avvisi e si perse. I sostenitori della vecchia regola chiesero di richiudere tutto. {{name}} partecipò alla ricerca e poi analizzò l’accaduto: segnaletica poco chiara, nessun punto di check-in, previsioni del tempo assenti. Corressero il sistema invece di usare un errore come prova che ogni alternativa fosse pericolosa.'}
    ],
    'v2-8-10-calma-luci': [
      {id:'c3y',after:'c3',includeInShort:true,includeInMedium:true,scene:'Misurare invece di indovinare',text:'La custode prestò a {{name}} uno strumento che misurava quanta luce raggiungeva il cielo e le finestre. Alcune lampade considerate deboli disperdevano più luce di altre molto potenti ma ben orientate. I numeri non decidevano tutto, però permisero di confrontare soluzioni e di evitare discussioni basate soltanto sull’impressione.'},
      {id:'c5y',after:'c5',includeInShort:true,includeInMedium:true,scene:'La strada di chi torna tardi',text:'Un’infermiera spiegò che rientrava a casa quando le strade erano quasi vuote. Per lei alcune luci rappresentavano sicurezza reale. {{name}} percorse il tragitto insieme a lei e individuò incroci, fermate e passaggi che richiedevano illuminazione continua. Il progetto cambiò: meno luce inutile, più attenzione esattamente dove serviva.'},
      {id:'c7y',after:'c7',scene:'Il costo nascosto',text:'Ridurre gli sprechi liberò energia e denaro. Il consiglio decise di investirne una parte in lampade migliori e una parte in servizi notturni. La custode insistette perché i risparmi non diventassero una scusa per lasciare zone trascurate al buio. Una trasformazione sostenibile doveva migliorare insieme cielo, sicurezza e qualità degli spazi.'},
      {id:'c9y',after:'c9',scene:'Il festival dell’ombra',text:'Per celebrare il nuovo equilibrio, gli abitanti organizzarono un festival senza grandi fari. Usarono lanterne schermate, superfici riflettenti e percorsi segnati da luci basse. Artisti proiettarono ombre sulle mura e astronomi raccontarono costellazioni. La notte non era diventata assenza: offriva forme di creatività che la luminosità continua aveva cancellato.'}
    ],
    'v2-8-10-emozioni-teatro-voci': [
      {id:'e3y',after:'e3',includeInShort:true,includeInMedium:true,scene:'La voce del confronto',text:'Dalle quinte entrò una nuova attrice, il Confronto. Portava fotografie dei successi altrui e mostrava soltanto i momenti migliori. Ogni immagine faceva sembrare il lavoro di {{name}} insufficiente. La Gentilezza verso di sé chiese di aggiungere ciò che le fotografie non mostravano: tentativi, aiuti ricevuti, errori e condizioni diverse. Il confronto perse parte del suo potere quando smise di presentarsi come misura assoluta.'},
      {id:'e5y',after:'e5',includeInShort:true,includeInMedium:true,scene:'La prova che va male',text:'Durante una simulazione, {{name}} dimenticò una frase e rimase in silenzio. La Critica iniziò un monologo durissimo. Il Regista interruppe la scena e trasformò l’errore in prova tecnica: guardare gli appunti, respirare, riprendere dal punto successivo. La seconda esecuzione non fu perfetta, ma dimostrò che un blocco può essere gestito senza diventare una definizione personale.'},
      {id:'e7y',after:'e7',scene:'La voce della rabbia',text:'La Rabbia comparve con un tamburo. Era stanca di essere considerata soltanto pericolosa. Spiegò che segnalava confini violati e ingiustizie, ma ammise di aver spesso coperto altre voci con il proprio volume. {{name}} le assegnò un ruolo preciso: indicare che cosa non andava, poi lasciare a Ragione e Cura il compito di scegliere l’azione.'},
      {id:'e9y',after:'e9',scene:'Un copione che cambia',text:'Il taccuino mostrò che la stessa situazione produceva voci diverse a seconda di sonno, fame, compagnia e precedenti esperienze. {{name}} iniziò ad annotare il contesto, non soltanto il pensiero. Questo rese più facile riconoscere quando una voce descriveva un rischio reale e quando era amplificata dalla stanchezza o da una giornata già difficile.'}
    ],
    'v2-8-10-scoperta-laboratorio': [
      {id:'s3y',after:'s3',includeInShort:true,includeInMedium:true,scene:'Controllare la fonte',text:'La scienziata chiese alla macchina da dove provenisse una delle sue frasi. Il sistema indicò un libro di racconti, una tabella senza autore e una citazione tagliata. {{name}} cercò le fonti originali e scoprì che nessuna sosteneva davvero la conclusione stampata. Una frase può sembrare documentata anche quando i riferimenti sono decorativi o fuori contesto.'},
      {id:'s5y',after:'s5',includeInShort:true,includeInMedium:true,scene:'Ripetere la prova',text:'Un solo esperimento poteva contenere coincidenze. Un secondo gruppo ripeté il test senza conoscere il risultato precedente e ottenne osservazioni simili. Un terzo cambiò alcune condizioni per capire che cosa producesse le luci. La spiegazione diventò più affidabile non perché tutti fossero d’accordo in anticipo, ma perché procedure indipendenti convergevano.'},
      {id:'s7y',after:'s7',scene:'Il dato che non piace',text:'Una misurazione contraddiceva l’ipotesi preferita dalla scienziata. Per un momento fu tentata di considerarla un errore e basta. {{name}} propose di controllare lo strumento, ripetere il test e conservare comunque il risultato. L’anomalia rivelò una variabile trascurata. Proteggere i dati scomodi permise alla teoria di diventare più completa.'},
      {id:'s9y',after:'s9',scene:'Spiegare l’incertezza',text:'Il nuovo laboratorio doveva comunicare risultati senza trasformare prudenza in debolezza. Prepararono etichette diverse: ben verificato, probabile, possibile, non sostenuto. Gli abitanti impararono che “non sappiamo ancora” non equivale a “qualunque risposta vale”. Anche l’incertezza può essere descritta con precisione e aggiornata quando arrivano nuove prove.'}
    ],

    'v2-11-12-avventura-citta-nomi': [
      {id:'a3z',after:'a3',includeInShort:true,includeInMedium:true,scene:'Il quartiere che non compariva',text:'Sovrapponendo le mappe, {{name}} notò un quartiere presente soltanto nei racconti di chi aveva cambiato spesso definizione. Lì vivevano persone considerate incoerenti dal sistema: un atleta appassionato di poesia, una leader che aveva bisogno di solitudine, un ragazzo brillante in alcune materie e in difficoltà in altre. Le strade del quartiere non seguivano categorie, ma connessioni tra interessi, bisogni e relazioni. Il luogo dimostrava che la complessità non impedisce di orientarsi; richiede mappe capaci di rappresentarla.'},
      {id:'a5z',after:'a5',includeInShort:true,includeInMedium:true,scene:'Il prezzo della coerenza',text:'Una musicista raccontò di aver rifiutato un corso scientifico perché tutti la conoscevano come “quella creativa”. Aveva temuto che cambiare interesse rendesse falso ciò che era stata prima. {{name}} le chiese se una nuova stanza cancella le stanze già costruite. La donna sorrise e mostrò strumenti musicali modificati grazie a conoscenze di fisica. Le identità precedenti non erano state smentite: avevano fornito materiali a quella successiva.'},
      {id:'a7z',after:'a7',includeInShort:true,includeInMedium:true,scene:'La prova dello sguardo altrui',text:'Nel percorso comparve una sala piena di persone che formulavano giudizi rapidi su {{name}}. Alcuni erano positivi, altri ingiusti, molti basati su pochi dettagli. Per uscire non bisognava convincerli tutti, ma distinguere tra feedback utile, preferenza personale e proiezione. {{name}} raccolse le osservazioni specifiche, lasciò a terra le etichette assolute e accettò che una parte dell’immagine pubblica sarebbe rimasta fuori dal proprio controllo.'},
      {id:'a8z',after:'a8',scene:'La persona dietro la maschera',text:'La figura che aveva rubato la targa si rivelò un ex funzionario dell’Ufficio dei Nomi. Per anni aveva assegnato definizioni e poi era stato classificato come “inaffidabile” dopo aver messo in dubbio il sistema. Non cercava di distruggere la città: voleva dimostrare quanto le istituzioni dipendessero da etichette che fingevano di descrivere la realtà. {{name}} non approvò il furto, ma comprese il conflitto che lo aveva generato e lo invitò alla discussione pubblica.'},
      {id:'a10z',after:'a10',scene:'Le conseguenze inattese',text:'Le targhe modificabili produssero anche problemi. Alcune persone cambiavano descrizione per evitare responsabilità; altre usavano parole ambigue per ottenere vantaggi. La città introdusse una distinzione tra identità personale e impegni assunti: si poteva cambiare idea su chi si era, ma restava necessario riparare danni e rispettare accordi. Libertà di evolvere non significava cancellare le conseguenze delle proprie azioni.'}
    ],
    'v2-11-12-calma-ora-silenzio': [
      {id:'c3z',after:'c3',includeInShort:true,includeInMedium:true,scene:'La pausa che sembra colpa',text:'Durante il minuto protetto, {{name}} sentì una voce interna accusarlo di essere improduttivo. L’orologiaio chiese da dove provenisse quella regola. Emersero messaggi ascoltati per anni: chi è impegnato vale di più, rispondere subito dimostra affetto, riposare è concesso soltanto dopo aver finito tutto. Ma il lavoro non finiva mai davvero. {{name}} iniziò a considerare il riposo non come premio, bensì come condizione necessaria per pensare, scegliere e mantenere relazioni senza esaurirsi.'},
      {id:'c5z',after:'c5',includeInShort:true,includeInMedium:true,scene:'La conversazione differita',text:'Un amico interpretò il silenzio di {{name}} come rifiuto. Invece di abbandonare il confine, parlarono di aspettative. Concordarono segnali semplici: un messaggio per dire “ho letto, rispondo domani”, un canale diverso per le urgenze reali e la libertà di non giustificare ogni pausa. Il rapporto non diventò più freddo; divenne meno dipendente dall’ansia di interpretare ogni ritardo.'},
      {id:'c7z',after:'c7',includeInShort:true,includeInMedium:true,scene:'Chi lavora quando gli altri riposano',text:'La proposta di un’unica ora quieta non funzionava per chi aveva turni serali o responsabilità di cura. {{name}} intervistò persone con ritmi differenti e suggerì finestre personali protette, riconosciute dagli altri sistemi. La città smise di associare il riposo a un preciso orario e iniziò a proteggerlo come bisogno universale con forme diverse. Un confine efficace non presuppone che tutte le vite abbiano la stessa agenda.'},
      {id:'c8z',after:'c8',scene:'Il ritorno delle idee lunghe',text:'Dopo alcune settimane, ricomparvero attività che richiedevano continuità: leggere capitoli interi, costruire, conversare senza controllare lo schermo, seguire un pensiero fino alla sua conseguenza. Gli abitanti si accorsero che la concentrazione non era soltanto una qualità individuale; dipendeva dall’ambiente e dalle interruzioni consentite. Progettare spazi meno invasivi restituì capacità che molti credevano di aver perso per sempre.'},
      {id:'c10z',after:'c10',scene:'Una sera non perfetta',text:'Una sera {{name}} interruppe il proprio tempo quieto molte volte e finì per sentirsi frustrato. L’orologiaio ricordò che anche il riposo può diventare una prestazione da giudicare. Non serviva ottenere ogni giorno la stessa calma. Il confine era uno strumento, non un esame. {{name}} spense una sola notifica, respirò per pochi secondi e considerò sufficiente quel gesto. La continuità si costruiva anche attraverso tentativi imperfetti.'}
    ],
    'v2-11-12-emozioni-versioni': [
      {id:'e3z',after:'e3',includeInShort:true,includeInMedium:true,scene:'La versione che cambia idea',text:'Uno specchio mostrava {{name}} dopo aver investito anni in una direzione e averla poi abbandonata. La figura non appariva fallita, ma portava con sé competenze, amicizie e una conoscenza più precisa dei propri limiti. «Cambiare non restituisce il tempo», disse, «ma il tempo trascorso non è automaticamente sprecato». La stanza tendeva a raccontare le vite come linee rette; quella versione mostrava che deviazioni e revisioni possono produrre continuità di un tipo diverso.'},
      {id:'e5z',after:'e5',includeInShort:true,includeInMedium:true,scene:'Il futuro costruito dalle circostanze',text:'Un altro specchio mostrava eventi fuori dal controllo di {{name}}: cambiamenti economici, incontri casuali, salute, opportunità disponibili o negate. Non significava che le scelte fossero inutili. Significava che nessuna versione futura poteva essere attribuita soltanto al merito o alla volontà. Riconoscere il ruolo delle circostanze riduceva sia l’arroganza davanti ai successi sia la colpa assoluta davanti agli ostacoli.'},
      {id:'e7z',after:'e7',includeInShort:true,includeInMedium:true,scene:'La versione osservata dai social',text:'Uno specchio non mostrava una vita intera, ma una sequenza di momenti selezionati per essere visti dagli altri. Sembrava brillante e continua, senza attese, ripetizioni o dubbi. {{name}} entrò dietro la superficie e trovò prove scartate, giornate normali e decisioni non fotografate. Capì che confrontare il proprio dietro le quinte con la vetrina altrui produce giudizi basati su informazioni incompatibili.'},
      {id:'e9z',after:'e9',scene:'Il consiglio delle persone reali',text:'Per verificare le immagini degli specchi, {{name}} parlò con adulti che avevano seguito percorsi diversi. Nessuno descrisse la propria vita come una scelta singola compiuta all’età giusta. Raccontarono tentativi, compromessi, occasioni inattese e valori cambiati. Le loro esperienze non fornivano istruzioni universali, ma rendevano meno credibile l’idea che esistesse una sequenza perfetta da indovinare in anticipo.'},
      {id:'e10z',after:'e10',scene:'Un impegno limitato',text:'Prima di lasciare la stanza, {{name}} formulò un impegno con una scadenza e un criterio di revisione: dedicare alcune settimane a un interesse, poi osservare energia, curiosità, difficoltà e desiderio di continuare. La decisione era seria proprio perché includeva il momento in cui sarebbe stata riesaminata. Non tutte le promesse devono essere eterne per avere valore; alcune servono a creare le condizioni di un’esperienza sincera.'}
    ],
    'v2-11-12-scoperta-atlante': [
      {id:'s3z',after:'s3',includeInShort:true,includeInMedium:true,scene:'La scala della fiducia',text:'Il cartografo mostrò che la conoscenza indiretta non ha un solo livello. Una ricostruzione sostenuta da molte fonti indipendenti, reperti coerenti e metodi trasparenti merita più fiducia di una storia basata su una testimonianza isolata. {{name}} disegnò una scala che non andava da “vero” a “falso”, ma da scarsamente sostenuto a molto ben sostenuto. Questo linguaggio permetteva di essere prudenti senza fingere che tutte le ipotesi avessero lo stesso peso.'},
      {id:'s5z',after:'s5',includeInShort:true,includeInMedium:true,scene:'La fonte che manca',text:'Nel ricostruire la pagina proibita, {{name}} si accorse che interi gruppi non avevano lasciato documenti scritti perché non avevano accesso agli archivi. Oggetti quotidiani, tradizioni orali e tracce ambientali diventavano quindi essenziali. L’assenza di una voce non dimostrava l’assenza di un’esperienza. L’atlante aggiunse una nota permanente: chiedere chi ha potuto produrre, conservare e rendere visibili le fonti disponibili.'},
      {id:'s7z',after:'s7',includeInShort:true,includeInMedium:true,scene:'L’esperimento personale',text:'Per esplorare una preferenza, {{name}} progettò un piccolo esperimento: provare un’attività in condizioni diverse, annotare motivazione prima e dopo, distinguere la difficoltà iniziale dal disinteresse reale. Il risultato non definiva per sempre il carattere, ma offriva dati migliori delle fantasie astratte. Conoscere se stessi richiedeva anche osservazione, non soltanto introspezione e racconti su ciò che si dovrebbe essere.'},
      {id:'s8z',after:'s8',scene:'La risposta che vende appartenenza',text:'Un venditore non prometteva soltanto certezza: prometteva un gruppo in cui sentirsi finalmente compresi. Le persone difendevano la risposta perché temevano di perdere la comunità costruita intorno a essa. {{name}} comprese che correggere un’informazione può minacciare relazioni e identità. Per questo offrì spazi di discussione in cui cambiare idea non comportasse umiliazione o espulsione. La qualità del confronto dipende anche dalla sicurezza sociale di chi partecipa.'},
      {id:'s10z',after:'s10',scene:'La domanda che resta aperta',text:'L’atlante conteneva una questione su cui esperti competenti continuavano a divergere pur condividendo molti dati. {{name}} studiò le diverse posizioni e scoprì assunzioni, priorità e limiti metodologici differenti. Non era necessario scegliere subito un campo. Poteva descrivere il disaccordo con precisione, indicare quali prove avrebbero modificato le posizioni e accettare che una sospensione del giudizio fosse talvolta la risposta più rigorosa disponibile.'}
    ]
  };

  const catalog = [].concat(
    global.FABLEA_STORIES_V2_2_4 || [],
    global.FABLEA_STORIES_V2_5_7 || [],
    global.FABLEA_STORIES_V2_8_10 || [],
    global.FABLEA_STORIES_V2_11_12 || []
  );

  catalog.forEach(story => {
    story.extensions = extensions[story.id] || [];
  });

  global.FABLEA_STORY_EXTENSIONS = extensions;
  global.FABLEA_STORIES_V2 = catalog;
})(window);
