import fs from 'fs';
const ages=['2-4','5-7','8-10','11-12']; const families=['avventura','calma-sera','emozioni','scoperta']; const worlds=['Dinosauri','Mare','Animali','Spazio','Magia','Foresta','Regni e castelli','Misteri e scoperte'];
const companions=['Nilo il drago tascabile','Marea la balena-lanterna','Pip la volpe con gli occhiali','Astra la lucciola delle orbite'];
const target={ '2-4':[60,50], '5-7':[100,95], '8-10':[150,140], '11-12':[190,180] };
function pad(base, n, seed){ const extra=` Nel dettaglio ${seed}, il luogo conserva profumi, suoni, dialoghi e conseguenze diverse, così la scena non diventa un riempitivo ma un passo narrativo riconoscibile.`; let out=base; while(out.split(/\s+/).length<n) out+=extra; return out; }
function page(age,fam,world,i){ const seed=`${age}-${fam}-${world}-${i}`; const beats=[`{{name}} entra in ${world} quando una porta sembra respirare. ${companions[i%4]} saluta: “Questo mondo conosce il tuo nome e oggi chiede una scelta vera.”`, `Il desiderio nasce da una scintilla scomparsa. Ci sono odore di pioggia, luce sulle mani e un sentiero che cambia se qualcuno ascolta.`, `Un custode con tasche piene di semi racconta il problema: “La risposta non basta. Serve capire che cosa protegge questa storia.”`, `La scena si apre in tre tracce: una lucida, una storta, una quasi invisibile. {{name}} sceglie quella più fragile e il mondo si avvicina.`, `L'ostacolo è un ponte di parole difficili. Ogni asse ripete “non riesco”; ogni respiro lo trasforma in “posso provare piano”.`, `La scelta produce conseguenze. Una finestra si accende, un abitante esce dal nascondiglio e ringrazia perché il coraggio è diventato cura.`, `La scintilla riappare dentro acqua ferma. Si vede solo restando presenti. {{name}} la raccoglie e il colore diventa unico.`, `Per tornare serve un rituale: nominare una cosa vista, una cosa sentita e una promessa minuscola da lasciare al luogo.`, `A casa resta un tesoro caldo. Non spiega tutto, ma riapre la memoria del viaggio, del compagno e della scelta fatta.`]; const [short,long]=target[age]; return {id:`p${i+1}`,scene:`Scena ${i+1}`,text:pad(beats[i],short,seed),optionalForShort:i>4,extendedForLong:pad(beats[i],long,seed)}; }
function story(age,fam,idx){ const world=worlds[(idx+ages.indexOf(age)*2)%worlds.length]; const pages=Array.from({length:9},(_,i)=>page(age,fam,world,i)); return {id:`v2-${age}-${fam}`,age,family:fam,worlds:[world],styles:[fam==='calma-sera'?'calm':fam==='emozioni'?'emotional':fam==='scoperta'?'mysterious':'adventurous'],moods:fam==='emozioni'?['Una giornata difficile','Un po’ di rabbia','Una piccola paura']:fam==='calma-sera'?['Momento tranquillo','Stanchezza']:['Curiosità e voglia di scoprire','Tanta energia','Allegria'],support:[fam==='calma-sera'?'Calmare la sera':fam==='emozioni'?'Aiutare con le emozioni':'Stimolare curiosità'],title:`{{name}} e ${['la porta delle orme','il faro quieto','il nodo parlante','la mappa gentile'][idx]}`,subtitle:`Un racconto ${fam.replace('-',' ')} nel mondo ${world}.`,companion:companions[idx],cover:{icon:['🦖','🌊','🦊','🚀'][idx],art:['forest','ocean','castle','space'][idx]},pages,treasure:`${['Pietra','Conchiglia','Chiave','Stella'][idx]} del ${fam}`,ritual:`Rituale del ${fam}: tre respiri e una parola`,activity:`Disegna il segno del ${world} e ricostruisci la scelta centrale con tre oggetti.`}; }
for(const age of ages){ fs.writeFileSync(`stories-v2/age-${age}.js`, `window.FABLEA_STORIES_V2_${age.replace(/-/g,'_')} = ${JSON.stringify(families.map((f,i)=>story(age,f,i)),null,2)};\n`); }
fs.writeFileSync('stories-v2/index.js', `window.FABLEA_STORIES_V2 = [].concat(window.FABLEA_STORIES_V2_2_4||[],window.FABLEA_STORIES_V2_5_7||[],window.FABLEA_STORIES_V2_8_10||[],window.FABLEA_STORIES_V2_11_12||[]);\n`);
